// Mazo de palabras — Super Taboo
// p: palabra, c: categoría, x: palabras prohibidas (solo para rondas de Taboo)
export const CATEGORIAS = [
  'Animales', 'Comida', 'Cine y series', 'Deportes',
  'Objetos', 'Lugares', 'Música y famosos', 'Acciones',
];

export const PALABRAS = [
  // ── Animales ──
  { p: 'Elefante', c: 'Animales', x: ['Trompa', 'Grande', 'Gris', 'Orejas', 'África'] },
  { p: 'Pingüino', c: 'Animales', x: ['Frío', 'Hielo', 'Ave', 'Antártida', 'Blanco y negro'] },
  { p: 'Tiburón', c: 'Animales', x: ['Mar', 'Dientes', 'Aleta', 'Peligroso', 'Película'] },
  { p: 'Jirafa', c: 'Animales', x: ['Cuello', 'Alta', 'Manchas', 'África', 'Hojas'] },
  { p: 'Perro', c: 'Animales', x: ['Ladrar', 'Mascota', 'Hueso', 'Gato', 'Correa'] },
  { p: 'Gato', c: 'Animales', x: ['Maullar', 'Ratón', 'Mascota', 'Bigotes', 'Siete vidas'] },
  { p: 'Caballo', c: 'Animales', x: ['Montar', 'Galopar', 'Crin', 'Granja', 'Jinete'] },
  { p: 'Abeja', c: 'Animales', x: ['Miel', 'Picar', 'Amarillo', 'Volar', 'Panal'] },
  { p: 'Cocodrilo', c: 'Animales', x: ['Río', 'Dientes', 'Verde', 'Reptil', 'Lagarto'] },
  { p: 'Mono', c: 'Animales', x: ['Banana', 'Selva', 'Trepar', 'Cola', 'Simio'] },
  { p: 'Búho', c: 'Animales', x: ['Noche', 'Sabio', 'Plumas', 'Girar', 'Ave'] },
  // ── Comida ──
  { p: 'Pizza', c: 'Comida', x: ['Queso', 'Italiana', 'Porción', 'Muzzarella', 'Horno'] },
  { p: 'Asado', c: 'Comida', x: ['Parrilla', 'Carne', 'Fuego', 'Domingo', 'Costillas'] },
  { p: 'Empanada', c: 'Comida', x: ['Relleno', 'Masa', 'Carne', 'Horno', 'Repulgue'] },
  { p: 'Helado', c: 'Comida', x: ['Frío', 'Cucurucho', 'Sabor', 'Verano', 'Postre'] },
  { p: 'Hamburguesa', c: 'Comida', x: ['Pan', 'Carne', 'Queso', 'Comida rápida', 'Papas fritas'] },
  { p: 'Sushi', c: 'Comida', x: ['Japonés', 'Arroz', 'Pescado', 'Palitos', 'Alga'] },
  { p: 'Chocolate', c: 'Comida', x: ['Dulce', 'Cacao', 'Marrón', 'Tableta', 'Bombón'] },
  { p: 'Café', c: 'Comida', x: ['Taza', 'Despertar', 'Negro', 'Cafeína', 'Desayuno'] },
  { p: 'Sopa', c: 'Comida', x: ['Caliente', 'Cuchara', 'Plato', 'Líquido', 'Invierno'] },
  { p: 'Taco', c: 'Comida', x: ['México', 'Tortilla', 'Picante', 'Relleno', 'Carne'] },
  { p: 'Ensalada', c: 'Comida', x: ['Lechuga', 'Verduras', 'Tomate', 'Saludable', 'Aderezo'] },
  // ── Cine y series ──
  { p: 'Superhéroe', c: 'Cine y series', x: ['Capa', 'Poderes', 'Volar', 'Salvar', 'Villano'] },
  { p: 'Zombi', c: 'Cine y series', x: ['Muerto', 'Cerebro', 'Caminar', 'Virus', 'Terror'] },
  { p: 'Titanic', c: 'Cine y series', x: ['Barco', 'Hundirse', 'Iceberg', 'Leonardo', 'Amor'] },
  { p: 'Mago', c: 'Cine y series', x: ['Varita', 'Hechizo', 'Sombrero', 'Conejo', 'Magia'] },
  { p: 'Vampiro', c: 'Cine y series', x: ['Sangre', 'Colmillos', 'Noche', 'Ajo', 'Drácula'] },
  { p: 'Pochoclo', c: 'Cine y series', x: ['Maíz', 'Cine', 'Balde', 'Explotar', 'Película'] },
  { p: 'Director de cine', c: 'Cine y series', x: ['Película', 'Cámara', 'Acción', 'Rodar', 'Corte'] },
  { p: 'Premio Oscar', c: 'Cine y series', x: ['Estatua', 'Hollywood', 'Actor', 'Alfombra roja', 'Ganador'] },
  { p: 'Dinosaurio', c: 'Cine y series', x: ['Extinto', 'Fósil', 'Gigante', 'Prehistórico', 'Reptil'] },
  { p: 'Pirata', c: 'Cine y series', x: ['Barco', 'Parche', 'Tesoro', 'Loro', 'Espada'] },
  { p: 'Bruja', c: 'Cine y series', x: ['Escoba', 'Hechizo', 'Caldero', 'Sombrero', 'Magia'] },
  // ── Deportes ──
  { p: 'Fútbol', c: 'Deportes', x: ['Pelota', 'Gol', 'Cancha', 'Equipo', 'Arco'] },
  { p: 'Tenis', c: 'Deportes', x: ['Raqueta', 'Pelota', 'Red', 'Saque', 'Cancha'] },
  { p: 'Natación', c: 'Deportes', x: ['Agua', 'Pileta', 'Nadar', 'Brazadas', 'Malla'] },
  { p: 'Básquet', c: 'Deportes', x: ['Aro', 'Pelota', 'Canasta', 'Rebote', 'Picar'] },
  { p: 'Boxeo', c: 'Deportes', x: ['Guantes', 'Ring', 'Golpe', 'Nocaut', 'Pelea'] },
  { p: 'Maratón', c: 'Deportes', x: ['Correr', 'Kilómetros', 'Meta', 'Resistencia', 'Carrera'] },
  { p: 'Ajedrez', c: 'Deportes', x: ['Tablero', 'Rey', 'Jaque', 'Piezas', 'Estrategia'] },
  { p: 'Surf', c: 'Deportes', x: ['Ola', 'Tabla', 'Mar', 'Equilibrio', 'Playa'] },
  { p: 'Esquí', c: 'Deportes', x: ['Nieve', 'Montaña', 'Tablas', 'Bastones', 'Invierno'] },
  { p: 'Yoga', c: 'Deportes', x: ['Estirar', 'Posturas', 'Relajación', 'Colchoneta', 'Respirar'] },
  { p: 'Árbitro', c: 'Deportes', x: ['Silbato', 'Tarjeta', 'Falta', 'Juez', 'Partido'] },
  // ── Objetos ──
  { p: 'Paraguas', c: 'Objetos', x: ['Lluvia', 'Abrir', 'Mojarse', 'Mango', 'Cubrirse'] },
  { p: 'Espejo', c: 'Objetos', x: ['Reflejo', 'Vidrio', 'Mirarse', 'Baño', 'Imagen'] },
  { p: 'Almohada', c: 'Objetos', x: ['Dormir', 'Cama', 'Cabeza', 'Suave', 'Plumas'] },
  { p: 'Tijera', c: 'Objetos', x: ['Cortar', 'Papel', 'Filo', 'Dos', 'Peluquería'] },
  { p: 'Heladera', c: 'Objetos', x: ['Frío', 'Cocina', 'Comida', 'Puerta', 'Congelador'] },
  { p: 'Celular', c: 'Objetos', x: ['Llamar', 'Pantalla', 'Apps', 'Batería', 'Mensaje'] },
  { p: 'Llave', c: 'Objetos', x: ['Puerta', 'Abrir', 'Cerradura', 'Candado', 'Auto'] },
  { p: 'Reloj', c: 'Objetos', x: ['Hora', 'Muñeca', 'Agujas', 'Tiempo', 'Despertador'] },
  { p: 'Escoba', c: 'Objetos', x: ['Barrer', 'Limpiar', 'Palo', 'Piso', 'Bruja'] },
  { p: 'Anteojos', c: 'Objetos', x: ['Ver', 'Ojos', 'Marco', 'Lentes', 'Sol'] },
  { p: 'Cepillo de dientes', c: 'Objetos', x: ['Pasta', 'Boca', 'Lavar', 'Baño', 'Higiene'] },
  // ── Lugares ──
  { p: 'Playa', c: 'Lugares', x: ['Arena', 'Mar', 'Sol', 'Sombrilla', 'Verano'] },
  { p: 'Hospital', c: 'Lugares', x: ['Médico', 'Enfermo', 'Camilla', 'Ambulancia', 'Cirugía'] },
  { p: 'Escuela', c: 'Lugares', x: ['Maestra', 'Alumnos', 'Pizarrón', 'Recreo', 'Aula'] },
  { p: 'Aeropuerto', c: 'Lugares', x: ['Avión', 'Valija', 'Vuelo', 'Pasaporte', 'Despegar'] },
  { p: 'Supermercado', c: 'Lugares', x: ['Comprar', 'Carrito', 'Góndola', 'Caja', 'Precios'] },
  { p: 'Cine', c: 'Lugares', x: ['Película', 'Pantalla', 'Butaca', 'Entrada', 'Pochoclo'] },
  { p: 'Museo', c: 'Lugares', x: ['Arte', 'Cuadros', 'Historia', 'Exhibición', 'Antiguo'] },
  { p: 'Selva', c: 'Lugares', x: ['Árboles', 'Animales', 'Húmedo', 'Tarzán', 'Verde'] },
  { p: 'Desierto', c: 'Lugares', x: ['Arena', 'Calor', 'Camello', 'Cactus', 'Seco'] },
  { p: 'Luna', c: 'Lugares', x: ['Espacio', 'Astronauta', 'Noche', 'Cráter', 'Llena'] },
  { p: 'Gimnasio', c: 'Lugares', x: ['Pesas', 'Ejercicio', 'Músculos', 'Entrenar', 'Máquinas'] },
  // ── Música y famosos ──
  { p: 'Guitarra', c: 'Música y famosos', x: ['Cuerdas', 'Tocar', 'Rock', 'Acordes', 'Instrumento'] },
  { p: 'Batería', c: 'Música y famosos', x: ['Palillos', 'Ritmo', 'Tambor', 'Platillos', 'Golpear'] },
  { p: 'Micrófono', c: 'Música y famosos', x: ['Cantar', 'Voz', 'Escenario', 'Karaoke', 'Hablar'] },
  { p: 'Karaoke', c: 'Música y famosos', x: ['Cantar', 'Letra', 'Pantalla', 'Micrófono', 'Bar'] },
  { p: 'Ópera', c: 'Música y famosos', x: ['Cantar', 'Teatro', 'Soprano', 'Clásica', 'Italiano'] },
  { p: 'DJ', c: 'Música y famosos', x: ['Música', 'Mezclar', 'Fiesta', 'Bandeja', 'Electrónica'] },
  { p: 'Tango', c: 'Música y famosos', x: ['Baile', 'Buenos Aires', 'Gardel', 'Pareja', 'Bandoneón'] },
  { p: 'Coro', c: 'Música y famosos', x: ['Cantar', 'Grupo', 'Voces', 'Iglesia', 'Director'] },
  { p: 'Violín', c: 'Música y famosos', x: ['Cuerdas', 'Arco', 'Clásica', 'Orquesta', 'Hombro'] },
  { p: 'Rockstar', c: 'Música y famosos', x: ['Escenario', 'Guitarra', 'Fama', 'Gira', 'Fans'] },
  { p: 'Cumbia', c: 'Música y famosos', x: ['Baile', 'Fiesta', 'Ritmo', 'Música', 'Tropical'] },
  // ── Acciones ──
  { p: 'Estornudar', c: 'Acciones', x: ['Nariz', 'Achís', 'Resfrío', 'Pañuelo', 'Salud'] },
  { p: 'Bostezar', c: 'Acciones', x: ['Sueño', 'Boca', 'Cansado', 'Aburrido', 'Abrir'] },
  { p: 'Aplaudir', c: 'Acciones', x: ['Manos', 'Bravo', 'Teatro', 'Felicitar', 'Ruido'] },
  { p: 'Cocinar', c: 'Acciones', x: ['Comida', 'Olla', 'Chef', 'Receta', 'Fuego'] },
  { p: 'Bailar', c: 'Acciones', x: ['Música', 'Mover', 'Fiesta', 'Pareja', 'Ritmo'] },
  { p: 'Dormir', c: 'Acciones', x: ['Cama', 'Noche', 'Soñar', 'Roncar', 'Descansar'] },
  { p: 'Manejar', c: 'Acciones', x: ['Auto', 'Volante', 'Ruta', 'Licencia', 'Conducir'] },
  { p: 'Pescar', c: 'Acciones', x: ['Caña', 'Río', 'Anzuelo', 'Pez', 'Paciencia'] },
  { p: 'Pintar', c: 'Acciones', x: ['Pincel', 'Colores', 'Cuadro', 'Pared', 'Artista'] },
  { p: 'Silbar', c: 'Acciones', x: ['Boca', 'Sonido', 'Melodía', 'Labios', 'Aire'] },
  { p: 'Abrazar', c: 'Acciones', x: ['Brazos', 'Cariño', 'Apretar', 'Saludo', 'Amor'] },
];
