// Mazo de palabras — Super Taboo
// p: palabra, c: categoría, x: palabras prohibidas (solo para rondas de Taboo)
export interface Palabra {
  p: string;
  c: string;
  x: string[];
}

export const CATEGORIAS = [
  'Animales', 'Comida', 'Cine y series', 'Películas', 'Actores y famosos', 'Personajes',
  'Deportes', 'Objetos', 'Lugares', 'Música y famosos', 'Acciones',
];

export const PALABRAS: Palabra[] = [
  // ── Animales ──
  { p: 'Elefante', c: 'Animales', x: ['Trompa', 'Grande', 'Gris', 'Orejas', 'África'] },
  { p: 'Pingüino', c: 'Animales', x: ['Frío', 'Hielo', 'Ave', 'Antártida', 'Blanco y negro'] },
  { p: 'Tiburón', c: 'Animales', x: ['Mar', 'Dientes', 'Aleta', 'Peligroso', 'Película'] },
  { p: 'Jirafa', c: 'Animales', x: ['Cuello', 'Alta', 'Manchas', 'África', 'Hojas'] },
  { p: 'Perro', c: 'Animales', x: ['Ladrar', 'Mascota', 'Hueso', 'Gato', 'Correa'] },
  { p: 'Gato', c: 'Animales', x: ['Maullar', 'Ratón', 'Mascota', 'Bigotes', 'Siete vidas'] },
  { p: 'Caballo', c: 'Animales', x: ['Montar', 'Galopar', 'Crin', 'Granja', 'Jinete'] },
  { p: 'Abeja', c: 'Animales', x: ['Miel', 'Picar', 'Amarillo', 'Volar', 'Panal'] },
  { p: 'Cocodrilo', c: 'Animales', x: ['Río', 'Dientes', 'Verde', 'Reptil', 'Lagarto'] },
  { p: 'Mono', c: 'Animales', x: ['Banana', 'Selva', 'Trepar', 'Cola', 'Simio'] },
  { p: 'Búho', c: 'Animales', x: ['Noche', 'Sabio', 'Plumas', 'Girar', 'Ave'] },
  // ── Comida ──
  { p: 'Pizza', c: 'Comida', x: ['Queso', 'Italiana', 'Porción', 'Muzzarella', 'Horno'] },
  { p: 'Asado', c: 'Comida', x: ['Parrilla', 'Carne', 'Fuego', 'Domingo', 'Costillas'] },
  { p: 'Empanada', c: 'Comida', x: ['Relleno', 'Masa', 'Carne', 'Horno', 'Repulgue'] },
  { p: 'Helado', c: 'Comida', x: ['Frío', 'Cucurucho', 'Sabor', 'Verano', 'Postre'] },
  { p: 'Hamburguesa', c: 'Comida', x: ['Pan', 'Carne', 'Queso', 'Comida rápida', 'Papas fritas'] },
  { p: 'Sushi', c: 'Comida', x: ['Japonés', 'Arroz', 'Pescado', 'Palitos', 'Alga'] },
  { p: 'Chocolate', c: 'Comida', x: ['Dulce', 'Cacao', 'Marrón', 'Tableta', 'Bombón'] },
  { p: 'Café', c: 'Comida', x: ['Taza', 'Despertar', 'Negro', 'Cafeína', 'Desayuno'] },
  { p: 'Sopa', c: 'Comida', x: ['Caliente', 'Cuchara', 'Plato', 'Líquido', 'Invierno'] },
  { p: 'Taco', c: 'Comida', x: ['México', 'Tortilla', 'Picante', 'Relleno', 'Carne'] },
  { p: 'Ensalada', c: 'Comida', x: ['Lechuga', 'Verduras', 'Tomate', 'Saludable', 'Aderezo'] },
  // ── Cine y series ──
  { p: 'Superhéroe', c: 'Cine y series', x: ['Capa', 'Poderes', 'Volar', 'Salvar', 'Villano'] },
  { p: 'Zombi', c: 'Cine y series', x: ['Muerto', 'Cerebro', 'Caminar', 'Virus', 'Terror'] },
  { p: 'Titanic', c: 'Cine y series', x: ['Barco', 'Hundirse', 'Iceberg', 'Leonardo', 'Amor'] },
  { p: 'Mago', c: 'Cine y series', x: ['Varita', 'Hechizo', 'Sombrero', 'Conejo', 'Magia'] },
  { p: 'Vampiro', c: 'Cine y series', x: ['Sangre', 'Colmillos', 'Noche', 'Ajo', 'Drácula'] },
  { p: 'Pochoclo', c: 'Cine y series', x: ['Maíz', 'Cine', 'Balde', 'Explotar', 'Película'] },
  { p: 'Director de cine', c: 'Cine y series', x: ['Película', 'Cámara', 'Acción', 'Rodar', 'Corte'] },
  { p: 'Premio Oscar', c: 'Cine y series', x: ['Estatua', 'Hollywood', 'Actor', 'Alfombra roja', 'Ganador'] },
  { p: 'Dinosaurio', c: 'Cine y series', x: ['Extinto', 'Fósil', 'Gigante', 'Prehistórico', 'Reptil'] },
  { p: 'Pirata', c: 'Cine y series', x: ['Barco', 'Parche', 'Tesoro', 'Loro', 'Espada'] },
  { p: 'Bruja', c: 'Cine y series', x: ['Escoba', 'Hechizo', 'Caldero', 'Sombrero', 'Magia'] },
  // ── Películas ──
  { p: 'El Rey León', c: 'Películas', x: ['Simba', 'África', 'Hakuna Matata', 'Disney', 'Selva'] },
  { p: 'Toy Story', c: 'Películas', x: ['Juguetes', 'Woody', 'Buzz', 'Pixar', 'Vaquero'] },
  { p: 'Harry Potter', c: 'Películas', x: ['Mago', 'Varita', 'Hogwarts', 'Anteojos', 'Cicatriz'] },
  { p: 'Jurassic Park', c: 'Películas', x: ['Dinosaurios', 'Parque', 'Isla', 'ADN', 'Tiranosaurio'] },
  { p: 'Shrek', c: 'Películas', x: ['Ogro', 'Verde', 'Burro', 'Fiona', 'Pantano'] },
  { p: 'Frozen', c: 'Películas', x: ['Hielo', 'Elsa', 'Princesa', 'Muñeco de nieve', 'Libre soy'] },
  { p: 'Volver al Futuro', c: 'Películas', x: ['DeLorean', 'Viaje en el tiempo', 'Marty', 'Doc', 'Auto'] },
  { p: 'El Padrino', c: 'Películas', x: ['Mafia', 'Italia', 'Don', 'Oferta', 'Corleone'] },
  { p: 'Matrix', c: 'Películas', x: ['Pastilla', 'Neo', 'Realidad virtual', 'Agente', 'Lentes negros'] },
  { p: 'Piratas del Caribe', c: 'Películas', x: ['Jack Sparrow', 'Barco', 'Tesoro', 'Mar', 'Ron'] },
  { p: 'Rápido y Furioso', c: 'Películas', x: ['Autos', 'Carreras', 'Familia', 'Toretto', 'Velocidad'] },
  { p: 'Buscando a Nemo', c: 'Películas', x: ['Pez', 'Payaso', 'Océano', 'Dory', 'Perdido'] },
  { p: 'Los Increíbles', c: 'Películas', x: ['Superhéroes', 'Familia', 'Pixar', 'Traje', 'Poderes'] },
  { p: 'Mi Villano Favorito', c: 'Películas', x: ['Minions', 'Gru', 'Amarillo', 'Villano', 'Nenas'] },
  { p: 'Avatar', c: 'Películas', x: ['Azul', 'Pandora', 'Planeta', 'Alienígenas', 'James Cameron'] },
  { p: 'Avengers', c: 'Películas', x: ['Marvel', 'Superhéroes', 'Thanos', 'Iron Man', 'Equipo'] },
  { p: 'El Señor de los Anillos', c: 'Películas', x: ['Frodo', 'Anillo', 'Gandalf', 'Hobbit', 'Mordor'] },
  { p: 'Star Wars', c: 'Películas', x: ['Espada láser', 'Darth Vader', 'Galaxia', 'Fuerza', 'Yoda'] },
  { p: 'Terminator', c: 'Películas', x: ['Robot', 'Futuro', 'Schwarzenegger', 'Volveré', 'Máquina'] },
  { p: 'Rocky', c: 'Películas', x: ['Boxeo', 'Stallone', 'Escaleras', 'Filadelfia', 'Campeón'] },
  { p: 'E.T.', c: 'Películas', x: ['Extraterrestre', 'Bicicleta', 'Teléfono', 'Casa', 'Dedo'] },
  { p: 'La Era de Hielo', c: 'Películas', x: ['Ardilla', 'Bellota', 'Mamut', 'Perezoso', 'Glaciar'] },
  { p: 'Madagascar', c: 'Películas', x: ['Zoológico', 'León', 'Pingüinos', 'Isla', 'África'] },
  { p: 'Kung Fu Panda', c: 'Películas', x: ['Oso', 'Artes marciales', 'China', 'Po', 'Fideos'] },
  { p: 'Ratatouille', c: 'Películas', x: ['Rata', 'Cocinar', 'París', 'Chef', 'Restaurante'] },
  { p: 'Coco', c: 'Películas', x: ['México', 'Día de los muertos', 'Guitarra', 'Familia', 'Recuérdame'] },
  { p: 'Up', c: 'Películas', x: ['Globos', 'Casa', 'Viejito', 'Volar', 'Aventura'] },
  { p: 'Monsters Inc', c: 'Películas', x: ['Sustos', 'Puertas', 'Sully', 'Mike', 'Gritos'] },
  { p: 'Cars', c: 'Películas', x: ['Autos', 'Carreras', 'Rayo McQueen', 'Pixar', 'Rueda'] },
  { p: 'Grease', c: 'Películas', x: ['Baile', 'Musical', 'John Travolta', 'Secundaria', 'Cuero'] },
  { p: 'Duro de Matar', c: 'Películas', x: ['Bruce Willis', 'Navidad', 'Edificio', 'Policía', 'Explosión'] },
  { p: 'Misión Imposible', c: 'Películas', x: ['Tom Cruise', 'Espía', 'Máscara', 'Colgado', 'Bomba'] },
  { p: 'Mary Poppins', c: 'Películas', x: ['Niñera', 'Paraguas', 'Volar', 'Magia', 'Supercalifragilístico'] },
  { p: 'El Exorcista', c: 'Películas', x: ['Terror', 'Posesión', 'Cura', 'Demonio', 'Cabeza'] },
  { p: 'Karate Kid', c: 'Películas', x: ['Patada', 'Maestro', 'Miyagi', 'Encerar', 'Grulla'] },
  { p: 'Nueve Reinas', c: 'Películas', x: ['Estafa', 'Argentina', 'Darín', 'Estampillas', 'Timo'] },
  { p: 'Relatos Salvajes', c: 'Películas', x: ['Argentina', 'Episodios', 'Venganza', 'Avión', 'Casamiento'] },
  { p: 'Metegol', c: 'Películas', x: ['Argentina', 'Jugadores', 'Fútbol', 'Muñecos', 'Animada'] },
  { p: 'Esperando la Carroza', c: 'Películas', x: ['Mamá Cora', 'Argentina', 'Familia', 'Velorio', 'Tres empanadas'] },
  { p: 'Gladiador', c: 'Películas', x: ['Roma', 'Coliseo', 'Espada', 'Máximo', 'Emperador'] },
  { p: 'Forrest Gump', c: 'Películas', x: ['Correr', 'Chocolates', 'Pluma', 'Tom Hanks', 'Banco'] },
  // ── Actores y famosos ──
  { p: 'Leonardo DiCaprio', c: 'Actores y famosos', x: ['Titanic', 'Oscar', 'Lobo de Wall Street', 'Actor', 'Barco'] },
  { p: 'Brad Pitt', c: 'Actores y famosos', x: ['Angelina', 'Rubio', 'Hollywood', 'Actor', 'Club de la Pelea'] },
  { p: 'Jim Carrey', c: 'Actores y famosos', x: ['La Máscara', 'Comedia', 'Ace Ventura', 'Caras', 'Grinch'] },
  { p: 'La Roca', c: 'Actores y famosos', x: ['Músculos', 'Lucha libre', 'Pelado', 'Actor', 'Piedra'] },
  { p: 'Angelina Jolie', c: 'Actores y famosos', x: ['Brad', 'Labios', 'Tomb Raider', 'Actriz', 'Maléfica'] },
  { p: 'Tom Cruise', c: 'Actores y famosos', x: ['Misión Imposible', 'Top Gun', 'Bajo', 'Actor', 'Acción'] },
  { p: 'Will Smith', c: 'Actores y famosos', x: ['Príncipe del rap', 'Cachetada', 'Men in Black', 'Actor', 'Oscar'] },
  { p: 'Keanu Reeves', c: 'Actores y famosos', x: ['Matrix', 'John Wick', 'Neo', 'Actor', 'Motos'] },
  { p: 'Johnny Depp', c: 'Actores y famosos', x: ['Pirata', 'Jack Sparrow', 'Tijeras', 'Actor', 'Sombrero'] },
  { p: 'Ricardo Darín', c: 'Actores y famosos', x: ['Argentino', 'El secreto de sus ojos', 'Nueve reinas', 'Actor', 'Relatos salvajes'] },
  { p: 'Guillermo Francella', c: 'Actores y famosos', x: ['Casados con hijos', 'Bigote', 'Comedia', 'Argentino', 'El Clan'] },
  { p: 'Lionel Messi', c: 'Actores y famosos', x: ['Fútbol', 'Argentina', 'Diez', 'Barcelona', 'Copa del mundo'] },
  { p: 'Diego Maradona', c: 'Actores y famosos', x: ['Diez', 'Mano de Dios', 'Fútbol', 'Barrilete cósmico', 'Nápoles'] },
  { p: 'Cristiano Ronaldo', c: 'Actores y famosos', x: ['Portugal', 'Fútbol', 'Siuuu', 'Real Madrid', 'CR7'] },
  { p: 'Michael Jackson', c: 'Actores y famosos', x: ['Rey del pop', 'Moonwalk', 'Thriller', 'Guante', 'Cantante'] },
  { p: 'Shakira', c: 'Actores y famosos', x: ['Colombia', 'Caderas', 'Cantante', 'Piqué', 'Waka Waka'] },
  { p: 'Madonna', c: 'Actores y famosos', x: ['Reina del pop', 'Cantante', 'Rubia', 'Like a Virgin', 'Evita'] },
  { p: 'Freddie Mercury', c: 'Actores y famosos', x: ['Queen', 'Bigote', 'Bohemian Rhapsody', 'Cantante', 'We Will Rock You'] },
  { p: 'Elvis Presley', c: 'Actores y famosos', x: ['Rey del rock', 'Jopo', 'Cantante', 'Caderas', 'Memphis'] },
  { p: 'Charly García', c: 'Actores y famosos', x: ['Bigote bicolor', 'Rock nacional', 'Piano', 'Cantante', 'Say No More'] },
  { p: 'Bizarrap', c: 'Actores y famosos', x: ['Sesiones', 'Gorra', 'Lentes', 'Productor', 'Música'] },
  { p: 'Susana Giménez', c: 'Actores y famosos', x: ['Diva', 'Teléfono', 'Rubia', 'Televisión', 'Shock'] },
  { p: 'Marcelo Tinelli', c: 'Actores y famosos', x: ['ShowMatch', 'Conductor', 'Bailando', 'Televisión', 'Cámara'] },
  { p: 'Mirtha Legrand', c: 'Actores y famosos', x: ['Almuerzos', 'Televisión', 'Diva', 'Mesa', 'Chiquita'] },
  { p: 'Moria Casán', c: 'Actores y famosos', x: ['Diva', 'Lengua', 'Vedette', 'One', 'Jurado'] },
  { p: 'Lali Espósito', c: 'Actores y famosos', x: ['Cantante', 'Casi Ángeles', 'Pop', 'Actriz', 'Disciplina'] },
  { p: 'El Dibu Martínez', c: 'Actores y famosos', x: ['Arquero', 'Penales', 'Selección', 'Atajada', 'Baile'] },
  { p: 'Usain Bolt', c: 'Actores y famosos', x: ['Correr', 'Jamaica', 'Rayo', 'Velocista', 'Récord'] },
  { p: 'Mike Tyson', c: 'Actores y famosos', x: ['Boxeo', 'Oreja', 'Nocaut', 'Tatuaje', 'Campeón'] },
  { p: 'Michael Jordan', c: 'Actores y famosos', x: ['Básquet', 'Chicago Bulls', 'Veintitrés', 'Zapatillas', 'Volar'] },
  { p: 'Serena Williams', c: 'Actores y famosos', x: ['Tenis', 'Raqueta', 'Hermanas', 'Campeona', 'Estados Unidos'] },
  { p: 'Albert Einstein', c: 'Actores y famosos', x: ['Científico', 'Relatividad', 'Genio', 'Lengua', 'Pelo loco'] },
  { p: 'Morgan Freeman', c: 'Actores y famosos', x: ['Voz', 'Dios', 'Narrador', 'Actor', 'Pecas'] },
  { p: 'Arnold Schwarzenegger', c: 'Actores y famosos', x: ['Terminator', 'Músculos', 'Austria', 'Gobernador', 'Volveré'] },
  { p: 'Sylvester Stallone', c: 'Actores y famosos', x: ['Rocky', 'Rambo', 'Boxeo', 'Actor', 'Músculos'] },
  { p: 'Emma Watson', c: 'Actores y famosos', x: ['Hermione', 'Harry Potter', 'Actriz', 'Inglesa', 'Maga'] },
  { p: 'Julia Roberts', c: 'Actores y famosos', x: ['Mujer bonita', 'Sonrisa', 'Actriz', 'Pelirroja', 'Hollywood'] },
  { p: 'Adam Sandler', c: 'Actores y famosos', x: ['Comedia', 'Actor', 'Netflix', 'Como si fuera la primera vez', 'Gracioso'] },
  { p: 'Danny DeVito', c: 'Actores y famosos', x: ['Bajito', 'Actor', 'Matilda', 'Pelado', 'Comedia'] },
  { p: 'Antonio Banderas', c: 'Actores y famosos', x: ['Español', 'Zorro', 'Gato con botas', 'Actor', 'Acento'] },
  { p: 'Jackie Chan', c: 'Actores y famosos', x: ['Artes marciales', 'China', 'Acrobacias', 'Actor', 'Golpes'] },
  // ── Personajes ──
  { p: 'Batman', c: 'Personajes', x: ['Murciélago', 'Ciudad Gótica', 'Robin', 'Guasón', 'Capa'] },
  { p: 'Superman', c: 'Personajes', x: ['Capa', 'Volar', 'Kriptonita', 'Clark Kent', 'Acero'] },
  { p: 'Homero Simpson', c: 'Personajes', x: ['Amarillo', 'Donas', 'Springfield', 'Bart', 'Cerveza'] },
  { p: 'Bob Esponja', c: 'Personajes', x: ['Amarillo', 'Mar', 'Patricio', 'Cangreburger', 'Piña'] },
  { p: 'Mickey Mouse', c: 'Personajes', x: ['Ratón', 'Disney', 'Orejas', 'Minnie', 'Guantes'] },
  { p: 'El Hombre Araña', c: 'Personajes', x: ['Telaraña', 'Trepar', 'Rojo', 'Peter Parker', 'Araña'] },
  { p: 'Darth Vader', c: 'Personajes', x: ['Star Wars', 'Casco', 'Padre', 'Lado oscuro', 'Respiración'] },
  { p: 'Papá Noel', c: 'Personajes', x: ['Navidad', 'Regalos', 'Rojo', 'Barba', 'Renos'] },
  { p: 'Pikachu', c: 'Personajes', x: ['Pokémon', 'Amarillo', 'Rayo', 'Ash', 'Ratón'] },
  { p: 'Mario Bros', c: 'Personajes', x: ['Plomero', 'Bigote', 'Hongo', 'Luigi', 'Princesa'] },
  { p: 'El Grinch', c: 'Personajes', x: ['Navidad', 'Verde', 'Robar', 'Odiar', 'Regalos'] },
  { p: 'El Guasón', c: 'Personajes', x: ['Batman', 'Payaso', 'Risa', 'Villano', 'Pelo verde'] },
  { p: 'Mujer Maravilla', c: 'Personajes', x: ['Amazona', 'Lazo', 'Superheroína', 'Tiara', 'Escudo'] },
  { p: 'Hulk', c: 'Personajes', x: ['Verde', 'Enojado', 'Gigante', 'Músculos', 'Aplastar'] },
  { p: 'Iron Man', c: 'Personajes', x: ['Armadura', 'Tony Stark', 'Marvel', 'Volar', 'Millonario'] },
  { p: 'Thor', c: 'Personajes', x: ['Martillo', 'Dios', 'Trueno', 'Rubio', 'Asgard'] },
  { p: 'Capitán América', c: 'Personajes', x: ['Escudo', 'Soldado', 'Estados Unidos', 'Vengador', 'Estrella'] },
  { p: 'Goku', c: 'Personajes', x: ['Dragon Ball', 'Saiyajin', 'Kamehameha', 'Pelo', 'Esferas'] },
  { p: 'Naruto', c: 'Personajes', x: ['Ninja', 'Anime', 'Zorro', 'Naranja', 'Aldea'] },
  { p: 'Pato Donald', c: 'Personajes', x: ['Pato', 'Disney', 'Marinero', 'Enojado', 'Sin pantalones'] },
  { p: 'Winnie Pooh', c: 'Personajes', x: ['Oso', 'Miel', 'Amarillo', 'Puerquito', 'Bosque'] },
  { p: 'Pinocho', c: 'Personajes', x: ['Nariz', 'Mentira', 'Madera', 'Muñeco', 'Grillo'] },
  { p: 'Peter Pan', c: 'Personajes', x: ['Volar', 'Nunca Jamás', 'Campanita', 'Garfio', 'Niño'] },
  { p: 'Cenicienta', c: 'Personajes', x: ['Zapato', 'Princesa', 'Medianoche', 'Carroza', 'Madrastra'] },
  { p: 'Blancanieves', c: 'Personajes', x: ['Manzana', 'Enanos', 'Espejo', 'Princesa', 'Bruja'] },
  { p: 'La Sirenita', c: 'Personajes', x: ['Mar', 'Cola', 'Ariel', 'Cangrejo', 'Voz'] },
  { p: 'Aladdín', c: 'Personajes', x: ['Genio', 'Lámpara', 'Alfombra', 'Deseos', 'Príncipe'] },
  { p: 'Buzz Lightyear', c: 'Personajes', x: ['Toy Story', 'Espacio', 'Al infinito', 'Juguete', 'Alas'] },
  { p: 'Minion', c: 'Personajes', x: ['Amarillo', 'Banana', 'Anteojos', 'Gru', 'Idioma'] },
  { p: 'Gollum', c: 'Personajes', x: ['Anillo', 'Mi precioso', 'Hobbit', 'Cueva', 'Flaco'] },
  { p: 'Frankenstein', c: 'Personajes', x: ['Monstruo', 'Verde', 'Tornillos', 'Científico', 'Rayo'] },
  { p: 'La Momia', c: 'Personajes', x: ['Vendas', 'Egipto', 'Sarcófago', 'Maldición', 'Muerto'] },
  { p: 'Chucky', c: 'Personajes', x: ['Muñeco', 'Terror', 'Cuchillo', 'Pelirrojo', 'Overol'] },
  { p: 'Godzilla', c: 'Personajes', x: ['Monstruo', 'Japón', 'Gigante', 'Ciudad', 'Lagarto'] },
  { p: 'King Kong', c: 'Personajes', x: ['Gorila', 'Gigante', 'Edificio', 'Isla', 'Rubia'] },
  { p: 'Sonic', c: 'Personajes', x: ['Erizo', 'Azul', 'Velocidad', 'Anillos', 'Sega'] },
  { p: 'Pac-Man', c: 'Personajes', x: ['Comer', 'Fantasmas', 'Amarillo', 'Laberinto', 'Arcade'] },
  { p: 'Lara Croft', c: 'Personajes', x: ['Tomb Raider', 'Aventurera', 'Tumbas', 'Videojuego', 'Trenza'] },
  { p: 'Mr. Bean', c: 'Personajes', x: ['Inglés', 'Comedia', 'Oso de peluche', 'Auto verde', 'Gestos'] },
  { p: 'El Chavo', c: 'Personajes', x: ['Barril', 'Vecindad', 'Ocho', 'México', 'Torta de jamón'] },
  { p: 'El Chapulín Colorado', c: 'Personajes', x: ['Antenas', 'Rojo', 'Chipote chillón', 'Héroe', 'México'] },
  // ── Deportes ──
  { p: 'Fútbol', c: 'Deportes', x: ['Pelota', 'Gol', 'Cancha', 'Equipo', 'Arco'] },
  { p: 'Tenis', c: 'Deportes', x: ['Raqueta', 'Pelota', 'Red', 'Saque', 'Cancha'] },
  { p: 'Natación', c: 'Deportes', x: ['Agua', 'Pileta', 'Nadar', 'Brazadas', 'Malla'] },
  { p: 'Básquet', c: 'Deportes', x: ['Aro', 'Pelota', 'Canasta', 'Rebote', 'Picar'] },
  { p: 'Boxeo', c: 'Deportes', x: ['Guantes', 'Ring', 'Golpe', 'Nocaut', 'Pelea'] },
  { p: 'Maratón', c: 'Deportes', x: ['Correr', 'Kilómetros', 'Meta', 'Resistencia', 'Carrera'] },
  { p: 'Ajedrez', c: 'Deportes', x: ['Tablero', 'Rey', 'Jaque', 'Piezas', 'Estrategia'] },
  { p: 'Surf', c: 'Deportes', x: ['Ola', 'Tabla', 'Mar', 'Equilibrio', 'Playa'] },
  { p: 'Esquí', c: 'Deportes', x: ['Nieve', 'Montaña', 'Tablas', 'Bastones', 'Invierno'] },
  { p: 'Yoga', c: 'Deportes', x: ['Estirar', 'Posturas', 'Relajación', 'Colchoneta', 'Respirar'] },
  { p: 'Árbitro', c: 'Deportes', x: ['Silbato', 'Tarjeta', 'Falta', 'Juez', 'Partido'] },
  // ── Objetos ──
  { p: 'Paraguas', c: 'Objetos', x: ['Lluvia', 'Abrir', 'Mojarse', 'Mango', 'Cubrirse'] },
  { p: 'Espejo', c: 'Objetos', x: ['Reflejo', 'Vidrio', 'Mirarse', 'Baño', 'Imagen'] },
  { p: 'Almohada', c: 'Objetos', x: ['Dormir', 'Cama', 'Cabeza', 'Suave', 'Plumas'] },
  { p: 'Tijera', c: 'Objetos', x: ['Cortar', 'Papel', 'Filo', 'Dos', 'Peluquería'] },
  { p: 'Heladera', c: 'Objetos', x: ['Frío', 'Cocina', 'Comida', 'Puerta', 'Congelador'] },
  { p: 'Celular', c: 'Objetos', x: ['Llamar', 'Pantalla', 'Apps', 'Batería', 'Mensaje'] },
  { p: 'Llave', c: 'Objetos', x: ['Puerta', 'Abrir', 'Cerradura', 'Candado', 'Auto'] },
  { p: 'Reloj', c: 'Objetos', x: ['Hora', 'Muñeca', 'Agujas', 'Tiempo', 'Despertador'] },
  { p: 'Escoba', c: 'Objetos', x: ['Barrer', 'Limpiar', 'Palo', 'Piso', 'Bruja'] },
  { p: 'Anteojos', c: 'Objetos', x: ['Ver', 'Ojos', 'Marco', 'Lentes', 'Sol'] },
  { p: 'Cepillo de dientes', c: 'Objetos', x: ['Pasta', 'Boca', 'Lavar', 'Baño', 'Higiene'] },
  // ── Lugares ──
  { p: 'Playa', c: 'Lugares', x: ['Arena', 'Mar', 'Sol', 'Sombrilla', 'Verano'] },
  { p: 'Hospital', c: 'Lugares', x: ['Médico', 'Enfermo', 'Camilla', 'Ambulancia', 'Cirugía'] },
  { p: 'Escuela', c: 'Lugares', x: ['Maestra', 'Alumnos', 'Pizarrón', 'Recreo', 'Aula'] },
  { p: 'Aeropuerto', c: 'Lugares', x: ['Avión', 'Valija', 'Vuelo', 'Pasaporte', 'Despegar'] },
  { p: 'Supermercado', c: 'Lugares', x: ['Comprar', 'Carrito', 'Góndola', 'Caja', 'Precios'] },
  { p: 'Cine', c: 'Lugares', x: ['Película', 'Pantalla', 'Butaca', 'Entrada', 'Pochoclo'] },
  { p: 'Museo', c: 'Lugares', x: ['Arte', 'Cuadros', 'Historia', 'Exhibición', 'Antiguo'] },
  { p: 'Selva', c: 'Lugares', x: ['Árboles', 'Animales', 'Húmedo', 'Tarzán', 'Verde'] },
  { p: 'Desierto', c: 'Lugares', x: ['Arena', 'Calor', 'Camello', 'Cactus', 'Seco'] },
  { p: 'Luna', c: 'Lugares', x: ['Espacio', 'Astronauta', 'Noche', 'Cráter', 'Llena'] },
  { p: 'Gimnasio', c: 'Lugares', x: ['Pesas', 'Ejercicio', 'Músculos', 'Entrenar', 'Máquinas'] },
  // ── Música y famosos ──
  { p: 'Guitarra', c: 'Música y famosos', x: ['Cuerdas', 'Tocar', 'Rock', 'Acordes', 'Instrumento'] },
  { p: 'Batería', c: 'Música y famosos', x: ['Palillos', 'Ritmo', 'Tambor', 'Platillos', 'Golpear'] },
  { p: 'Micrófono', c: 'Música y famosos', x: ['Cantar', 'Voz', 'Escenario', 'Karaoke', 'Hablar'] },
  { p: 'Karaoke', c: 'Música y famosos', x: ['Cantar', 'Letra', 'Pantalla', 'Micrófono', 'Bar'] },
  { p: 'Ópera', c: 'Música y famosos', x: ['Cantar', 'Teatro', 'Soprano', 'Clásica', 'Italiano'] },
  { p: 'DJ', c: 'Música y famosos', x: ['Música', 'Mezclar', 'Fiesta', 'Bandeja', 'Electrónica'] },
  { p: 'Tango', c: 'Música y famosos', x: ['Baile', 'Buenos Aires', 'Gardel', 'Pareja', 'Bandoneón'] },
  { p: 'Coro', c: 'Música y famosos', x: ['Cantar', 'Grupo', 'Voces', 'Iglesia', 'Director'] },
  { p: 'Violín', c: 'Música y famosos', x: ['Cuerdas', 'Arco', 'Clásica', 'Orquesta', 'Hombro'] },
  { p: 'Rockstar', c: 'Música y famosos', x: ['Escenario', 'Guitarra', 'Fama', 'Gira', 'Fans'] },
  { p: 'Cumbia', c: 'Música y famosos', x: ['Baile', 'Fiesta', 'Ritmo', 'Música', 'Tropical'] },
  // ── Acciones ──
  { p: 'Estornudar', c: 'Acciones', x: ['Nariz', 'Achís', 'Resfrío', 'Pañuelo', 'Salud'] },
  { p: 'Bostezar', c: 'Acciones', x: ['Sueño', 'Boca', 'Cansado', 'Aburrido', 'Abrir'] },
  { p: 'Aplaudir', c: 'Acciones', x: ['Manos', 'Bravo', 'Teatro', 'Felicitar', 'Ruido'] },
  { p: 'Cocinar', c: 'Acciones', x: ['Comida', 'Olla', 'Chef', 'Receta', 'Fuego'] },
  { p: 'Bailar', c: 'Acciones', x: ['Música', 'Mover', 'Fiesta', 'Pareja', 'Ritmo'] },
  { p: 'Dormir', c: 'Acciones', x: ['Cama', 'Noche', 'Soñar', 'Roncar', 'Descansar'] },
  { p: 'Manejar', c: 'Acciones', x: ['Auto', 'Volante', 'Ruta', 'Licencia', 'Conducir'] },
  { p: 'Pescar', c: 'Acciones', x: ['Caña', 'Río', 'Anzuelo', 'Pez', 'Paciencia'] },
  { p: 'Pintar', c: 'Acciones', x: ['Pincel', 'Colores', 'Cuadro', 'Pared', 'Artista'] },
  { p: 'Silbar', c: 'Acciones', x: ['Boca', 'Sonido', 'Melodía', 'Labios', 'Aire'] },
  { p: 'Abrazar', c: 'Acciones', x: ['Brazos', 'Cariño', 'Apretar', 'Saludo', 'Amor'] },
];
