// Mazo de palabras — Decilo sin decirlo
// p: palabra, c: categoría, x: palabras prohibidas (solo para rondas de Taboo)
export interface Palabra {
  p: string;
  c: string;
  x: string[];
}

export const CATEGORIAS = [
  'Argentina', 'Animales', 'Comida', 'Cine y series', 'Películas', 'Actores y famosos', 'Personajes',
  'Videojuegos', 'Deportes', 'Objetos', 'Lugares', 'Música y famosos', 'Acciones',
];

export const PALABRAS: Palabra[] = [
  // ── Animales ──
  { p: 'Elefante', c: 'Animales', x: ['Trompa', 'Grande', 'Gris', 'Orejas', 'África'] },
  { p: 'Pingüino', c: 'Animales', x: ['Frío', 'Hielo', 'Ave', 'Antártida', 'Blanco y negro'] },
  { p: 'Tiburón', c: 'Animales', x: ['Mar', 'Dientes', 'Aleta', 'Peligroso', 'Película'] },
  { p: 'Jirafa', c: 'Animales', x: ['Cuello', 'Alta', 'Manchas', 'África', 'Hojas'] },
  { p: 'Perro', c: 'Animales', x: ['Ladrar', 'Mascota', 'Hueso', 'Gato', 'Correa'] },
  { p: 'Gato', c: 'Animales', x: ['Maullar', 'Ratón', 'Mascota', 'Bigotes', 'Siete vidas'] },
  { p: 'Caballo', c: 'Animales', x: ['Montar', 'Galopar', 'Crin', 'Granja', 'Jinete'] },
  { p: 'Abeja', c: 'Animales', x: ['Miel', 'Picar', 'Amarillo', 'Volar', 'Panal'] },
  { p: 'Cocodrilo', c: 'Animales', x: ['Río', 'Dientes', 'Verde', 'Reptil', 'Lagarto'] },
  { p: 'Mono', c: 'Animales', x: ['Banana', 'Selva', 'Trepar', 'Cola', 'Simio'] },
  { p: 'Búho', c: 'Animales', x: ['Noche', 'Sabio', 'Plumas', 'Girar', 'Ave'] },
  { p: 'Tortuga', c: 'Animales', x: ['Caparazón', 'Lenta', 'Ninja', 'Mar', 'Vieja'] },
  { p: 'León', c: 'Animales', x: ['Rey', 'Selva', 'Melena', 'Rugir', 'Felino'] },
  { p: 'Canguro', c: 'Animales', x: ['Australia', 'Saltar', 'Bolsa', 'Cría', 'Boxeo'] },
  { p: 'Murciélago', c: 'Animales', x: ['Noche', 'Cueva', 'Volar', 'Batman', 'Colgado'] },
  { p: 'Pulpo', c: 'Animales', x: ['Ocho', 'Tentáculos', 'Mar', 'Tinta', 'Ventosas'] },
  { p: 'Loro', c: 'Animales', x: ['Repetir', 'Hablar', 'Verde', 'Pirata', 'Ave'] },
  { p: 'Hormiga', c: 'Animales', x: ['Chiquita', 'Trabajadora', 'Hormiguero', 'Fila', 'Picnic'] },
  { p: 'Vaca', c: 'Animales', x: ['Leche', 'Mugir', 'Campo', 'Manchas', 'Toro'] },
  { p: 'Serpiente', c: 'Animales', x: ['Veneno', 'Reptil', 'Arrastrarse', 'Cascabel', 'Lengua'] },
  { p: 'Oso', c: 'Animales', x: ['Miel', 'Hibernar', 'Polar', 'Panda', 'Peluche'] },
  // ── Comida ──
  { p: 'Pizza', c: 'Comida', x: ['Queso', 'Italiana', 'Porción', 'Muzzarella', 'Horno'] },
  { p: 'Asado', c: 'Argentina', x: ['Parrilla', 'Carne', 'Fuego', 'Domingo', 'Costillas'] },
  { p: 'Empanada', c: 'Argentina', x: ['Relleno', 'Masa', 'Carne', 'Horno', 'Repulgue'] },
  { p: 'Helado', c: 'Comida', x: ['Frío', 'Cucurucho', 'Sabor', 'Verano', 'Postre'] },
  { p: 'Hamburguesa', c: 'Comida', x: ['Pan', 'Carne', 'Queso', 'Comida rápida', 'Papas fritas'] },
  { p: 'Sushi', c: 'Comida', x: ['Japonés', 'Arroz', 'Pescado', 'Palitos', 'Alga'] },
  { p: 'Chocolate', c: 'Comida', x: ['Dulce', 'Cacao', 'Marrón', 'Tableta', 'Bombón'] },
  { p: 'Café', c: 'Comida', x: ['Taza', 'Despertar', 'Negro', 'Cafeína', 'Desayuno'] },
  { p: 'Sopa', c: 'Comida', x: ['Caliente', 'Cuchara', 'Plato', 'Líquido', 'Invierno'] },
  { p: 'Taco', c: 'Comida', x: ['México', 'Tortilla', 'Picante', 'Relleno', 'Carne'] },
  { p: 'Ensalada', c: 'Comida', x: ['Lechuga', 'Verduras', 'Tomate', 'Saludable', 'Aderezo'] },
  { p: 'Milanesa', c: 'Argentina', x: ['Empanado', 'Napolitana', 'Carne', 'Frita', 'Puré'] },
  { p: 'Fideos', c: 'Comida', x: ['Pasta', 'Salsa', 'Italia', 'Tuco', 'Hervir'] },
  { p: 'Dulce de leche', c: 'Argentina', x: ['Argentina', 'Marrón', 'Untar', 'Postre', 'Leche'] },
  { p: 'Mate', c: 'Argentina', x: ['Yerba', 'Bombilla', 'Termo', 'Amargo', 'Argentina'] },
  { p: 'Torta', c: 'Comida', x: ['Cumpleaños', 'Velitas', 'Dulce', 'Porción', 'Bizcochuelo'] },
  { p: 'Pancho', c: 'Comida', x: ['Salchicha', 'Pan', 'Mostaza', 'Rápido', 'Cancha'] },
  { p: 'Huevo', c: 'Comida', x: ['Gallina', 'Frito', 'Yema', 'Cáscara', 'Revuelto'] },
  { p: 'Queso', c: 'Comida', x: ['Rallado', 'Vaca', 'Ratón', 'Agujeros', 'Lácteo'] },
  { p: 'Banana', c: 'Comida', x: ['Amarilla', 'Mono', 'Cáscara', 'Fruta', 'Resbalar'] },
  { p: 'Papas fritas', c: 'Comida', x: ['Aceite', 'Ketchup', 'Crujientes', 'Bastones', 'McDonalds'] },
  // ── Cine y series ──
  { p: 'Superhéroe', c: 'Cine y series', x: ['Capa', 'Poderes', 'Volar', 'Salvar', 'Villano'] },
  { p: 'Zombi', c: 'Cine y series', x: ['Muerto', 'Cerebro', 'Caminar', 'Virus', 'Terror'] },
  { p: 'Titanic', c: 'Cine y series', x: ['Barco', 'Hundirse', 'Iceberg', 'Leonardo', 'Amor'] },
  { p: 'Mago', c: 'Cine y series', x: ['Varita', 'Hechizo', 'Sombrero', 'Conejo', 'Magia'] },
  { p: 'Vampiro', c: 'Cine y series', x: ['Sangre', 'Colmillos', 'Noche', 'Ajo', 'Drácula'] },
  { p: 'Pochoclo', c: 'Cine y series', x: ['Maíz', 'Cine', 'Balde', 'Explotar', 'Película'] },
  { p: 'Director de cine', c: 'Cine y series', x: ['Película', 'Cámara', 'Acción', 'Rodar', 'Corte'] },
  { p: 'Premio Oscar', c: 'Cine y series', x: ['Estatua', 'Hollywood', 'Actor', 'Alfombra roja', 'Ganador'] },
  { p: 'Dinosaurio', c: 'Cine y series', x: ['Extinto', 'Fósil', 'Gigante', 'Prehistórico', 'Reptil'] },
  { p: 'Pirata', c: 'Cine y series', x: ['Barco', 'Parche', 'Tesoro', 'Loro', 'Espada'] },
  { p: 'Bruja', c: 'Cine y series', x: ['Escoba', 'Hechizo', 'Caldero', 'Sombrero', 'Magia'] },
  { p: 'Netflix', c: 'Cine y series', x: ['Series', 'Streaming', 'Maratón', 'Rojo', 'Suscripción'] },
  { p: 'Telenovela', c: 'Cine y series', x: ['Amor', 'Drama', 'Capítulos', 'Llorar', 'Villana'] },
  { p: 'Documental', c: 'Cine y series', x: ['Real', 'Naturaleza', 'Narrador', 'Historia', 'Educativo'] },
  { p: 'Dibujos animados', c: 'Cine y series', x: ['Niños', 'Televisión', 'Colores', 'Personajes', 'Animación'] },
  { p: 'Alfombra roja', c: 'Cine y series', x: ['Famosos', 'Vestidos', 'Fotógrafos', 'Premios', 'Caminar'] },
  { p: 'Extraterrestre', c: 'Cine y series', x: ['OVNI', 'Espacio', 'Verde', 'Platillo', 'Alien'] },
  { p: 'Robot', c: 'Cine y series', x: ['Máquina', 'Metal', 'Futuro', 'Inteligencia artificial', 'Programar'] },
  { p: 'Fantasma', c: 'Cine y series', x: ['Sábana', 'Casa embrujada', 'Boo', 'Aparecer', 'Miedo'] },
  { p: 'Payaso', c: 'Cine y series', x: ['Circo', 'Nariz roja', 'Risa', 'Maquillaje', 'Globos'] },
  { p: 'Cámara oculta', c: 'Cine y series', x: ['Broma', 'Filmar', 'Sorpresa', 'Reír', 'Televisión'] },
  { p: 'Los Simpson', c: 'Cine y series', x: ['Amarillos', 'Springfield', 'Homero', 'Bart', 'Familia'] },
  { p: 'Friends', c: 'Cine y series', x: ['Café', 'Nueva York', 'Ross', 'Sofá', 'Seis amigos'] },
  { p: 'Stranger Things', c: 'Cine y series', x: ['Once', 'Demogorgon', 'Años 80', 'Bicicletas', 'Upside Down'] },
  { p: 'El Juego del Calamar', c: 'Cine y series', x: ['Corea', 'Juegos', 'Muñeca', 'Deudas', 'Máscaras'] },
  { p: 'La Casa de Papel', c: 'Cine y series', x: ['Atraco', 'Dalí', 'Bella Ciao', 'Rojo', 'Profesor'] },
  { p: 'Game of Thrones', c: 'Cine y series', x: ['Dragones', 'Tronos', 'Invierno', 'Jon Snow', 'Khaleesi'] },
  { p: 'Breaking Bad', c: 'Cine y series', x: ['Química', 'Heisenberg', 'Metanfetamina', 'Profesor', 'Desierto'] },
  { p: 'Merlina', c: 'Cine y series', x: ['Addams', 'Trenzas', 'Baile', 'Dedos', 'Gótica'] },
  { p: 'Casados con Hijos', c: 'Argentina', x: ['Pepe', 'Moni', 'Argento', 'Zapatero', 'Familia'] },
  { p: 'El Marginal', c: 'Argentina', x: ['Cárcel', 'Borges', 'Presos', 'Argentina', 'Hermanos'] },
  { p: 'Doctor House', c: 'Cine y series', x: ['Médico', 'Bastón', 'Lupus', 'Sarcasmo', 'Diagnóstico'] },
  { p: 'Greys Anatomy', c: 'Cine y series', x: ['Hospital', 'Médicos', 'Meredith', 'Cirugías', 'Romance'] },
  { p: 'Dragon Ball', c: 'Cine y series', x: ['Goku', 'Esferas', 'Anime', 'Saiyajin', 'Kamehameha'] },
  { p: 'Peaky Blinders', c: 'Cine y series', x: ['Boinas', 'Gángsters', 'Inglaterra', 'Tommy', 'Navajas'] },
  // ── Películas ──
  { p: 'El Rey León', c: 'Películas', x: ['Simba', 'África', 'Hakuna Matata', 'Disney', 'Selva'] },
  { p: 'Toy Story', c: 'Películas', x: ['Juguetes', 'Woody', 'Buzz', 'Pixar', 'Vaquero'] },
  { p: 'Harry Potter', c: 'Películas', x: ['Mago', 'Varita', 'Hogwarts', 'Anteojos', 'Cicatriz'] },
  { p: 'Jurassic Park', c: 'Películas', x: ['Dinosaurios', 'Parque', 'Isla', 'ADN', 'Tiranosaurio'] },
  { p: 'Shrek', c: 'Películas', x: ['Ogro', 'Verde', 'Burro', 'Fiona', 'Pantano'] },
  { p: 'Frozen', c: 'Películas', x: ['Hielo', 'Elsa', 'Princesa', 'Muñeco de nieve', 'Libre soy'] },
  { p: 'Volver al Futuro', c: 'Películas', x: ['DeLorean', 'Viaje en el tiempo', 'Marty', 'Doc', 'Auto'] },
  { p: 'El Padrino', c: 'Películas', x: ['Mafia', 'Italia', 'Don', 'Oferta', 'Corleone'] },
  { p: 'Matrix', c: 'Películas', x: ['Pastilla', 'Neo', 'Realidad virtual', 'Agente', 'Lentes negros'] },
  { p: 'Piratas del Caribe', c: 'Películas', x: ['Jack Sparrow', 'Barco', 'Tesoro', 'Mar', 'Ron'] },
  { p: 'Rápido y Furioso', c: 'Películas', x: ['Autos', 'Carreras', 'Familia', 'Toretto', 'Velocidad'] },
  { p: 'Buscando a Nemo', c: 'Películas', x: ['Pez', 'Payaso', 'Océano', 'Dory', 'Perdido'] },
  { p: 'Los Increíbles', c: 'Películas', x: ['Superhéroes', 'Familia', 'Pixar', 'Traje', 'Poderes'] },
  { p: 'Mi Villano Favorito', c: 'Películas', x: ['Minions', 'Gru', 'Amarillo', 'Villano', 'Nenas'] },
  { p: 'Avatar', c: 'Películas', x: ['Azul', 'Pandora', 'Planeta', 'Alienígenas', 'James Cameron'] },
  { p: 'Avengers', c: 'Películas', x: ['Marvel', 'Superhéroes', 'Thanos', 'Iron Man', 'Equipo'] },
  { p: 'El Señor de los Anillos', c: 'Películas', x: ['Frodo', 'Anillo', 'Gandalf', 'Hobbit', 'Mordor'] },
  { p: 'Star Wars', c: 'Películas', x: ['Espada láser', 'Darth Vader', 'Galaxia', 'Fuerza', 'Yoda'] },
  { p: 'Terminator', c: 'Películas', x: ['Robot', 'Futuro', 'Schwarzenegger', 'Volveré', 'Máquina'] },
  { p: 'Rocky', c: 'Películas', x: ['Boxeo', 'Stallone', 'Escaleras', 'Filadelfia', 'Campeón'] },
  { p: 'E.T.', c: 'Películas', x: ['Extraterrestre', 'Bicicleta', 'Teléfono', 'Casa', 'Dedo'] },
  { p: 'La Era de Hielo', c: 'Películas', x: ['Ardilla', 'Bellota', 'Mamut', 'Perezoso', 'Glaciar'] },
  { p: 'Madagascar', c: 'Películas', x: ['Zoológico', 'León', 'Pingüinos', 'Isla', 'África'] },
  { p: 'Kung Fu Panda', c: 'Películas', x: ['Oso', 'Artes marciales', 'China', 'Po', 'Fideos'] },
  { p: 'Ratatouille', c: 'Películas', x: ['Rata', 'Cocinar', 'París', 'Chef', 'Restaurante'] },
  { p: 'Coco', c: 'Películas', x: ['México', 'Día de los muertos', 'Guitarra', 'Familia', 'Recuérdame'] },
  { p: 'Up', c: 'Películas', x: ['Globos', 'Casa', 'Viejito', 'Volar', 'Aventura'] },
  { p: 'Monsters Inc', c: 'Películas', x: ['Sustos', 'Puertas', 'Sully', 'Mike', 'Gritos'] },
  { p: 'Cars', c: 'Películas', x: ['Autos', 'Carreras', 'Rayo McQueen', 'Pixar', 'Rueda'] },
  { p: 'Grease', c: 'Películas', x: ['Baile', 'Musical', 'John Travolta', 'Secundaria', 'Cuero'] },
  { p: 'Duro de Matar', c: 'Películas', x: ['Bruce Willis', 'Navidad', 'Edificio', 'Policía', 'Explosión'] },
  { p: 'Misión Imposible', c: 'Películas', x: ['Tom Cruise', 'Espía', 'Máscara', 'Colgado', 'Bomba'] },
  { p: 'Mary Poppins', c: 'Películas', x: ['Niñera', 'Paraguas', 'Volar', 'Magia', 'Supercalifragilístico'] },
  { p: 'El Exorcista', c: 'Películas', x: ['Terror', 'Posesión', 'Cura', 'Demonio', 'Cabeza'] },
  { p: 'Karate Kid', c: 'Películas', x: ['Patada', 'Maestro', 'Miyagi', 'Encerar', 'Grulla'] },
  { p: 'Nueve Reinas', c: 'Argentina', x: ['Estafa', 'Argentina', 'Darín', 'Estampillas', 'Timo'] },
  { p: 'Relatos Salvajes', c: 'Argentina', x: ['Argentina', 'Episodios', 'Venganza', 'Avión', 'Casamiento'] },
  { p: 'Metegol', c: 'Argentina', x: ['Argentina', 'Jugadores', 'Fútbol', 'Muñecos', 'Animada'] },
  { p: 'Esperando la Carroza', c: 'Argentina', x: ['Mamá Cora', 'Argentina', 'Familia', 'Velorio', 'Tres empanadas'] },
  { p: 'Gladiador', c: 'Películas', x: ['Roma', 'Coliseo', 'Espada', 'Máximo', 'Emperador'] },
  { p: 'Forrest Gump', c: 'Películas', x: ['Correr', 'Chocolates', 'Pluma', 'Tom Hanks', 'Banco'] },
  { p: 'Intensamente', c: 'Películas', x: ['Emociones', 'Alegría', 'Tristeza', 'Cabeza', 'Pixar'] },
  { p: 'Wall-E', c: 'Películas', x: ['Robot', 'Basura', 'Espacio', 'Planta', 'Solo'] },
  { p: 'Náufrago', c: 'Películas', x: ['Isla', 'Wilson', 'Pelota', 'Tom Hanks', 'Solo'] },
  { p: 'Jumanji', c: 'Películas', x: ['Juego', 'Selva', 'Dados', 'Animales', 'Robin Williams'] },
  { p: 'Los Cazafantasmas', c: 'Películas', x: ['Fantasmas', 'Atrapar', 'Mochila láser', 'Nueva York', 'Logo'] },
  { p: 'Mi Pobre Angelito', c: 'Películas', x: ['Navidad', 'Solo en casa', 'Ladrones', 'Trampas', 'Kevin'] },
  { p: 'It', c: 'Películas', x: ['Payaso', 'Globo', 'Terror', 'Alcantarilla', 'Pennywise'] },
  { p: 'Crepúsculo', c: 'Películas', x: ['Vampiros', 'Amor', 'Hombre lobo', 'Bella', 'Brillar'] },
  { p: 'Los Juegos del Hambre', c: 'Películas', x: ['Arco', 'Katniss', 'Distritos', 'Arena', 'Sinsajo'] },
  { p: 'Barbie', c: 'Películas', x: ['Rosa', 'Muñeca', 'Ken', 'Margot Robbie', 'Plástico'] },
  { p: 'El Lobo de Wall Street', c: 'Películas', x: ['Dinero', 'Bolsa', 'DiCaprio', 'Fiestas', 'Estafa'] },
  { p: 'Matilda', c: 'Películas', x: ['Nena', 'Poderes', 'Libros', 'Tronchatoro', 'Danny DeVito'] },
  { p: 'Charlie y la Fábrica de Chocolate', c: 'Películas', x: ['Wonka', 'Golosinas', 'Ticket dorado', 'Umpa Lumpa', 'Niños'] },
  { p: 'El Mago de Oz', c: 'Películas', x: ['Dorothy', 'Camino amarillo', 'Espantapájaros', 'Bruja', 'Toto'] },
  { p: 'Moana', c: 'Películas', x: ['Mar', 'Isla', 'Maui', 'Océano', 'Polinesia'] },
  { p: 'Encanto', c: 'Películas', x: ['Colombia', 'Mirabel', 'Bruno', 'Casa', 'Dones'] },
  { p: 'Psicosis', c: 'Películas', x: ['Ducha', 'Cuchillo', 'Hitchcock', 'Motel', 'Terror'] },
  { p: 'El Resplandor', c: 'Películas', x: ['Hotel', 'Hacha', 'Aquí está Johnny', 'Gemelas', 'Jack Nicholson'] },
  { p: 'Actividad Paranormal', c: 'Películas', x: ['Cámaras', 'Fantasma', 'Casa', 'Noche', 'Terror'] },
  { p: 'El Conjuro', c: 'Películas', x: ['Terror', 'Muñeca', 'Casa embrujada', 'Demonio', 'Annabelle'] },
  { p: 'Chicas Pesadas', c: 'Películas', x: ['Rosa', 'Miércoles', 'Regina', 'Secundaria', 'Populares'] },
  { p: 'Legalmente Rubia', c: 'Películas', x: ['Abogada', 'Rosa', 'Harvard', 'Perrito', 'Rubia'] },
  { p: 'Diario de una Pasión', c: 'Películas', x: ['Amor', 'Cartas', 'Lluvia', 'Beso', 'Anciano'] },
  { p: 'Kill Bill', c: 'Películas', x: ['Espada', 'Venganza', 'Amarillo', 'Novia', 'Tarantino'] },
  { p: 'Pulp Fiction', c: 'Películas', x: ['Tarantino', 'Baile', 'Maletín', 'Hamburguesa', 'Peluca'] },
  { p: 'El Silencio de los Inocentes', c: 'Películas', x: ['Hannibal', 'Caníbal', 'FBI', 'Máscara', 'Clarice'] },
  { p: 'Corazón Valiente', c: 'Películas', x: ['Escocia', 'Libertad', 'Mel Gibson', 'Guerra', 'Pintura azul'] },
  { p: '300', c: 'Películas', x: ['Esparta', 'Guerreros', 'Abdominales', 'Escudos', 'Persas'] },
  { p: 'Transformers', c: 'Películas', x: ['Robots', 'Autos', 'Optimus', 'Transformar', 'Explosiones'] },
  { p: 'Space Jam', c: 'Películas', x: ['Michael Jordan', 'Looney Tunes', 'Básquet', 'Dibujos', 'Aliens'] },
  { p: 'El Diablo Viste a la Moda', c: 'Películas', x: ['Moda', 'Jefa', 'Revista', 'Asistente', 'Meryl Streep'] },
  { p: 'Ted', c: 'Películas', x: ['Oso', 'Peluche', 'Grosero', 'Amigo', 'Hablar'] },
  { p: '¿Qué Pasó Ayer?', c: 'Películas', x: ['Resaca', 'Las Vegas', 'Despedida', 'Tigre', 'Bebé'] },
  { p: 'Bohemian Rhapsody', c: 'Películas', x: ['Queen', 'Freddie Mercury', 'Banda', 'Bigote', 'Concierto'] },
  { p: 'Interestelar', c: 'Películas', x: ['Espacio', 'Agujero negro', 'Tiempo', 'Maíz', 'Nolan'] },
  // ── Actores y famosos ──
  { p: 'Leonardo DiCaprio', c: 'Actores y famosos', x: ['Titanic', 'Oscar', 'Lobo de Wall Street', 'Actor', 'Barco'] },
  { p: 'Brad Pitt', c: 'Actores y famosos', x: ['Angelina', 'Rubio', 'Hollywood', 'Actor', 'Club de la Pelea'] },
  { p: 'Jim Carrey', c: 'Actores y famosos', x: ['La Máscara', 'Comedia', 'Ace Ventura', 'Caras', 'Grinch'] },
  { p: 'La Roca', c: 'Actores y famosos', x: ['Músculos', 'Lucha libre', 'Pelado', 'Actor', 'Piedra'] },
  { p: 'Angelina Jolie', c: 'Actores y famosos', x: ['Brad', 'Labios', 'Tomb Raider', 'Actriz', 'Maléfica'] },
  { p: 'Tom Cruise', c: 'Actores y famosos', x: ['Misión Imposible', 'Top Gun', 'Bajo', 'Actor', 'Acción'] },
  { p: 'Will Smith', c: 'Actores y famosos', x: ['Príncipe del rap', 'Cachetada', 'Men in Black', 'Actor', 'Oscar'] },
  { p: 'Keanu Reeves', c: 'Actores y famosos', x: ['Matrix', 'John Wick', 'Neo', 'Actor', 'Motos'] },
  { p: 'Johnny Depp', c: 'Actores y famosos', x: ['Pirata', 'Jack Sparrow', 'Tijeras', 'Actor', 'Sombrero'] },
  { p: 'Ricardo Darín', c: 'Actores y famosos', x: ['Argentino', 'El secreto de sus ojos', 'Nueve reinas', 'Actor', 'Relatos salvajes'] },
  { p: 'Guillermo Francella', c: 'Actores y famosos', x: ['Casados con hijos', 'Bigote', 'Comedia', 'Argentino', 'El Clan'] },
  { p: 'Lionel Messi', c: 'Argentina', x: ['Fútbol', 'Argentina', 'Diez', 'Barcelona', 'Copa del mundo'] },
  { p: 'Diego Maradona', c: 'Argentina', x: ['Diez', 'Mano de Dios', 'Fútbol', 'Barrilete cósmico', 'Nápoles'] },
  { p: 'Cristiano Ronaldo', c: 'Actores y famosos', x: ['Portugal', 'Fútbol', 'Siuuu', 'Real Madrid', 'CR7'] },
  { p: 'Michael Jackson', c: 'Actores y famosos', x: ['Rey del pop', 'Moonwalk', 'Thriller', 'Guante', 'Cantante'] },
  { p: 'Shakira', c: 'Actores y famosos', x: ['Colombia', 'Caderas', 'Cantante', 'Piqué', 'Waka Waka'] },
  { p: 'Madonna', c: 'Actores y famosos', x: ['Reina del pop', 'Cantante', 'Rubia', 'Like a Virgin', 'Evita'] },
  { p: 'Freddie Mercury', c: 'Actores y famosos', x: ['Queen', 'Bigote', 'Bohemian Rhapsody', 'Cantante', 'We Will Rock You'] },
  { p: 'Elvis Presley', c: 'Actores y famosos', x: ['Rey del rock', 'Jopo', 'Cantante', 'Caderas', 'Memphis'] },
  { p: 'Charly García', c: 'Argentina', x: ['Bigote bicolor', 'Rock nacional', 'Piano', 'Cantante', 'Say No More'] },
  { p: 'Bizarrap', c: 'Actores y famosos', x: ['Sesiones', 'Gorra', 'Lentes', 'Productor', 'Música'] },
  { p: 'Susana Giménez', c: 'Argentina', x: ['Diva', 'Teléfono', 'Rubia', 'Televisión', 'Shock'] },
  { p: 'Marcelo Tinelli', c: 'Argentina', x: ['ShowMatch', 'Conductor', 'Bailando', 'Televisión', 'Cámara'] },
  { p: 'Mirtha Legrand', c: 'Argentina', x: ['Almuerzos', 'Televisión', 'Diva', 'Mesa', 'Chiquita'] },
  { p: 'Moria Casán', c: 'Argentina', x: ['Diva', 'Lengua', 'Vedette', 'One', 'Jurado'] },
  { p: 'Lali Espósito', c: 'Actores y famosos', x: ['Cantante', 'Casi Ángeles', 'Pop', 'Actriz', 'Disciplina'] },
  { p: 'El Dibu Martínez', c: 'Argentina', x: ['Arquero', 'Penales', 'Selección', 'Atajada', 'Baile'] },
  { p: 'Usain Bolt', c: 'Actores y famosos', x: ['Correr', 'Jamaica', 'Rayo', 'Velocista', 'Récord'] },
  { p: 'Mike Tyson', c: 'Actores y famosos', x: ['Boxeo', 'Oreja', 'Nocaut', 'Tatuaje', 'Campeón'] },
  { p: 'Michael Jordan', c: 'Actores y famosos', x: ['Básquet', 'Chicago Bulls', 'Veintitrés', 'Zapatillas', 'Volar'] },
  { p: 'Serena Williams', c: 'Actores y famosos', x: ['Tenis', 'Raqueta', 'Hermanas', 'Campeona', 'Estados Unidos'] },
  { p: 'Albert Einstein', c: 'Actores y famosos', x: ['Científico', 'Relatividad', 'Genio', 'Lengua', 'Pelo loco'] },
  { p: 'Morgan Freeman', c: 'Actores y famosos', x: ['Voz', 'Dios', 'Narrador', 'Actor', 'Pecas'] },
  { p: 'Arnold Schwarzenegger', c: 'Actores y famosos', x: ['Terminator', 'Músculos', 'Austria', 'Gobernador', 'Volveré'] },
  { p: 'Sylvester Stallone', c: 'Actores y famosos', x: ['Rocky', 'Rambo', 'Boxeo', 'Actor', 'Músculos'] },
  { p: 'Emma Watson', c: 'Actores y famosos', x: ['Hermione', 'Harry Potter', 'Actriz', 'Inglesa', 'Maga'] },
  { p: 'Julia Roberts', c: 'Actores y famosos', x: ['Mujer bonita', 'Sonrisa', 'Actriz', 'Pelirroja', 'Hollywood'] },
  { p: 'Adam Sandler', c: 'Actores y famosos', x: ['Comedia', 'Actor', 'Netflix', 'Como si fuera la primera vez', 'Gracioso'] },
  { p: 'Danny DeVito', c: 'Actores y famosos', x: ['Bajito', 'Actor', 'Matilda', 'Pelado', 'Comedia'] },
  { p: 'Antonio Banderas', c: 'Actores y famosos', x: ['Español', 'Zorro', 'Gato con botas', 'Actor', 'Acento'] },
  { p: 'Jackie Chan', c: 'Actores y famosos', x: ['Artes marciales', 'China', 'Acrobacias', 'Actor', 'Golpes'] },
  { p: 'Taylor Swift', c: 'Actores y famosos', x: ['Cantante', 'Pop', 'Swifties', 'Eras Tour', 'Rubia'] },
  { p: 'Bad Bunny', c: 'Actores y famosos', x: ['Reggaetón', 'Puerto Rico', 'Conejo', 'Trap', 'Lentes'] },
  { p: 'Duki', c: 'Actores y famosos', x: ['Trap', 'Argentino', 'Freestyle', 'Rapero', 'Modo diablo'] },
  { p: 'María Becerra', c: 'Actores y famosos', x: ['Cantante', 'Argentina', 'Nena de Argentina', 'Pop', 'Quilmes'] },
  { p: 'Tini', c: 'Actores y famosos', x: ['Violetta', 'Cantante', 'Argentina', 'Pop', 'Triple T'] },
  { p: 'Novak Djokovic', c: 'Actores y famosos', x: ['Tenis', 'Serbia', 'Número uno', 'Grand Slam', 'Raqueta'] },
  { p: 'Kylian Mbappé', c: 'Actores y famosos', x: ['Francia', 'Fútbol', 'Velocidad', 'Real Madrid', 'Campeón del mundo'] },
  { p: 'Beyoncé', c: 'Actores y famosos', x: ['Cantante', 'Diva', 'Single Ladies', 'Queen B', 'Estados Unidos'] },
  { p: 'Marley', c: 'Actores y famosos', x: ['Conductor', 'Viajes', 'Por el mundo', 'Mirko', 'Televisión'] },
  { p: 'Guido Kaczka', c: 'Actores y famosos', x: ['Conductor', 'Los 8 escalones', 'Televisión', 'Preguntas', 'Premios'] },
  { p: 'Rihanna', c: 'Actores y famosos', x: ['Cantante', 'Umbrella', 'Barbados', 'Fenty', 'Diamonds'] },
  { p: 'Ariana Grande', c: 'Actores y famosos', x: ['Cantante', 'Colita', 'Pop', 'Wicked', 'Thank U Next'] },
  { p: 'Dua Lipa', c: 'Actores y famosos', x: ['Cantante', 'Inglesa', 'Pop', 'Levitating', 'Morocha'] },
  { p: 'Bruno Mars', c: 'Actores y famosos', x: ['Cantante', 'Funk', 'Uptown', 'Hawaii', 'Sombrero'] },
  { p: 'Eminem', c: 'Actores y famosos', x: ['Rapero', 'Rubio', 'Detroit', '8 Millas', 'Slim Shady'] },
  { p: 'Snoop Dogg', c: 'Actores y famosos', x: ['Rapero', 'Trenzas', 'Perro', 'Humo', 'Flaco'] },
  { p: 'Karol G', c: 'Actores y famosos', x: ['Colombia', 'Bichota', 'Reggaetón', 'Pelo rojo', 'Cantante'] },
  { p: 'Rosalía', c: 'Actores y famosos', x: ['España', 'Motomami', 'Flamenco', 'Cantante', 'Tra tra'] },
  { p: 'L-Gante', c: 'Actores y famosos', x: ['Cumbia 420', 'Argentino', 'Keloke', 'Tatuajes', 'General Rodríguez'] },
  { p: 'Emilia Mernes', c: 'Actores y famosos', x: ['Cantante', 'Argentina', 'Pop', 'Duki', 'No se ve'] },
  { p: 'Nicki Nicole', c: 'Actores y famosos', x: ['Argentina', 'Rosario', 'Cantante', 'Trap', 'Wapo Traketero'] },
  { p: 'Paulo Londra', c: 'Actores y famosos', x: ['Córdoba', 'Rapero', 'Adiós', 'Freestyle', 'Alto'] },
  { p: 'Luis Miguel', c: 'Actores y famosos', x: ['México', 'Sol', 'Cantante', 'Serie', 'Bolero'] },
  { p: 'Ricky Martin', c: 'Actores y famosos', x: ['Puerto Rico', 'Livin la Vida Loca', 'Cantante', 'Menudo', 'María'] },
  { p: 'Franco Colapinto', c: 'Argentina', x: ['Fórmula 1', 'Argentino', 'Piloto', 'Williams', 'Pilarense'] },
  { p: 'Del Potro', c: 'Argentina', x: ['Tenis', 'Tandil', 'US Open', 'Torre', 'Delpo'] },
  { p: 'Manu Ginóbili', c: 'Argentina', x: ['Básquet', 'Bahía Blanca', 'Spurs', 'Zurdo', 'Generación dorada'] },
  { p: 'Carlos Tevez', c: 'Argentina', x: ['Apache', 'Boca', 'Fuerte', 'Delantero', 'Cicatriz'] },
  { p: 'Riquelme', c: 'Argentina', x: ['Boca', 'Diez', 'Enganche', 'Topo Gigio', 'Pausa'] },
  { p: 'Neymar', c: 'Actores y famosos', x: ['Brasil', 'Fútbol', 'Lujos', 'PSG', 'Caídas'] },
  { p: 'Kun Agüero', c: 'Argentina', x: ['Streamer', 'Manchester City', 'Delantero', 'Independiente', 'Krü'] },
  { p: 'Ibai', c: 'Actores y famosos', x: ['Streamer', 'España', 'Twitch', 'Velada', 'Grande'] },
  { p: 'Coscu', c: 'Actores y famosos', x: ['Streamer', 'Argentino', 'Twitch', 'Coscu Army', 'Gamer'] },
  { p: 'MrBeast', c: 'Actores y famosos', x: ['YouTube', 'Millones', 'Retos', 'Regalar', 'Chocolate'] },
  { p: 'Wanda Nara', c: 'Actores y famosos', x: ['Mediática', 'Icardi', 'Rubia', 'Empresaria', 'MasterChef'] },
  // ── Personajes ──
  { p: 'Batman', c: 'Personajes', x: ['Murciélago', 'Ciudad Gótica', 'Robin', 'Guasón', 'Capa'] },
  { p: 'Superman', c: 'Personajes', x: ['Capa', 'Volar', 'Kriptonita', 'Clark Kent', 'Acero'] },
  { p: 'Homero Simpson', c: 'Personajes', x: ['Amarillo', 'Donas', 'Springfield', 'Bart', 'Cerveza'] },
  { p: 'Bob Esponja', c: 'Personajes', x: ['Amarillo', 'Mar', 'Patricio', 'Cangreburger', 'Piña'] },
  { p: 'Mickey Mouse', c: 'Personajes', x: ['Ratón', 'Disney', 'Orejas', 'Minnie', 'Guantes'] },
  { p: 'El Hombre Araña', c: 'Personajes', x: ['Telaraña', 'Trepar', 'Rojo', 'Peter Parker', 'Araña'] },
  { p: 'Darth Vader', c: 'Personajes', x: ['Star Wars', 'Casco', 'Padre', 'Lado oscuro', 'Respiración'] },
  { p: 'Papá Noel', c: 'Personajes', x: ['Navidad', 'Regalos', 'Rojo', 'Barba', 'Renos'] },
  { p: 'Pikachu', c: 'Personajes', x: ['Pokémon', 'Amarillo', 'Rayo', 'Ash', 'Ratón'] },
  { p: 'Mario Bros', c: 'Personajes', x: ['Plomero', 'Bigote', 'Hongo', 'Luigi', 'Princesa'] },
  { p: 'El Grinch', c: 'Personajes', x: ['Navidad', 'Verde', 'Robar', 'Odiar', 'Regalos'] },
  { p: 'El Guasón', c: 'Personajes', x: ['Batman', 'Payaso', 'Risa', 'Villano', 'Pelo verde'] },
  { p: 'Mujer Maravilla', c: 'Personajes', x: ['Amazona', 'Lazo', 'Superheroína', 'Tiara', 'Escudo'] },
  { p: 'Hulk', c: 'Personajes', x: ['Verde', 'Enojado', 'Gigante', 'Músculos', 'Aplastar'] },
  { p: 'Iron Man', c: 'Personajes', x: ['Armadura', 'Tony Stark', 'Marvel', 'Volar', 'Millonario'] },
  { p: 'Thor', c: 'Personajes', x: ['Martillo', 'Dios', 'Trueno', 'Rubio', 'Asgard'] },
  { p: 'Capitán América', c: 'Personajes', x: ['Escudo', 'Soldado', 'Estados Unidos', 'Vengador', 'Estrella'] },
  { p: 'Goku', c: 'Personajes', x: ['Dragon Ball', 'Saiyajin', 'Kamehameha', 'Pelo', 'Esferas'] },
  { p: 'Naruto', c: 'Personajes', x: ['Ninja', 'Anime', 'Zorro', 'Naranja', 'Aldea'] },
  { p: 'Pato Donald', c: 'Personajes', x: ['Pato', 'Disney', 'Marinero', 'Enojado', 'Sin pantalones'] },
  { p: 'Winnie Pooh', c: 'Personajes', x: ['Oso', 'Miel', 'Amarillo', 'Puerquito', 'Bosque'] },
  { p: 'Pinocho', c: 'Personajes', x: ['Nariz', 'Mentira', 'Madera', 'Muñeco', 'Grillo'] },
  { p: 'Peter Pan', c: 'Personajes', x: ['Volar', 'Nunca Jamás', 'Campanita', 'Garfio', 'Niño'] },
  { p: 'Cenicienta', c: 'Personajes', x: ['Zapato', 'Princesa', 'Medianoche', 'Carroza', 'Madrastra'] },
  { p: 'Blancanieves', c: 'Personajes', x: ['Manzana', 'Enanos', 'Espejo', 'Princesa', 'Bruja'] },
  { p: 'La Sirenita', c: 'Personajes', x: ['Mar', 'Cola', 'Ariel', 'Cangrejo', 'Voz'] },
  { p: 'Aladdín', c: 'Personajes', x: ['Genio', 'Lámpara', 'Alfombra', 'Deseos', 'Príncipe'] },
  { p: 'Buzz Lightyear', c: 'Personajes', x: ['Toy Story', 'Espacio', 'Al infinito', 'Juguete', 'Alas'] },
  { p: 'Minion', c: 'Personajes', x: ['Amarillo', 'Banana', 'Anteojos', 'Gru', 'Idioma'] },
  { p: 'Gollum', c: 'Personajes', x: ['Anillo', 'Mi precioso', 'Hobbit', 'Cueva', 'Flaco'] },
  { p: 'Frankenstein', c: 'Personajes', x: ['Monstruo', 'Verde', 'Tornillos', 'Científico', 'Rayo'] },
  { p: 'La Momia', c: 'Personajes', x: ['Vendas', 'Egipto', 'Sarcófago', 'Maldición', 'Muerto'] },
  { p: 'Chucky', c: 'Personajes', x: ['Muñeco', 'Terror', 'Cuchillo', 'Pelirrojo', 'Overol'] },
  { p: 'Godzilla', c: 'Personajes', x: ['Monstruo', 'Japón', 'Gigante', 'Ciudad', 'Lagarto'] },
  { p: 'King Kong', c: 'Personajes', x: ['Gorila', 'Gigante', 'Edificio', 'Isla', 'Rubia'] },
  { p: 'Sonic', c: 'Personajes', x: ['Erizo', 'Azul', 'Velocidad', 'Anillos', 'Sega'] },
  { p: 'Pac-Man', c: 'Personajes', x: ['Comer', 'Fantasmas', 'Amarillo', 'Laberinto', 'Arcade'] },
  { p: 'Lara Croft', c: 'Personajes', x: ['Tomb Raider', 'Aventurera', 'Tumbas', 'Videojuego', 'Trenza'] },
  { p: 'Mr. Bean', c: 'Personajes', x: ['Inglés', 'Comedia', 'Oso de peluche', 'Auto verde', 'Gestos'] },
  { p: 'El Chavo', c: 'Personajes', x: ['Barril', 'Vecindad', 'Ocho', 'México', 'Torta de jamón'] },
  { p: 'El Chapulín Colorado', c: 'Personajes', x: ['Antenas', 'Rojo', 'Chipote chillón', 'Héroe', 'México'] },
  { p: 'Wolverine', c: 'Personajes', x: ['Garras', 'X-Men', 'Mutante', 'Regenerar', 'Adamantium'] },
  { p: 'Deadpool', c: 'Personajes', x: ['Rojo', 'Mercenario', 'Cuarta pared', 'Katanas', 'Chistes'] },
  { p: 'Dumbledore', c: 'Personajes', x: ['Director', 'Hogwarts', 'Barba', 'Mago', 'Varita'] },
  { p: 'Voldemort', c: 'Personajes', x: ['Villano', 'Sin nariz', 'Harry Potter', 'Innombrable', 'Varita'] },
  { p: 'Yoda', c: 'Personajes', x: ['Star Wars', 'Verde', 'Maestro', 'Orejas', 'Al revés'] },
  { p: 'Garfield', c: 'Personajes', x: ['Gato', 'Naranja', 'Lasaña', 'Lunes', 'Perezoso'] },
  { p: 'Snoopy', c: 'Personajes', x: ['Perro', 'Blanco', 'Charlie Brown', 'Casita', 'Historieta'] },
  { p: 'Olaf', c: 'Personajes', x: ['Frozen', 'Muñeco de nieve', 'Zanahoria', 'Abrazos', 'Verano'] },
  { p: 'Popeye', c: 'Personajes', x: ['Espinaca', 'Marinero', 'Músculos', 'Pipa', 'Olivia'] },
  { p: 'Tarzán', c: 'Personajes', x: ['Selva', 'Liana', 'Grito', 'Mono', 'Taparrabos'] },
  { p: 'Thanos', c: 'Personajes', x: ['Villano', 'Guantelete', 'Gemas', 'Chasquido', 'Morado'] },
  { p: 'Loki', c: 'Personajes', x: ['Dios', 'Engaños', 'Thor', 'Cuernos', 'Verde'] },
  { p: 'Groot', c: 'Personajes', x: ['Árbol', 'Guardianes', 'Yo soy', 'Espacio', 'Rocket'] },
  { p: 'Flash', c: 'Personajes', x: ['Velocidad', 'Rojo', 'Rayo', 'Correr', 'DC'] },
  { p: 'Aquaman', c: 'Personajes', x: ['Mar', 'Tridente', 'Peces', 'Atlantis', 'Rey'] },
  { p: 'Hermione', c: 'Personajes', x: ['Harry Potter', 'Inteligente', 'Libros', 'Maga', 'Emma Watson'] },
  { p: 'Hagrid', c: 'Personajes', x: ['Gigante', 'Barba', 'Hogwarts', 'Motocicleta', 'Animales'] },
  { p: 'Jack Sparrow', c: 'Personajes', x: ['Pirata', 'Ron', 'Perla Negra', 'Johnny Depp', 'Brújula'] },
  { p: 'Vegeta', c: 'Personajes', x: ['Dragon Ball', 'Príncipe', 'Saiyajin', 'Orgulloso', 'Goku'] },
  { p: 'Luffy', c: 'Personajes', x: ['One Piece', 'Pirata', 'Goma', 'Sombrero de paja', 'Estirarse'] },
  { p: 'Sailor Moon', c: 'Personajes', x: ['Luna', 'Marinera', 'Anime', 'Rodetes', 'Transformación'] },
  { p: 'Hello Kitty', c: 'Personajes', x: ['Gata', 'Moño', 'Japón', 'Rosa', 'Sin boca'] },
  { p: 'Barney', c: 'Personajes', x: ['Dinosaurio', 'Violeta', 'Cantar', 'Niños', 'Te quiero yo'] },
  { p: 'Peppa Pig', c: 'Personajes', x: ['Chancha', 'Rosa', 'Charcos', 'George', 'Dibujito'] },
  { p: 'Bluey', c: 'Personajes', x: ['Perra', 'Azul', 'Australia', 'Bingo', 'Dibujito'] },
  { p: 'Dora la Exploradora', c: 'Personajes', x: ['Mochila', 'Mapa', 'Botas', 'Zorro', 'Preguntas'] },
  { p: 'Scooby-Doo', c: 'Personajes', x: ['Perro', 'Misterios', 'Galletas', 'Shaggy', 'Van'] },
  { p: 'Tom y Jerry', c: 'Personajes', x: ['Gato', 'Ratón', 'Perseguir', 'Trampas', 'Rivales'] },
  { p: 'Piolín', c: 'Personajes', x: ['Canario', 'Amarillo', 'Gato', 'Lindo gatito', 'Jaula'] },
  { p: 'Bugs Bunny', c: 'Personajes', x: ['Conejo', 'Zanahoria', 'Qué hay de nuevo', 'Looney Tunes', 'Gris'] },
  { p: 'El Correcaminos', c: 'Personajes', x: ['Rápido', 'Coyote', 'Bip bip', 'Desierto', 'Trampas'] },
  { p: 'Pedro Picapiedra', c: 'Personajes', x: ['Cavernícola', 'Yabba Dabba Doo', 'Vilma', 'Piedras', 'Dino'] },
  { p: 'Doraemon', c: 'Personajes', x: ['Gato', 'Robot', 'Azul', 'Bolsillo', 'Japón'] },
  { p: 'Maléfica', c: 'Personajes', x: ['Villana', 'Cuernos', 'Bella Durmiente', 'Angelina', 'Dragón'] },
  { p: 'Freddy Krueger', c: 'Personajes', x: ['Sueños', 'Garras', 'Sombrero', 'Quemado', 'Pesadilla'] },
  // ── Videojuegos ──
  { p: 'Minecraft', c: 'Videojuegos', x: ['Bloques', 'Construir', 'Creeper', 'Picar', 'Cubos'] },
  { p: 'Fortnite', c: 'Videojuegos', x: ['Battle Royale', 'Construir', 'Bailes', 'Isla', 'Tormenta'] },
  { p: 'Tetris', c: 'Videojuegos', x: ['Bloques', 'Encajar', 'Líneas', 'Caer', 'Ruso'] },
  { p: 'FIFA', c: 'Videojuegos', x: ['Fútbol', 'EA Sports', 'Ultimate Team', 'Consola', 'Messi'] },
  { p: 'Candy Crush', c: 'Videojuegos', x: ['Caramelos', 'Celular', 'Niveles', 'Combinar', 'Vidas'] },
  { p: 'GTA', c: 'Videojuegos', x: ['Autos', 'Robar', 'San Andreas', 'Policía', 'Misiones'] },
  { p: 'Call of Duty', c: 'Videojuegos', x: ['Guerra', 'Disparos', 'Soldados', 'Online', 'Warzone'] },
  { p: 'Among Us', c: 'Videojuegos', x: ['Impostor', 'Tripulación', 'Nave', 'Sospechoso', 'Tareas'] },
  { p: 'Zelda', c: 'Videojuegos', x: ['Link', 'Espada', 'Princesa', 'Hyrule', 'Trifuerza'] },
  { p: 'Pokémon', c: 'Videojuegos', x: ['Atrapar', 'Pikachu', 'Entrenador', 'Pokebola', 'Evolución'] },
  { p: 'Mario Kart', c: 'Videojuegos', x: ['Carreras', 'Caparazón', 'Banana', 'Karting', 'Nintendo'] },
  { p: 'Counter-Strike', c: 'Videojuegos', x: ['Terroristas', 'Bomba', 'Disparos', 'Policías', 'Computadora'] },
  { p: 'League of Legends', c: 'Videojuegos', x: ['MOBA', 'Campeones', 'Grieta', 'Online', 'Equipos'] },
  { p: 'Angry Birds', c: 'Videojuegos', x: ['Pájaros', 'Gomera', 'Chanchos', 'Celular', 'Huevos'] },
  { p: 'Los Sims', c: 'Videojuegos', x: ['Vida', 'Casa', 'Familia', 'Simular', 'Construir'] },
  { p: 'Crash Bandicoot', c: 'Videojuegos', x: ['Marsupial', 'Cajas', 'Girar', 'Manzanas', 'Naranja'] },
  { p: 'Mortal Kombat', c: 'Videojuegos', x: ['Pelea', 'Fatality', 'Scorpion', 'Sangre', 'Torneo'] },
  { p: 'Street Fighter', c: 'Videojuegos', x: ['Pelea', 'Hadouken', 'Ryu', 'Combos', 'Japón'] },
  { p: 'God of War', c: 'Videojuegos', x: ['Kratos', 'Dioses', 'Hacha', 'Grecia', 'Guerra'] },
  { p: 'Elden Ring', c: 'Videojuegos', x: ['Difícil', 'Jefes', 'Morir', 'Anillo', 'Souls'] },
  { p: 'Roblox', c: 'Videojuegos', x: ['Plataforma', 'Crear', 'Niños', 'Avatares', 'Juegos'] },
  { p: 'Free Fire', c: 'Videojuegos', x: ['Battle Royale', 'Celular', 'Disparos', 'Booyah', 'Isla'] },
  { p: 'Clash Royale', c: 'Videojuegos', x: ['Cartas', 'Torres', 'Coronas', 'Celular', 'Elixir'] },
  { p: 'Doom', c: 'Videojuegos', x: ['Demonios', 'Marte', 'Disparos', 'Infierno', 'Clásico'] },
  { p: 'Space Invaders', c: 'Videojuegos', x: ['Naves', 'Aliens', 'Disparar', 'Arcade', 'Filas'] },
  { p: 'Kirby', c: 'Videojuegos', x: ['Rosa', 'Aspirar', 'Redondo', 'Nintendo', 'Estrella'] },
  { p: 'Donkey Kong', c: 'Videojuegos', x: ['Gorila', 'Corbata', 'Bananas', 'Barriles', 'Nintendo'] },
  { p: 'Luigi', c: 'Videojuegos', x: ['Hermano', 'Verde', 'Mario', 'Bigote', 'Fantasmas'] },
  { p: 'Princesa Peach', c: 'Videojuegos', x: ['Rosa', 'Castillo', 'Rescatar', 'Corona', 'Mario'] },
  { p: 'Bowser', c: 'Videojuegos', x: ['Villano', 'Tortuga', 'Fuego', 'Mario', 'Púas'] },
  { p: 'Charizard', c: 'Videojuegos', x: ['Pokémon', 'Dragón', 'Fuego', 'Naranja', 'Evolución'] },
  { p: 'Master Chief', c: 'Videojuegos', x: ['Halo', 'Casco', 'Soldado', 'Verde', 'Espacial'] },
  { p: 'Plants vs Zombies', c: 'Videojuegos', x: ['Plantas', 'Jardín', 'Girasol', 'Cerebros', 'Defender'] },
  { p: 'Subway Surfers', c: 'Videojuegos', x: ['Correr', 'Tren', 'Vías', 'Monedas', 'Inspector'] },
  { p: 'Need for Speed', c: 'Videojuegos', x: ['Autos', 'Carreras', 'Policía', 'Tuning', 'Velocidad'] },
  { p: 'Halo', c: 'Videojuegos', x: ['Master Chief', 'Casco', 'Alienígenas', 'Xbox', 'Espacial'] },
  { p: 'Portal', c: 'Videojuegos', x: ['Portales', 'Puzzle', 'Torreta', 'GLaDOS', 'Naranja y azul'] },
  { p: 'Metroid', c: 'Videojuegos', x: ['Samus', 'Espacio', 'Nave', 'Casco', 'Nintendo'] },
  { p: 'Castlevania', c: 'Videojuegos', x: ['Vampiros', 'Látigo', 'Castillo', 'Drácula', 'Konami'] },
  { p: 'Silent Hill', c: 'Videojuegos', x: ['Terror', 'Niebla', 'Pueblo', 'Radio', 'Konami'] },
  { p: 'Bloodborne', c: 'Videojuegos', x: ['Difícil', 'Bestias', 'Gótico', 'Souls', 'Cazador'] },
  { p: 'Dark Souls', c: 'Videojuegos', x: ['Difícil', 'Morir', 'Hoguera', 'Jefes', 'FromSoftware'] },
  { p: 'Sekiro', c: 'Videojuegos', x: ['Ninja', 'Japón', 'Espada', 'Difícil', 'Prótesis'] },
  { p: 'NBA 2K', c: 'Videojuegos', x: ['Básquet', 'Deportivo', 'NBA', 'Consola', 'Canasta'] },
  { p: 'PES', c: 'Videojuegos', x: ['Fútbol', 'Konami', 'Rival del FIFA', 'Consola', 'Pelota'] },
  { p: 'Tomb Raider', c: 'Videojuegos', x: ['Lara Croft', 'Tumbas', 'Aventura', 'Reliquias', 'Pistolas'] },
  { p: 'Bioshock', c: 'Videojuegos', x: ['Ciudad submarina', 'Distopía', 'Jeringa', 'Rapture', 'Shooter'] },
  { p: 'Tekken', c: 'Videojuegos', x: ['Pelea', 'Torneo', 'Combos', 'Japón', 'Osos'] },
  { p: 'Watch Dogs', c: 'Videojuegos', x: ['Hackear', 'Ciudad', 'Ubisoft', 'Celular', 'Vigilancia'] },
  { p: 'Death Stranding', c: 'Videojuegos', x: ['Kojima', 'Paquetes', 'Bebé', 'Caminar', 'Conectar'] },
  { p: 'The Last of Us', c: 'Videojuegos', x: ['Hongos', 'Apocalipsis', 'Joel', 'Ellie', 'Serie'] },
  { p: 'Red Dead Redemption', c: 'Videojuegos', x: ['Cowboy', 'Caballo', 'Oeste', 'Arthur', 'Rockstar'] },
  { p: 'Cyberpunk', c: 'Videojuegos', x: ['Futuro', 'Neón', 'Keanu Reeves', 'Ciudad', 'Implantes'] },
  { p: 'Assassins Creed', c: 'Videojuegos', x: ['Asesino', 'Capucha', 'Historia', 'Saltar', 'Templarios'] },
  { p: 'Resident Evil', c: 'Videojuegos', x: ['Zombis', 'Virus', 'Mansión', 'Umbrella', 'Terror'] },
  { p: 'Final Fantasy', c: 'Videojuegos', x: ['RPG', 'Japón', 'Espadas', 'Magia', 'Cloud'] },
  { p: 'Metal Gear', c: 'Videojuegos', x: ['Espionaje', 'Snake', 'Caja', 'Sigilo', 'Alerta'] },
  { p: 'Valorant', c: 'Videojuegos', x: ['Shooter', 'Agentes', 'Riot', 'Habilidades', 'Spike'] },
  { p: 'World of Warcraft', c: 'Videojuegos', x: ['MMORPG', 'Orcos', 'Azeroth', 'Suscripción', 'Blizzard'] },
  { p: 'Age of Empires', c: 'Videojuegos', x: ['Estrategia', 'Civilizaciones', 'Aldeanos', 'Edades', 'Wololo'] },
  { p: 'Diablo', c: 'Videojuegos', x: ['Infierno', 'Demonios', 'Clic', 'Botín', 'Blizzard'] },
  { p: 'Duck Hunt', c: 'Videojuegos', x: ['Patos', 'Pistola', 'Perro', 'Reírse', 'NES'] },
  { p: 'Wii Sports', c: 'Videojuegos', x: ['Nintendo', 'Tenis', 'Bowling', 'Control', 'Familia'] },
  { p: 'Just Dance', c: 'Videojuegos', x: ['Bailar', 'Coreografía', 'Pantalla', 'Puntos', 'Fiesta'] },
  { p: 'Guitar Hero', c: 'Videojuegos', x: ['Guitarra', 'Botones', 'Rock', 'Notas', 'Colores'] },
  { p: 'Brawl Stars', c: 'Videojuegos', x: ['Celular', 'Supercell', 'Peleas', 'Brawlers', 'Gemas'] },
  { p: 'Genshin Impact', c: 'Videojuegos', x: ['Anime', 'Mundo abierto', 'Gacha', 'Elementos', 'Personajes'] },
  { p: 'Pou', c: 'Videojuegos', x: ['Mascota', 'Celular', 'Alimentar', 'Marrón', 'Cuidar'] },
  { p: 'La Viborita', c: 'Videojuegos', x: ['Nokia', 'Celular', 'Comer', 'Crecer', 'Chocarse'] },
  { p: 'Buscaminas', c: 'Videojuegos', x: ['Bombas', 'Números', 'Banderas', 'Windows', 'Casillas'] },
  // ── Deportes ──
  { p: 'Fútbol', c: 'Deportes', x: ['Pelota', 'Gol', 'Cancha', 'Equipo', 'Arco'] },
  { p: 'Tenis', c: 'Deportes', x: ['Raqueta', 'Pelota', 'Red', 'Saque', 'Cancha'] },
  { p: 'Natación', c: 'Deportes', x: ['Agua', 'Pileta', 'Nadar', 'Brazadas', 'Malla'] },
  { p: 'Básquet', c: 'Deportes', x: ['Aro', 'Pelota', 'Canasta', 'Rebote', 'Picar'] },
  { p: 'Boxeo', c: 'Deportes', x: ['Guantes', 'Ring', 'Golpe', 'Nocaut', 'Pelea'] },
  { p: 'Maratón', c: 'Deportes', x: ['Correr', 'Kilómetros', 'Meta', 'Resistencia', 'Carrera'] },
  { p: 'Ajedrez', c: 'Deportes', x: ['Tablero', 'Rey', 'Jaque', 'Piezas', 'Estrategia'] },
  { p: 'Surf', c: 'Deportes', x: ['Ola', 'Tabla', 'Mar', 'Equilibrio', 'Playa'] },
  { p: 'Esquí', c: 'Deportes', x: ['Nieve', 'Montaña', 'Tablas', 'Bastones', 'Invierno'] },
  { p: 'Yoga', c: 'Deportes', x: ['Estirar', 'Posturas', 'Relajación', 'Colchoneta', 'Respirar'] },
  { p: 'Árbitro', c: 'Deportes', x: ['Silbato', 'Tarjeta', 'Falta', 'Juez', 'Partido'] },
  { p: 'Vóley', c: 'Deportes', x: ['Red', 'Pelota', 'Playa', 'Manos', 'Saque'] },
  { p: 'Rugby', c: 'Deportes', x: ['Ovalada', 'Try', 'Tackle', 'Pumas', 'Scrum'] },
  { p: 'Hockey', c: 'Deportes', x: ['Palo', 'Bocha', 'Leonas', 'Césped', 'Patines'] },
  { p: 'Golf', c: 'Deportes', x: ['Hoyo', 'Palos', 'Pelotita', 'Césped', 'Tiger Woods'] },
  { p: 'Ciclismo', c: 'Deportes', x: ['Bicicleta', 'Pedalear', 'Tour de Francia', 'Casco', 'Ruedas'] },
  { p: 'Skate', c: 'Deportes', x: ['Tabla', 'Ruedas', 'Trucos', 'Rampa', 'Caerse'] },
  { p: 'Fórmula 1', c: 'Deportes', x: ['Autos', 'Carrera', 'Velocidad', 'Boxes', 'Colapinto'] },
  { p: 'Esgrima', c: 'Deportes', x: ['Espada', 'Careta', 'Tocado', 'Duelo', 'Blanco'] },
  { p: 'Gimnasia artística', c: 'Deportes', x: ['Piruetas', 'Barras', 'Medalla', 'Flexibilidad', 'Olimpiadas'] },
  { p: 'Pádel', c: 'Deportes', x: ['Paleta', 'Pared', 'Cancha', 'Parejas', 'Moda'] },
  // ── Objetos ──
  { p: 'Paraguas', c: 'Objetos', x: ['Lluvia', 'Abrir', 'Mojarse', 'Mango', 'Cubrirse'] },
  { p: 'Espejo', c: 'Objetos', x: ['Reflejo', 'Vidrio', 'Mirarse', 'Baño', 'Imagen'] },
  { p: 'Almohada', c: 'Objetos', x: ['Dormir', 'Cama', 'Cabeza', 'Suave', 'Plumas'] },
  { p: 'Tijera', c: 'Objetos', x: ['Cortar', 'Papel', 'Filo', 'Dos', 'Peluquería'] },
  { p: 'Heladera', c: 'Objetos', x: ['Frío', 'Cocina', 'Comida', 'Puerta', 'Congelador'] },
  { p: 'Celular', c: 'Objetos', x: ['Llamar', 'Pantalla', 'Apps', 'Batería', 'Mensaje'] },
  { p: 'Llave', c: 'Objetos', x: ['Puerta', 'Abrir', 'Cerradura', 'Candado', 'Auto'] },
  { p: 'Reloj', c: 'Objetos', x: ['Hora', 'Muñeca', 'Agujas', 'Tiempo', 'Despertador'] },
  { p: 'Escoba', c: 'Objetos', x: ['Barrer', 'Limpiar', 'Palo', 'Piso', 'Bruja'] },
  { p: 'Anteojos', c: 'Objetos', x: ['Ver', 'Ojos', 'Marco', 'Lentes', 'Sol'] },
  { p: 'Cepillo de dientes', c: 'Objetos', x: ['Pasta', 'Boca', 'Lavar', 'Baño', 'Higiene'] },
  { p: 'Lapicera', c: 'Objetos', x: ['Escribir', 'Tinta', 'Birome', 'Papel', 'Tapa'] },
  { p: 'Mochila', c: 'Objetos', x: ['Espalda', 'Escuela', 'Cargar', 'Cierres', 'Viaje'] },
  { p: 'Auriculares', c: 'Objetos', x: ['Música', 'Orejas', 'Escuchar', 'Cable', 'Inalámbricos'] },
  { p: 'Ventilador', c: 'Objetos', x: ['Calor', 'Aspas', 'Girar', 'Verano', 'Aire'] },
  { p: 'Martillo', c: 'Objetos', x: ['Clavo', 'Golpear', 'Herramienta', 'Thor', 'Carpintero'] },
  { p: 'Vela', c: 'Objetos', x: ['Fuego', 'Cera', 'Cumpleaños', 'Soplar', 'Apagón'] },
  { p: 'Linterna', c: 'Objetos', x: ['Luz', 'Oscuridad', 'Pilas', 'Camping', 'Alumbrar'] },
  { p: 'Control remoto', c: 'Objetos', x: ['Televisión', 'Botones', 'Cambiar', 'Pilas', 'Sillón'] },
  { p: 'Valija', c: 'Objetos', x: ['Viaje', 'Ropa', 'Ruedas', 'Aeropuerto', 'Empacar'] },
  { p: 'Silla', c: 'Objetos', x: ['Sentarse', 'Patas', 'Mesa', 'Madera', 'Respaldo'] },
  // ── Lugares ──
  { p: 'Playa', c: 'Lugares', x: ['Arena', 'Mar', 'Sol', 'Sombrilla', 'Verano'] },
  { p: 'Hospital', c: 'Lugares', x: ['Médico', 'Enfermo', 'Camilla', 'Ambulancia', 'Cirugía'] },
  { p: 'Escuela', c: 'Lugares', x: ['Maestra', 'Alumnos', 'Pizarrón', 'Recreo', 'Aula'] },
  { p: 'Aeropuerto', c: 'Lugares', x: ['Avión', 'Valija', 'Vuelo', 'Pasaporte', 'Despegar'] },
  { p: 'Supermercado', c: 'Lugares', x: ['Comprar', 'Carrito', 'Góndola', 'Caja', 'Precios'] },
  { p: 'Cine', c: 'Lugares', x: ['Película', 'Pantalla', 'Butaca', 'Entrada', 'Pochoclo'] },
  { p: 'Museo', c: 'Lugares', x: ['Arte', 'Cuadros', 'Historia', 'Exhibición', 'Antiguo'] },
  { p: 'Selva', c: 'Lugares', x: ['Árboles', 'Animales', 'Húmedo', 'Tarzán', 'Verde'] },
  { p: 'Desierto', c: 'Lugares', x: ['Arena', 'Calor', 'Camello', 'Cactus', 'Seco'] },
  { p: 'Luna', c: 'Lugares', x: ['Espacio', 'Astronauta', 'Noche', 'Cráter', 'Llena'] },
  { p: 'Gimnasio', c: 'Lugares', x: ['Pesas', 'Ejercicio', 'Músculos', 'Entrenar', 'Máquinas'] },
  { p: 'Cancha', c: 'Lugares', x: ['Fútbol', 'Estadio', 'Hinchada', 'Pasto', 'Tribuna'] },
  { p: 'Iglesia', c: 'Lugares', x: ['Cura', 'Misa', 'Rezar', 'Campana', 'Cruz'] },
  { p: 'Biblioteca', c: 'Lugares', x: ['Libros', 'Silencio', 'Estudiar', 'Estantes', 'Prestar'] },
  { p: 'Zoológico', c: 'Lugares', x: ['Animales', 'Jaulas', 'Visitar', 'Leones', 'Paseo'] },
  { p: 'Restaurante', c: 'Lugares', x: ['Comer', 'Mozo', 'Menú', 'Mesa', 'Propina'] },
  { p: 'Plaza', c: 'Lugares', x: ['Juegos', 'Hamacas', 'Árboles', 'Banco', 'Barrio'] },
  { p: 'Cementerio', c: 'Lugares', x: ['Tumbas', 'Muertos', 'Flores', 'Lápida', 'Fantasmas'] },
  { p: 'Estación de servicio', c: 'Lugares', x: ['Nafta', 'Auto', 'Cargar', 'Surtidor', 'Ruta'] },
  { p: 'Peluquería', c: 'Lugares', x: ['Cortar', 'Pelo', 'Tijeras', 'Espejo', 'Peine'] },
  { p: 'Antártida', c: 'Lugares', x: ['Frío', 'Hielo', 'Pingüinos', 'Sur', 'Blanco'] },
  // ── Música y famosos ──
  { p: 'Guitarra', c: 'Música y famosos', x: ['Cuerdas', 'Tocar', 'Rock', 'Acordes', 'Instrumento'] },
  { p: 'Batería', c: 'Música y famosos', x: ['Palillos', 'Ritmo', 'Tambor', 'Platillos', 'Golpear'] },
  { p: 'Micrófono', c: 'Música y famosos', x: ['Cantar', 'Voz', 'Escenario', 'Karaoke', 'Hablar'] },
  { p: 'Karaoke', c: 'Música y famosos', x: ['Cantar', 'Letra', 'Pantalla', 'Micrófono', 'Bar'] },
  { p: 'Ópera', c: 'Música y famosos', x: ['Cantar', 'Teatro', 'Soprano', 'Clásica', 'Italiano'] },
  { p: 'DJ', c: 'Música y famosos', x: ['Música', 'Mezclar', 'Fiesta', 'Bandeja', 'Electrónica'] },
  { p: 'Tango', c: 'Argentina', x: ['Baile', 'Buenos Aires', 'Gardel', 'Pareja', 'Bandoneón'] },
  { p: 'Coro', c: 'Música y famosos', x: ['Cantar', 'Grupo', 'Voces', 'Iglesia', 'Director'] },
  { p: 'Violín', c: 'Música y famosos', x: ['Cuerdas', 'Arco', 'Clásica', 'Orquesta', 'Hombro'] },
  { p: 'Rockstar', c: 'Música y famosos', x: ['Escenario', 'Guitarra', 'Fama', 'Gira', 'Fans'] },
  { p: 'Cumbia', c: 'Argentina', x: ['Baile', 'Fiesta', 'Ritmo', 'Música', 'Tropical'] },
  { p: 'Piano', c: 'Música y famosos', x: ['Teclas', 'Blanco y negro', 'Cola', 'Concierto', 'Dedos'] },
  { p: 'Trompeta', c: 'Música y famosos', x: ['Soplar', 'Viento', 'Jazz', 'Dorada', 'Labios'] },
  { p: 'Acordeón', c: 'Música y famosos', x: ['Fuelle', 'Apretar', 'Cumbia', 'Teclas', 'Aire'] },
  { p: 'Reggaetón', c: 'Música y famosos', x: ['Perreo', 'Ritmo', 'Puerto Rico', 'Bailar', 'Fiesta'] },
  { p: 'Orquesta', c: 'Música y famosos', x: ['Director', 'Instrumentos', 'Batuta', 'Sinfonía', 'Músicos'] },
  { p: 'Recital', c: 'Música y famosos', x: ['Banda', 'Escenario', 'Entradas', 'Público', 'Vivo'] },
  { p: 'Folclore', c: 'Argentina', x: ['Zamba', 'Guitarra', 'Tradición', 'Peña', 'Bombo'] },
  { p: 'Rap', c: 'Música y famosos', x: ['Rimas', 'Freestyle', 'Batalla', 'Micrófono', 'Calle'] },
  { p: 'Flauta', c: 'Música y famosos', x: ['Soplar', 'Agujeros', 'Dulce', 'Escuela', 'Hamelín'] },
  { p: 'Vinilo', c: 'Música y famosos', x: ['Disco', 'Tocadiscos', 'Antiguo', 'Negro', 'Colección'] },
  { p: 'Queen', c: 'Música y famosos', x: ['Freddie Mercury', 'Banda', 'Reina', 'Bohemian Rhapsody', 'We Are the Champions'] },
  { p: 'Los Beatles', c: 'Música y famosos', x: ['Liverpool', 'Cuatro', 'Yellow Submarine', 'John Lennon', 'Abbey Road'] },
  { p: 'Rolling Stones', c: 'Música y famosos', x: ['Lengua', 'Mick Jagger', 'Rock', 'Satisfaction', 'Ingleses'] },
  { p: 'ABBA', c: 'Música y famosos', x: ['Suecia', 'Dancing Queen', 'Mamma Mia', 'Cuatro', 'Disco'] },
  { p: 'Soda Stereo', c: 'Argentina', x: ['Cerati', 'Rock nacional', 'De Música Ligera', 'Trilogía', 'Persiana Americana'] },
  { p: 'Los Redondos', c: 'Argentina', x: ['Ricota', 'Indio Solari', 'Rock nacional', 'Skay', 'Misa'] },
  { p: 'BTS', c: 'Música y famosos', x: ['K-pop', 'Corea', 'Siete', 'Army', 'Baile'] },
  { p: 'Despacito', c: 'Música y famosos', x: ['Luis Fonsi', 'Puerto Rico', 'Éxito', 'Daddy Yankee', 'Lento'] },
  { p: 'La Macarena', c: 'Música y famosos', x: ['Baile', 'Manos', 'Los del Río', 'Fiesta', 'Coreografía'] },
  { p: 'Feliz Cumpleaños', c: 'Música y famosos', x: ['Canción', 'Torta', 'Velitas', 'Cantar', 'Deseo'] },
  { p: 'Gangnam Style', c: 'Música y famosos', x: ['PSY', 'Corea', 'Baile', 'Caballo', 'YouTube'] },
  { p: 'El Aserejé', c: 'Música y famosos', x: ['Las Ketchup', 'Baile', 'Verano', 'Español', 'Coreografía'] },
  { p: 'Muchachos', c: 'Argentina', x: ['Mundial', 'Hinchada', 'La Mosca', 'Cantito', 'Qatar'] },
  { p: 'Grammy', c: 'Música y famosos', x: ['Premio', 'Música', 'Gramófono', 'Estatuilla', 'Ganador'] },
  { p: 'Spotify', c: 'Música y famosos', x: ['Música', 'App', 'Playlists', 'Verde', 'Streaming'] },
  { p: 'Lollapalooza', c: 'Música y famosos', x: ['Festival', 'Bandas', 'Escenarios', 'Pulsera', 'Multitud'] },
  { p: 'Playlist', c: 'Música y famosos', x: ['Canciones', 'Lista', 'Spotify', 'Armar', 'Música'] },
  { p: 'Autotune', c: 'Música y famosos', x: ['Voz', 'Robot', 'Afinar', 'Trap', 'Efecto'] },
  { p: 'Videoclip', c: 'Música y famosos', x: ['Música', 'Filmar', 'YouTube', 'Canción', 'Artista'] },
  { p: 'Serenata', c: 'Música y famosos', x: ['Ventana', 'Guitarra', 'Amor', 'Cantar', 'Noche'] },
  // ── Acciones ──
  { p: 'Estornudar', c: 'Acciones', x: ['Nariz', 'Achís', 'Resfrío', 'Pañuelo', 'Salud'] },
  { p: 'Bostezar', c: 'Acciones', x: ['Sueño', 'Boca', 'Cansado', 'Aburrido', 'Abrir'] },
  { p: 'Aplaudir', c: 'Acciones', x: ['Manos', 'Bravo', 'Teatro', 'Felicitar', 'Ruido'] },
  { p: 'Cocinar', c: 'Acciones', x: ['Comida', 'Olla', 'Chef', 'Receta', 'Fuego'] },
  { p: 'Bailar', c: 'Acciones', x: ['Música', 'Mover', 'Fiesta', 'Pareja', 'Ritmo'] },
  { p: 'Dormir', c: 'Acciones', x: ['Cama', 'Noche', 'Soñar', 'Roncar', 'Descansar'] },
  { p: 'Manejar', c: 'Acciones', x: ['Auto', 'Volante', 'Ruta', 'Licencia', 'Conducir'] },
  { p: 'Pescar', c: 'Acciones', x: ['Caña', 'Río', 'Anzuelo', 'Pez', 'Paciencia'] },
  { p: 'Pintar', c: 'Acciones', x: ['Pincel', 'Colores', 'Cuadro', 'Pared', 'Artista'] },
  { p: 'Silbar', c: 'Acciones', x: ['Boca', 'Sonido', 'Melodía', 'Labios', 'Aire'] },
  { p: 'Abrazar', c: 'Acciones', x: ['Brazos', 'Cariño', 'Apretar', 'Saludo', 'Amor'] },
  { p: 'Correr', c: 'Acciones', x: ['Rápido', 'Piernas', 'Maratón', 'Transpirar', 'Zapatillas'] },
  { p: 'Saltar', c: 'Acciones', x: ['Alto', 'Soga', 'Piernas', 'Rana', 'Brincar'] },
  { p: 'Llorar', c: 'Acciones', x: ['Lágrimas', 'Triste', 'Pañuelo', 'Cebolla', 'Bebé'] },
  { p: 'Reír', c: 'Acciones', x: ['Chiste', 'Carcajada', 'Gracioso', 'Cosquillas', 'Boca'] },
  { p: 'Cantar', c: 'Acciones', x: ['Voz', 'Música', 'Ducha', 'Micrófono', 'Afinar'] },
  { p: 'Escribir', c: 'Acciones', x: ['Lapicera', 'Papel', 'Letras', 'Carta', 'Mano'] },
  { p: 'Fotografiar', c: 'Acciones', x: ['Cámara', 'Foto', 'Sonreír', 'Flash', 'Retrato'] },
  { p: 'Besar', c: 'Acciones', x: ['Labios', 'Amor', 'Pareja', 'Boca', 'Romántico'] },
  { p: 'Gritar', c: 'Acciones', x: ['Fuerte', 'Voz', 'Enojado', 'Susto', 'Garganta'] },
  { p: 'Maquillarse', c: 'Acciones', x: ['Espejo', 'Labial', 'Cara', 'Pintarse', 'Rubor'] },

  // ── Ampliación: +15 por categoría ──
  // Animales
  { p: 'Zorro', c: 'Animales', x: ['Astuto', 'Cola', 'Naranja', 'Gallinero', 'Bosque'] },
  { p: 'Delfín', c: 'Animales', x: ['Mar', 'Inteligente', 'Saltar', 'Gris', 'Nadar'] },
  { p: 'Ballena', c: 'Animales', x: ['Mar', 'Gigante', 'Agua', 'Chorro', 'Azul'] },
  { p: 'Rana', c: 'Animales', x: ['Saltar', 'Verde', 'Croar', 'Charco', 'Renacuajo'] },
  { p: 'Conejo', c: 'Animales', x: ['Orejas', 'Zanahoria', 'Saltar', 'Madriguera', 'Pascua'] },
  { p: 'Ardilla', c: 'Animales', x: ['Cola', 'Nuez', 'Árbol', 'Bellota', 'Trepar'] },
  { p: 'Lobo', c: 'Animales', x: ['Aullar', 'Luna', 'Manada', 'Bosque', 'Caperucita'] },
  { p: 'Tigre', c: 'Animales', x: ['Rayas', 'Felino', 'Naranja', 'Selva', 'Rugir'] },
  { p: 'Cebra', c: 'Animales', x: ['Rayas', 'Blanco y negro', 'África', 'Caballo', 'Sabana'] },
  { p: 'Rinoceronte', c: 'Animales', x: ['Cuerno', 'Gris', 'Grande', 'África', 'Cuero'] },
  { p: 'Gallina', c: 'Animales', x: ['Huevo', 'Cacarear', 'Granja', 'Plumas', 'Pollito'] },
  { p: 'Pato', c: 'Animales', x: ['Cuac', 'Agua', 'Pico', 'Nadar', 'Plumas'] },
  { p: 'Camello', c: 'Animales', x: ['Joroba', 'Desierto', 'Agua', 'Arena', 'Beduino'] },
  { p: 'Araña', c: 'Animales', x: ['Telaraña', 'Ocho patas', 'Insecto', 'Picar', 'Rincón'] },
  { p: 'Mariposa', c: 'Animales', x: ['Alas', 'Colores', 'Oruga', 'Volar', 'Flor'] },
  // Comida
  { p: 'Alfajor', c: 'Argentina', x: ['Dulce de leche', 'Tapas', 'Chocolate', 'Argentina', 'Redondo'] },
  { p: 'Choripán', c: 'Argentina', x: ['Chorizo', 'Pan', 'Cancha', 'Chimichurri', 'Parrilla'] },
  { p: 'Ñoquis', c: 'Argentina', x: ['29', 'Papa', 'Pasta', 'Salsa', 'Plata'] },
  { p: 'Locro', c: 'Argentina', x: ['25 de Mayo', 'Maíz', 'Guiso', 'Zapallo', 'Patria'] },
  { p: 'Facturas', c: 'Argentina', x: ['Panadería', 'Medialunas', 'Dulce', 'Desayuno', 'Docena'] },
  { p: 'Medialuna', c: 'Argentina', x: ['Factura', 'Café', 'Manteca', 'Croissant', 'Desayuno'] },
  { p: 'Flan', c: 'Comida', x: ['Dulce de leche', 'Postre', 'Caramelo', 'Huevo', 'Temblar'] },
  { p: 'Ravioles', c: 'Comida', x: ['Pasta', 'Relleno', 'Domingo', 'Salsa', 'Ricota'] },
  { p: 'Tarta', c: 'Comida', x: ['Masa', 'Relleno', 'Verdura', 'Horno', 'Jamón y queso'] },
  { p: 'Sándwich de miga', c: 'Comida', x: ['Pan', 'Jamón', 'Cumpleaños', 'Triple', 'Sin corteza'] },
  { p: 'Puré', c: 'Comida', x: ['Papa', 'Pisar', 'Milanesa', 'Suave', 'Guarnición'] },
  { p: 'Tostada', c: 'Comida', x: ['Pan', 'Tostadora', 'Manteca', 'Desayuno', 'Crujiente'] },
  { p: 'Yogur', c: 'Comida', x: ['Lácteo', 'Cuchara', 'Frutilla', 'Pote', 'Desayuno'] },
  { p: 'Panqueque', c: 'Comida', x: ['Dulce de leche', 'Enrollar', 'Masa', 'Sartén', 'Fino'] },
  { p: 'Frutilla', c: 'Comida', x: ['Roja', 'Fruta', 'Crema', 'Dulce', 'Semillitas'] },
  // Cine y series
  { p: 'The Office', c: 'Cine y series', x: ['Oficina', 'Jefe', 'Comedia', 'Documental falso', 'Papel'] },
  { p: 'The Big Bang Theory', c: 'Cine y series', x: ['Sheldon', 'Científicos', 'Nerds', 'Bazinga', 'Física'] },
  { p: 'Rick y Morty', c: 'Cine y series', x: ['Científico', 'Portal', 'Animada', 'Abuelo', 'Dimensiones'] },
  { p: 'La Niñera', c: 'Cine y series', x: ['Fran', 'Voz', 'Nueva York', 'Mucama', 'Millonario'] },
  { p: 'Chespirito', c: 'Cine y series', x: ['México', 'Chavo', 'Comedia', 'Vecindad', 'Chapulín'] },
  { p: 'Vikingos', c: 'Cine y series', x: ['Ragnar', 'Barcos', 'Guerreros', 'Nórdicos', 'Hachas'] },
  { p: 'The Mandalorian', c: 'Cine y series', x: ['Star Wars', 'Casco', 'Baby Yoda', 'Cazarrecompensas', 'Disney'] },
  { p: 'Sex Education', c: 'Cine y series', x: ['Adolescentes', 'Colegio', 'Netflix', 'Terapia', 'Inglesa'] },
  { p: 'Dark', c: 'Cine y series', x: ['Alemania', 'Tiempo', 'Cueva', 'Confusa', 'Netflix'] },
  { p: 'Los Soprano', c: 'Cine y series', x: ['Mafia', 'Nueva Jersey', 'Terapeuta', 'Tony', 'Italianos'] },
  { p: 'Chernobyl', c: 'Cine y series', x: ['Reactor', 'Rusia', 'Radiación', 'Explosión', 'Miniserie'] },
  { p: 'Modern Family', c: 'Cine y series', x: ['Familia', 'Documental falso', 'Comedia', 'Colombiana', 'Yerno'] },
  { p: 'CSI', c: 'Cine y series', x: ['Crimen', 'Investigación', 'Forense', 'Escena', 'Pistas'] },
  { p: 'Los Locos Addams', c: 'Cine y series', x: ['Familia', 'Gótica', 'Merlina', 'Dedos', 'Mansión'] },
  { p: 'Los 100', c: 'Cine y series', x: ['Apocalipsis', 'Espacio', 'Jóvenes', 'Tierra', 'Radiación'] },
  // Películas
  { p: 'El Joker', c: 'Películas', x: ['Payaso', 'Villano', 'Risa', 'Escaleras', 'Gotham'] },
  { p: 'Parásitos', c: 'Películas', x: ['Corea', 'Oscar', 'Ricos y pobres', 'Sótano', 'Sifón'] },
  { p: 'El Origen', c: 'Películas', x: ['Sueños', 'DiCaprio', 'Trompo', 'Niveles', 'Nolan'] },
  { p: 'La La Land', c: 'Películas', x: ['Musical', 'Los Ángeles', 'Piano', 'Amor', 'Ryan Gosling'] },
  { p: 'El Show de Truman', c: 'Películas', x: ['Reality', 'Jim Carrey', 'Cámaras', 'Isla', 'Ciudad falsa'] },
  { p: 'Bambi', c: 'Películas', x: ['Ciervo', 'Disney', 'Bosque', 'Mamá', 'Tambor'] },
  { p: 'Dumbo', c: 'Películas', x: ['Elefante', 'Orejas', 'Volar', 'Circo', 'Disney'] },
  { p: 'El Libro de la Selva', c: 'Películas', x: ['Mowgli', 'Oso', 'Pantera', 'Selva', 'Disney'] },
  { p: 'La Bella y la Bestia', c: 'Películas', x: ['Rosa', 'Castillo', 'Disney', 'Bella', 'Monstruo'] },
  { p: 'Enredados', c: 'Películas', x: ['Rapunzel', 'Pelo largo', 'Torre', 'Disney', 'Sartén'] },
  { p: 'Zootopia', c: 'Películas', x: ['Coneja', 'Zorro', 'Policía', 'Animales', 'Ciudad'] },
  { p: 'Scream', c: 'Películas', x: ['Terror', 'Máscara', 'Cuchillo', 'Teléfono', 'Grito'] },
  { p: 'Halloween', c: 'Películas', x: ['Terror', 'Michael Myers', 'Máscara blanca', 'Cuchillo', 'Disfraces'] },
  { p: 'Viernes 13', c: 'Películas', x: ['Jason', 'Terror', 'Campamento', 'Máscara de hockey', 'Machete'] },
  { p: 'El Aro', c: 'Películas', x: ['Terror', 'Video', 'Pozo', 'Pelo', 'Siete días'] },
  // Actores y famosos
  { p: 'Robert De Niro', c: 'Actores y famosos', x: ['Actor', 'Mafia', 'Taxi Driver', 'Italoamericano', 'Toro Salvaje'] },
  { p: 'Al Pacino', c: 'Actores y famosos', x: ['Padrino', 'Actor', 'Scarface', 'Bajito', 'Italiano'] },
  { p: 'Meryl Streep', c: 'Actores y famosos', x: ['Actriz', 'Oscar', 'Camaleónica', 'Hollywood', 'Diablo viste a la moda'] },
  { p: 'Scarlett Johansson', c: 'Actores y famosos', x: ['Viuda Negra', 'Actriz', 'Marvel', 'Rubia', 'Hollywood'] },
  { p: 'Robert Downey Jr', c: 'Actores y famosos', x: ['Iron Man', 'Actor', 'Barba', 'Marvel', 'Tony Stark'] },
  { p: 'Tom Hanks', c: 'Actores y famosos', x: ['Forrest Gump', 'Actor', 'Náufrago', 'Toy Story', 'Bueno'] },
  { p: 'Denzel Washington', c: 'Actores y famosos', x: ['Actor', 'Oscar', 'Afroamericano', 'Hollywood', 'Drama'] },
  { p: 'Nicolas Cage', c: 'Actores y famosos', x: ['Actor', 'Memes', 'Cara', 'Hollywood', 'Intenso'] },
  { p: 'Pedro Pascal', c: 'Actores y famosos', x: ['Chileno', 'Mandalorian', 'The Last of Us', 'Actor', 'Papá'] },
  { p: 'Zendaya', c: 'Actores y famosos', x: ['Actriz', 'Euphoria', 'Spider-Man', 'Duna', 'Morocha'] },
  { p: 'Margot Robbie', c: 'Actores y famosos', x: ['Barbie', 'Actriz', 'Australiana', 'Rubia', 'Harley Quinn'] },
  { p: 'Pampita', c: 'Actores y famosos', x: ['Modelo', 'Argentina', 'Jurado', 'Morocha', 'Pasarela'] },
  { p: 'Adrián Suar', c: 'Argentina', x: ['Actor', 'Productor', 'Argentina', 'Pol-ka', 'Comedia'] },
  { p: 'Nicolás Furtado', c: 'Actores y famosos', x: ['Actor', 'Uruguayo', 'El Marginal', 'Diosito', 'Cárcel'] },
  { p: 'Lionel Scaloni', c: 'Argentina', x: ['Director técnico', 'Selección', 'Campeón del mundo', 'Pujato', 'Argentina'] },
  // Personajes
  { p: 'Woody', c: 'Personajes', x: ['Toy Story', 'Vaquero', 'Sombrero', 'Sheriff', 'Juguete'] },
  { p: 'Elsa', c: 'Personajes', x: ['Frozen', 'Hielo', 'Reina', 'Trenza', 'Poderes'] },
  { p: 'Gru', c: 'Personajes', x: ['Minions', 'Villano', 'Nariz larga', 'Bufanda', 'Nenas'] },
  { p: 'Stitch', c: 'Personajes', x: ['Azul', 'Lilo', 'Alien', 'Orejas', 'Experimento'] },
  { p: 'El Zorro', c: 'Personajes', x: ['Máscara', 'Espada', 'Z', 'Capa negra', 'Justiciero'] },
  { p: 'Bob Patiño', c: 'Personajes', x: ['Simpson', 'Villano', 'Pelo', 'Rastrillos', 'Bart'] },
  { p: 'Ned Flanders', c: 'Personajes', x: ['Simpson', 'Vecino', 'Bigote', 'Religioso', 'Holita'] },
  { p: 'Krusty', c: 'Personajes', x: ['Payaso', 'Simpson', 'Programa', 'Verde', 'Risa'] },
  { p: 'Marge', c: 'Personajes', x: ['Simpson', 'Pelo azul', 'Ama de casa', 'Homero', 'Alta'] },
  { p: 'Lisa Simpson', c: 'Personajes', x: ['Saxofón', 'Inteligente', 'Amarilla', 'Bart', 'Nena'] },
  { p: 'Patricio', c: 'Personajes', x: ['Bob Esponja', 'Estrella', 'Rosa', 'Tonto', 'Mar'] },
  { p: 'Calamardo', c: 'Personajes', x: ['Bob Esponja', 'Pulpo', 'Clarinete', 'Malhumorado', 'Vecino'] },
  { p: 'Mafalda', c: 'Argentina', x: ['Historieta', 'Argentina', 'Sopa', 'Quino', 'Nena'] },
  { p: 'Gaturro', c: 'Argentina', x: ['Gato', 'Historieta', 'Argentina', 'Nik', 'Enamorado'] },
  { p: 'El Pato Lucas', c: 'Personajes', x: ['Pato', 'Negro', 'Looney Tunes', 'Ceceo', 'Bugs Bunny'] },
  // Videojuegos
  { p: 'Overwatch', c: 'Videojuegos', x: ['Shooter', 'Héroes', 'Blizzard', 'Equipos', 'Habilidades'] },
  { p: 'Apex Legends', c: 'Videojuegos', x: ['Battle Royale', 'Leyendas', 'Shooter', 'Escuadrón', 'EA'] },
  { p: 'Rocket League', c: 'Videojuegos', x: ['Autos', 'Fútbol', 'Pelota gigante', 'Cohetes', 'Goles'] },
  { p: 'Fall Guys', c: 'Videojuegos', x: ['Muñecos', 'Obstáculos', 'Caerse', 'Colores', 'Corona'] },
  { p: 'Stardew Valley', c: 'Videojuegos', x: ['Granja', 'Cultivar', 'Pixel', 'Pueblo', 'Relajante'] },
  { p: 'Hollow Knight', c: 'Videojuegos', x: ['Insecto', 'Cueva', 'Difícil', 'Indie', 'Aguijón'] },
  { p: 'Terraria', c: 'Videojuegos', x: ['Cavar', '2D', 'Construir', 'Pixel', 'Jefes'] },
  { p: 'Pinball', c: 'Videojuegos', x: ['Bolita', 'Máquina', 'Flippers', 'Puntos', 'Rebotar'] },
  { p: 'Solitario', c: 'Videojuegos', x: ['Cartas', 'Windows', 'Solo', 'Ordenar', 'Palos'] },
  { p: 'Dota', c: 'Videojuegos', x: ['MOBA', 'Estrategia', 'Equipos', 'Valve', 'Torres'] },
  { p: 'Rust', c: 'Videojuegos', x: ['Supervivencia', 'Construir', 'Online', 'Recursos', 'PvP'] },
  { p: 'Sea of Thieves', c: 'Videojuegos', x: ['Piratas', 'Barcos', 'Tesoros', 'Mar', 'Online'] },
  { p: 'Undertale', c: 'Videojuegos', x: ['Indie', 'Pixel', 'Sans', 'Perdonar', 'Historia'] },
  { p: 'Cuphead', c: 'Videojuegos', x: ['Taza', 'Dibujo antiguo', 'Difícil', 'Jefes', 'Años 30'] },
  { p: 'Gran Turismo', c: 'Videojuegos', x: ['Autos', 'Carreras', 'Simulador', 'PlayStation', 'Realista'] },
  // Deportes
  { p: 'Handball', c: 'Deportes', x: ['Pelota', 'Manos', 'Arco', 'Equipo', 'Cancha'] },
  { p: 'Bádminton', c: 'Deportes', x: ['Raqueta', 'Pluma', 'Red', 'Volante', 'Volar'] },
  { p: 'Ping pong', c: 'Deportes', x: ['Paleta', 'Mesa', 'Pelotita', 'Red', 'Tenis de mesa'] },
  { p: 'Waterpolo', c: 'Deportes', x: ['Agua', 'Pileta', 'Pelota', 'Arco', 'Nadar'] },
  { p: 'Karate', c: 'Deportes', x: ['Cinturón', 'Patada', 'Kimono', 'Golpes', 'Japón'] },
  { p: 'Judo', c: 'Deportes', x: ['Cinturón', 'Llaves', 'Tatami', 'Japón', 'Derribar'] },
  { p: 'Atletismo', c: 'Deportes', x: ['Pista', 'Correr', 'Saltar', 'Olimpiadas', 'Medallas'] },
  { p: 'Remo', c: 'Deportes', x: ['Bote', 'Río', 'Palas', 'Equipo', 'Agua'] },
  { p: 'Escalada', c: 'Deportes', x: ['Pared', 'Montaña', 'Agarres', 'Cuerda', 'Trepar'] },
  { p: 'Patinaje', c: 'Deportes', x: ['Hielo', 'Ruedas', 'Girar', 'Deslizar', 'Piruetas'] },
  { p: 'Motociclismo', c: 'Deportes', x: ['Moto', 'Casco', 'Velocidad', 'Circuito', 'Curvas'] },
  { p: 'Snowboard', c: 'Deportes', x: ['Nieve', 'Tabla', 'Montaña', 'Saltos', 'Invierno'] },
  { p: 'Buceo', c: 'Deportes', x: ['Agua', 'Tanque', 'Profundo', 'Mar', 'Peces'] },
  { p: 'Polo', c: 'Deportes', x: ['Caballo', 'Taco', 'Bocha', 'Equipo', 'Cancha'] },
  { p: 'Halterofilia', c: 'Deportes', x: ['Pesas', 'Levantar', 'Fuerza', 'Barra', 'Olimpiadas'] },
  // Objetos
  { p: 'Peine', c: 'Objetos', x: ['Pelo', 'Púas', 'Peinar', 'Baño', 'Dientes'] },
  { p: 'Tenedor', c: 'Objetos', x: ['Comer', 'Pinches', 'Cubierto', 'Pinchar', 'Plato'] },
  { p: 'Cuchara', c: 'Objetos', x: ['Comer', 'Sopa', 'Cubierto', 'Redonda', 'Revolver'] },
  { p: 'Cuchillo', c: 'Objetos', x: ['Cortar', 'Filo', 'Cubierto', 'Carne', 'Punta'] },
  { p: 'Plato', c: 'Objetos', x: ['Comer', 'Redondo', 'Mesa', 'Cerámica', 'Lavar'] },
  { p: 'Taza', c: 'Objetos', x: ['Café', 'Asa', 'Caliente', 'Té', 'Mate cocido'] },
  { p: 'Botella', c: 'Objetos', x: ['Agua', 'Tapa', 'Vidrio', 'Líquido', 'Pico'] },
  { p: 'Peluche', c: 'Objetos', x: ['Suave', 'Osito', 'Juguete', 'Abrazar', 'Relleno'] },
  { p: 'Sombrero', c: 'Objetos', x: ['Cabeza', 'Sol', 'Ala', 'Gorra', 'Tapar'] },
  { p: 'Guantes', c: 'Objetos', x: ['Manos', 'Frío', 'Dedos', 'Invierno', 'Cuero'] },
  { p: 'Cinturón', c: 'Objetos', x: ['Cintura', 'Pantalón', 'Hebilla', 'Cuero', 'Ajustar'] },
  { p: 'Balde', c: 'Objetos', x: ['Agua', 'Manija', 'Baldear', 'Plástico', 'Arena'] },
  { p: 'Escalera', c: 'Objetos', x: ['Subir', 'Peldaños', 'Altura', 'Pintor', 'Bajar'] },
  { p: 'Cámara de fotos', c: 'Objetos', x: ['Foto', 'Lente', 'Flash', 'Retrato', 'Clic'] },
  { p: 'Termo', c: 'Objetos', x: ['Agua caliente', 'Mate', 'Tapa', 'Conservar', 'Acero'] },
  // Lugares
  { p: 'Baño', c: 'Lugares', x: ['Inodoro', 'Ducha', 'Lavarse', 'Papel', 'Espejo'] },
  { p: 'Cocina', c: 'Lugares', x: ['Cocinar', 'Heladera', 'Horno', 'Ollas', 'Comida'] },
  { p: 'Cárcel', c: 'Lugares', x: ['Presos', 'Rejas', 'Celda', 'Guardias', 'Condena'] },
  { p: 'Banco', c: 'Lugares', x: ['Dinero', 'Cajero', 'Cuenta', 'Fila', 'Préstamo'] },
  { p: 'Teatro', c: 'Lugares', x: ['Escenario', 'Obra', 'Actores', 'Telón', 'Aplausos'] },
  { p: 'Circo', c: 'Lugares', x: ['Payaso', 'Carpa', 'Malabares', 'Trapecio', 'Animales'] },
  { p: 'Cataratas', c: 'Argentina', x: ['Agua', 'Caída', 'Iguazú', 'Ruido', 'Turistas'] },
  { p: 'Volcán', c: 'Lugares', x: ['Lava', 'Erupción', 'Montaña', 'Fuego', 'Ceniza'] },
  { p: 'Isla', c: 'Lugares', x: ['Mar', 'Náufrago', 'Arena', 'Palmeras', 'Rodeada de agua'] },
  { p: 'Montaña', c: 'Lugares', x: ['Alta', 'Nieve', 'Escalar', 'Cima', 'Cordillera'] },
  { p: 'Río', c: 'Lugares', x: ['Agua', 'Corriente', 'Pescar', 'Orilla', 'Puente'] },
  { p: 'Estadio', c: 'Lugares', x: ['Fútbol', 'Hinchada', 'Tribunas', 'Cancha', 'Recital'] },
  { p: 'Casino', c: 'Lugares', x: ['Apuestas', 'Ruleta', 'Fichas', 'Cartas', 'Las Vegas'] },
  { p: 'Shopping', c: 'Lugares', x: ['Compras', 'Locales', 'Escaleras mecánicas', 'Patio de comidas', 'Vidrieras'] },
  { p: 'Ciudad', c: 'Lugares', x: ['Edificios', 'Gente', 'Tránsito', 'Calles', 'Rascacielos'] },
  // Música y famosos
  { p: 'Saxofón', c: 'Música y famosos', x: ['Viento', 'Jazz', 'Dorado', 'Soplar', 'Lisa Simpson'] },
  { p: 'Bandoneón', c: 'Argentina', x: ['Tango', 'Fuelle', 'Argentina', 'Apretar', 'Piazzolla'] },
  { p: 'Arpa', c: 'Música y famosos', x: ['Cuerdas', 'Grande', 'Ángeles', 'Dedos', 'Clásica'] },
  { p: 'Xilófono', c: 'Música y famosos', x: ['Teclas', 'Palillos', 'Madera', 'Notas', 'Golpear'] },
  { p: 'Coldplay', c: 'Música y famosos', x: ['Banda', 'Chris Martin', 'Inglesa', 'Yellow', 'Estadios'] },
  { p: 'Ed Sheeran', c: 'Música y famosos', x: ['Pelirrojo', 'Guitarra', 'Inglés', 'Shape of You', 'Cantante'] },
  { p: 'Michael Bublé', c: 'Música y famosos', x: ['Crooner', 'Navidad', 'Canadiense', 'Swing', 'Romántico'] },
  { p: 'Los Auténticos Decadentes', c: 'Argentina', x: ['Banda', 'Argentina', 'Fiesta', 'Loco', 'Cumbia rock'] },
  { p: 'Ricardo Arjona', c: 'Música y famosos', x: ['Guatemala', 'Cantante', 'Romántico', 'Alto', 'Baladas'] },
  { p: 'Sandro', c: 'Argentina', x: ['Gitano', 'Argentina', 'Nenas', 'Ídolo', 'Caderas'] },
  { p: 'Gilda', c: 'Argentina', x: ['Cumbia', 'Santa', 'Argentina', 'Colectivo', 'No es mi despedida'] },
  { p: 'Rodrigo', c: 'Argentina', x: ['Cuarteto', 'Potro', 'Córdoba', 'Argentina', 'Ocho cuarenta'] },
  { p: 'Villancico', c: 'Música y famosos', x: ['Navidad', 'Cantar', 'Noche de paz', 'Pesebre', 'Diciembre'] },
  { p: 'Himno', c: 'Música y famosos', x: ['Nacional', 'Bandera', 'Escuela', 'De pie', 'Patria'] },
  { p: 'Batucada', c: 'Música y famosos', x: ['Tambores', 'Brasil', 'Carnaval', 'Ritmo', 'Percusión'] },
  // Acciones
  { p: 'Toser', c: 'Acciones', x: ['Garganta', 'Enfermo', 'Tapar la boca', 'Resfrío', 'Carraspeo'] },
  { p: 'Roncar', c: 'Acciones', x: ['Dormir', 'Ruido', 'Nariz', 'Noche', 'Molestar'] },
  { p: 'Nadar', c: 'Acciones', x: ['Agua', 'Pileta', 'Brazadas', 'Flotar', 'Mar'] },
  { p: 'Barrer', c: 'Acciones', x: ['Escoba', 'Piso', 'Suciedad', 'Limpiar', 'Basura'] },
  { p: 'Peinarse', c: 'Acciones', x: ['Pelo', 'Peine', 'Espejo', 'Prolijo', 'Cepillo'] },
  { p: 'Estudiar', c: 'Acciones', x: ['Libros', 'Examen', 'Escuela', 'Concentrarse', 'Apuntes'] },
  { p: 'Estirar', c: 'Acciones', x: ['Brazos', 'Cuerpo', 'Elongar', 'Gimnasia', 'Músculos'] },
  { p: 'Aplastar', c: 'Acciones', x: ['Pisar', 'Fuerza', 'Chato', 'Insecto', 'Mano'] },
  { p: 'Empujar', c: 'Acciones', x: ['Fuerza', 'Puerta', 'Adelante', 'Mano', 'Tirar'] },
  { p: 'Trepar', c: 'Acciones', x: ['Subir', 'Árbol', 'Escalar', 'Manos', 'Altura'] },
  { p: 'Soplar', c: 'Acciones', x: ['Aire', 'Boca', 'Velitas', 'Viento', 'Globo'] },
  { p: 'Masticar', c: 'Acciones', x: ['Comida', 'Dientes', 'Boca', 'Chicle', 'Tragar'] },
  { p: 'Tejer', c: 'Acciones', x: ['Lana', 'Agujas', 'Abuela', 'Bufanda', 'Puntos'] },
  { p: 'Rezar', c: 'Acciones', x: ['Dios', 'Iglesia', 'Manos', 'Oración', 'Rodillas'] },
  { p: 'Guiñar', c: 'Acciones', x: ['Ojo', 'Complicidad', 'Cerrar', 'Coqueto', 'Seña'] },

  // ── Argentina (nuevas) ──
  { p: 'Fernet', c: 'Argentina', x: ['Con coca', 'Amargo', 'Previa', 'Marrón', 'Branca'] },
  { p: 'Bondi', c: 'Argentina', x: ['Colectivo', 'SUBE', 'Chofer', 'Parada', 'Ciudad'] },
  { p: 'Che', c: 'Argentina', x: ['Muletilla', 'Boludo', 'Guevara', 'Saludo', 'Argentino'] },
  { p: 'Boludo', c: 'Argentina', x: ['Insulto', 'Cariñoso', 'Che', 'Amigo', 'Argentino'] },
  { p: 'Quilombo', c: 'Argentina', x: ['Lío', 'Desorden', 'Caos', 'Problema', 'Bardo'] },
  { p: 'Parrilla', c: 'Argentina', x: ['Asado', 'Carne', 'Brasas', 'Domingo', 'Fierros'] },
  { p: 'Gaucho', c: 'Argentina', x: ['Campo', 'Caballo', 'Boina', 'Facón', 'Martín Fierro'] },
  { p: 'Tereré', c: 'Argentina', x: ['Yerba', 'Frío', 'Litoral', 'Jugo', 'Bombilla'] },
  { p: 'Colectivo', c: 'Argentina', x: ['Bondi', 'Chofer', 'Pasaje', 'Parada', 'Línea'] },
  { p: 'Subte', c: 'Argentina', x: ['Buenos Aires', 'Subterráneo', 'Estación', 'Línea', 'Tren'] },
  { p: 'Obelisco', c: 'Argentina', x: ['Buenos Aires', 'Monumento', '9 de Julio', 'Punta', 'Festejos'] },
  { p: 'Casa Rosada', c: 'Argentina', x: ['Gobierno', 'Presidente', 'Balcón', 'Plaza de Mayo', 'Rosa'] },
  { p: 'La Bombonera', c: 'Argentina', x: ['Boca', 'Cancha', 'Estadio', 'La Boca', 'Tribuna'] },
  { p: 'El Monumental', c: 'Argentina', x: ['River', 'Cancha', 'Estadio', 'Núñez', 'Mundial 78'] },
  { p: 'Selección Argentina', c: 'Argentina', x: ['Fútbol', 'Celeste y blanco', 'Scaloni', 'Copa', 'Messi'] },
  { p: 'Copa del Mundo', c: 'Argentina', x: ['Mundial', 'Qatar', 'Trofeo', 'Selección', 'Dorada'] },
  { p: 'Evita', c: 'Argentina', x: ['Perón', 'Primera dama', 'Descamisados', 'Balcón', 'Musical'] },
  { p: 'Perón', c: 'Argentina', x: ['Presidente', 'Justicialismo', 'Evita', 'Descamisados', 'General'] },
  { p: 'Gardel', c: 'Argentina', x: ['Tango', 'Cada día canta mejor', 'Zorzal', 'Sonríe', 'Cantor'] },
  { p: 'Quino', c: 'Argentina', x: ['Mafalda', 'Historietista', 'Humor', 'Dibujante', 'Mendoza'] },
  { p: 'Les Luthiers', c: 'Argentina', x: ['Humor', 'Música', 'Instrumentos', 'Grupo', 'Ingenio'] },
  { p: 'Capusotto', c: 'Argentina', x: ['Humor', 'Peter', 'Bombita Rodríguez', 'Televisión', 'Personajes'] },
  { p: 'Gran Hermano', c: 'Argentina', x: ['Reality', 'Casa', 'Placa', 'Eliminado', 'Cámaras'] },
  { p: 'MasterChef Argentina', c: 'Argentina', x: ['Cocina', 'Concurso', 'Jurado', 'Delantal', 'Televisión'] },
  { p: 'Patagonia', c: 'Argentina', x: ['Sur', 'Frío', 'Glaciares', 'Ballenas', 'Ushuaia'] },
  { p: 'Bariloche', c: 'Argentina', x: ['Chocolate', 'Sur', 'Lago', 'Cerro', 'Egresados'] },
  { p: 'Mar del Plata', c: 'Argentina', x: ['Playa', 'Costa', 'Verano', 'Lobos marinos', 'La Feliz'] },
  { p: 'Glaciar Perito Moreno', c: 'Argentina', x: ['Hielo', 'Santa Cruz', 'Ruptura', 'Calafate', 'Turismo'] },
  { p: 'Quebrada de Humahuaca', c: 'Argentina', x: ['Jujuy', 'Cerros de colores', 'Norte', 'Quebrada', 'Coya'] },
  { p: 'Vino Malbec', c: 'Argentina', x: ['Mendoza', 'Uva', 'Tinto', 'Copa', 'Bodega'] },
  { p: 'Yerba mate', c: 'Argentina', x: ['Mate', 'Bombilla', 'Verde', 'Termo', 'Infusión'] },
  { p: 'Chimichurri', c: 'Argentina', x: ['Asado', 'Salsa', 'Ajo', 'Perejil', 'Aceite'] },
  { p: 'Provoleta', c: 'Argentina', x: ['Queso', 'Parrilla', 'Provolone', 'Derretido', 'Orégano'] },
  { p: 'Cortado', c: 'Argentina', x: ['Café', 'Leche', 'Bar', 'Pocillo', 'Media tarde'] },
  { p: 'Submarino', c: 'Argentina', x: ['Leche caliente', 'Chocolate', 'Barra', 'Merienda', 'Revolver'] },
  { p: 'Guardapolvo', c: 'Argentina', x: ['Blanco', 'Escuela', 'Delantal', 'Alumnos', 'Primaria'] },
  { p: 'Ruta 40', c: 'Argentina', x: ['Camino', 'Cordillera', 'Larga', 'Norte a sur', 'Viaje'] },
  { p: 'Peña', c: 'Argentina', x: ['Folclore', 'Guitarra', 'Empanadas', 'Baile', 'Norte'] },
  // ── Animales (nuevas) ──
  { p: 'Foca', c: 'Animales', x: ['Mar', 'Hielo', 'Aplaudir', 'Pelota', 'Bigotes'] },
  { p: 'Koala', c: 'Animales', x: ['Australia', 'Eucalipto', 'Árbol', 'Dormir', 'Orejas'] },
  { p: 'Panda', c: 'Animales', x: ['China', 'Bambú', 'Blanco y negro', 'Oso', 'Perezoso'] },
  { p: 'Flamenco', c: 'Animales', x: ['Rosa', 'Una pata', 'Ave', 'Laguna', 'Cuello'] },
  { p: 'Pavo real', c: 'Animales', x: ['Plumas', 'Colores', 'Abanico', 'Ave', 'Presumido'] },
  { p: 'Erizo', c: 'Animales', x: ['Púas', 'Bolita', 'Espinas', 'Sonic', 'Pinchar'] },
  { p: 'Camaleón', c: 'Animales', x: ['Colores', 'Cambiar', 'Lengua', 'Reptil', 'Ojos'] },
  { p: 'Cangrejo', c: 'Animales', x: ['Pinzas', 'Playa', 'De costado', 'Rojo', 'Mar'] },
  { p: 'Caracol', c: 'Animales', x: ['Lento', 'Baba', 'Concha', 'Antenas', 'Jardín'] },
  { p: 'Ratón', c: 'Animales', x: ['Queso', 'Cola', 'Chiquito', 'Gato', 'Ratonera'] },
  { p: 'Buitre', c: 'Animales', x: ['Carroña', 'Ave', 'Pelado', 'Desierto', 'Muerte'] },
  { p: 'Pantera', c: 'Animales', x: ['Negra', 'Felino', 'Selva', 'Rosa', 'Sigilo'] },
  { p: 'Hipopótamo', c: 'Animales', x: ['Río', 'Grande', 'Bostezo', 'África', 'Gordo'] },
  { p: 'Avestruz', c: 'Animales', x: ['Corre', 'Cabeza', 'Huevo grande', 'Ave', 'No vuela'] },
  { p: 'Escarabajo', c: 'Animales', x: ['Insecto', 'Caparazón', 'Bolita', 'Negro', 'Volkswagen'] },
  { p: 'Pez espada', c: 'Animales', x: ['Mar', 'Nariz larga', 'Pescado', 'Filoso', 'Nadar'] },
  // ── Comida (nuevas) ──
  { p: 'Waffle', c: 'Comida', x: ['Cuadrados', 'Dulce', 'Miel', 'Desayuno', 'Bélgica'] },
  { p: 'Donut', c: 'Comida', x: ['Rosquilla', 'Agujero', 'Glaseado', 'Homero', 'Dulce'] },
  { p: 'Croissant', c: 'Comida', x: ['Media luna', 'Francia', 'Manteca', 'Hojaldre', 'Desayuno'] },
  { p: 'Pan', c: 'Comida', x: ['Panadería', 'Miga', 'Harina', 'Cortar', 'Migas'] },
  { p: 'Manteca', c: 'Comida', x: ['Untar', 'Pan', 'Amarilla', 'Vaca', 'Tostada'] },
  { p: 'Mermelada', c: 'Comida', x: ['Fruta', 'Dulce', 'Untar', 'Frasco', 'Tostada'] },
  { p: 'Cereal', c: 'Comida', x: ['Desayuno', 'Leche', 'Copos', 'Caja', 'Crujiente'] },
  { p: 'Galletitas', c: 'Comida', x: ['Paquete', 'Dulces', 'Té', 'Redondas', 'Mojar'] },
  { p: 'Pastel de papa', c: 'Comida', x: ['Carne', 'Puré', 'Horno', 'Gratinado', 'Capas'] },
  { p: 'Guiso', c: 'Comida', x: ['Olla', 'Invierno', 'Caliente', 'Fideos', 'Cuchara'] },
  { p: 'Polenta', c: 'Comida', x: ['Maíz', 'Amarilla', 'Cremosa', 'Salsa', 'Italiana'] },
  { p: 'Tarta de manzana', c: 'Comida', x: ['Postre', 'Masa', 'Canela', 'Horno', 'Fruta'] },
  { p: 'Brownie', c: 'Comida', x: ['Chocolate', 'Cuadrado', 'Nueces', 'Postre', 'Húmedo'] },
  { p: 'Cheesecake', c: 'Comida', x: ['Queso', 'Torta', 'Frutos rojos', 'Base', 'Postre'] },
  { p: 'Papas noisette', c: 'Comida', x: ['Papa', 'Bolitas', 'Fritas', 'Horno', 'Doradas'] },
  { p: 'Chicle', c: 'Comida', x: ['Masticar', 'Globo', 'Dulce', 'Menta', 'Pegajoso'] },
  // ── Cine y series (nuevas) ──
  { p: 'Lost', c: 'Cine y series', x: ['Isla', 'Avión', 'Misterio', 'Náufragos', 'Humo'] },
  { p: 'Prison Break', c: 'Cine y series', x: ['Cárcel', 'Escape', 'Tatuaje', 'Hermanos', 'Plan'] },
  { p: 'The Walking Dead', c: 'Cine y series', x: ['Zombis', 'Apocalipsis', 'Rick', 'Sobrevivir', 'Caminantes'] },
  { p: 'Better Call Saul', c: 'Cine y series', x: ['Abogado', 'Breaking Bad', 'Saul', 'Precuela', 'Estafas'] },
  { p: 'Euphoria', c: 'Cine y series', x: ['Adolescentes', 'Zendaya', 'Fiestas', 'HBO', 'Brillos'] },
  { p: 'Wandavision', c: 'Cine y series', x: ['Marvel', 'Bruja', 'Sitcom', 'Realidad', 'Disney'] },
  { p: 'The Crown', c: 'Cine y series', x: ['Reina', 'Inglaterra', 'Corona', 'Realeza', 'Netflix'] },
  { p: 'Bridgerton', c: 'Cine y series', x: ['Época', 'Romance', 'Inglaterra', 'Chismes', 'Netflix'] },
  { p: 'Narcos', c: 'Cine y series', x: ['Pablo Escobar', 'Colombia', 'Droga', 'Capo', 'Netflix'] },
  { p: 'Los Padrinos Mágicos', c: 'Cine y series', x: ['Dibujito', 'Deseos', 'Hadas', 'Timmy', 'Verde y rosa'] },
  { p: 'Ben 10', c: 'Cine y series', x: ['Reloj', 'Alienígenas', 'Transformar', 'Niño', 'Dibujito'] },
  { p: 'Hora de Aventura', c: 'Cine y series', x: ['Finn', 'Jake', 'Perro', 'Dibujito', 'Ooo'] },
  { p: 'South Park', c: 'Cine y series', x: ['Animada', 'Cartman', 'Pueblo', 'Groseros', 'Niños'] },
  { p: 'Padre de Familia', c: 'Cine y series', x: ['Animada', 'Peter', 'Bebé', 'Perro', 'Griffin'] },
  { p: 'The Last of Us (serie)', c: 'Cine y series', x: ['Hongos', 'Apocalipsis', 'Joel', 'Ellie', 'HBO'] },
  { p: 'Fundación', c: 'Cine y series', x: ['Espacio', 'Ciencia ficción', 'Imperio', 'Apple', 'Futuro'] },
  // ── Películas (nuevas) ──
  { p: 'Titanic', c: 'Películas', x: ['Barco', 'Iceberg', 'DiCaprio', 'Hundirse', 'Corazón del océano'] },
  { p: 'El Gran Gatsby', c: 'Películas', x: ['Fiestas', 'DiCaprio', 'Años 20', 'Rico', 'Verde'] },
  { p: 'Django', c: 'Películas', x: ['Tarantino', 'Esclavo', 'Vaquero', 'Venganza', 'Látigo'] },
  { p: 'El Caballero de la Noche', c: 'Películas', x: ['Batman', 'Guasón', 'Gotham', 'Nolan', 'Héroe'] },
  { p: 'Spider-Man: Un Nuevo Universo', c: 'Películas', x: ['Araña', 'Animada', 'Miles', 'Multiverso', 'Colores'] },
  { p: 'Sing', c: 'Películas', x: ['Animales', 'Cantar', 'Concurso', 'Koala', 'Escenario'] },
  { p: 'Bee Movie', c: 'Películas', x: ['Abeja', 'Miel', 'Juicio', 'Amarillo', 'Animada'] },
  { p: 'Río', c: 'Películas', x: ['Guacamayo', 'Brasil', 'Azul', 'Carnaval', 'Animada'] },
  { p: 'Trolls', c: 'Películas', x: ['Pelo', 'Colores', 'Cantar', 'Muñecos', 'Abrazos'] },
  { p: 'Hotel Transylvania', c: 'Películas', x: ['Drácula', 'Monstruos', 'Hotel', 'Animada', 'Halloween'] },
  { p: 'Cómo Entrenar a tu Dragón', c: 'Películas', x: ['Vikingo', 'Dragón', 'Chimuelo', 'Volar', 'Amistad'] },
  { p: 'Escuadrón Suicida', c: 'Películas', x: ['Villanos', 'DC', 'Harley Quinn', 'Equipo', 'Bomba'] },
  { p: 'Sonic la Película', c: 'Películas', x: ['Erizo', 'Azul', 'Velocidad', 'Anillos', 'Jim Carrey'] },
  { p: 'Mamma Mia', c: 'Películas', x: ['ABBA', 'Grecia', 'Musical', 'Boda', 'Isla'] },
  // ── Actores y famosos (nuevas) ──
  { p: 'Chris Hemsworth', c: 'Actores y famosos', x: ['Thor', 'Martillo', 'Rubio', 'Australiano', 'Músculos'] },
  { p: 'Chris Evans', c: 'Actores y famosos', x: ['Capitán América', 'Escudo', 'Marvel', 'Actor', 'Rubio'] },
  { p: 'Ryan Reynolds', c: 'Actores y famosos', x: ['Deadpool', 'Rojo', 'Chistes', 'Actor', 'Canadiense'] },
  { p: 'Gal Gadot', c: 'Actores y famosos', x: ['Mujer Maravilla', 'Actriz', 'Israel', 'Lazo', 'DC'] },
  { p: 'Timothée Chalamet', c: 'Actores y famosos', x: ['Actor', 'Duna', 'Wonka', 'Rulos', 'Joven'] },
  { p: 'Jennifer Lawrence', c: 'Actores y famosos', x: ['Katniss', 'Actriz', 'Oscar', 'X-Men', 'Rubia'] },
  { p: 'Sandra Bullock', c: 'Actores y famosos', x: ['Actriz', 'Gravity', 'Miss Simpatía', 'Hollywood', 'Comedia'] },
  { p: 'Cameron Diaz', c: 'Actores y famosos', x: ['Actriz', 'Rubia', 'Shrek', 'La Máscara', 'Sonrisa'] },
  { p: 'Hugh Jackman', c: 'Actores y famosos', x: ['Wolverine', 'Garras', 'Actor', 'Australiano', 'Musical'] },
  { p: 'Samuel L. Jackson', c: 'Actores y famosos', x: ['Actor', 'Nick Fury', 'Pulp Fiction', 'Parche', 'Marvel'] },
  { p: 'Vin Diesel', c: 'Actores y famosos', x: ['Rápido y Furioso', 'Pelado', 'Groot', 'Familia', 'Voz'] },
  { p: 'Jason Statham', c: 'Actores y famosos', x: ['Acción', 'Pelado', 'Inglés', 'Peleas', 'Autos'] },
  { p: 'Chris Pratt', c: 'Actores y famosos', x: ['Guardianes', 'Actor', 'Jurassic', 'Star-Lord', 'Comedia'] },
  { p: 'Florence Pugh', c: 'Actores y famosos', x: ['Actriz', 'Marvel', 'Rubia', 'Midsommar', 'Inglesa'] },
  // ── Personajes (nuevas) ──
  { p: 'Baby Yoda', c: 'Personajes', x: ['Mandalorian', 'Verde', 'Orejas', 'Bebé', 'Fuerza'] },
  { p: 'Chewbacca', c: 'Personajes', x: ['Star Wars', 'Peludo', 'Rugido', 'Han Solo', 'Nave'] },
  { p: 'R2-D2', c: 'Personajes', x: ['Star Wars', 'Robot', 'Pitidos', 'Azul y blanco', 'Droide'] },
  { p: 'Baymax', c: 'Personajes', x: ['Robot', 'Inflable', 'Blanco', 'Salud', 'Abrazo'] },
  { p: 'Eleven', c: 'Personajes', x: ['Stranger Things', 'Poderes', 'Once', 'Nariz', 'Eggos'] },
  { p: 'Geralt', c: 'Personajes', x: ['The Witcher', 'Brujo', 'Espada', 'Blanco', 'Monstruos'] },
  { p: 'Kratos', c: 'Personajes', x: ['God of War', 'Hacha', 'Dios', 'Enojado', 'Barba roja'] },
  { p: 'Sub-Zero', c: 'Personajes', x: ['Mortal Kombat', 'Hielo', 'Ninja', 'Azul', 'Máscara'] },
  { p: 'Scorpion', c: 'Personajes', x: ['Mortal Kombat', 'Fuego', 'Amarillo', 'Ven aquí', 'Ninja'] },
  { p: 'Ryu', c: 'Personajes', x: ['Street Fighter', 'Hadouken', 'Karate', 'Cinta', 'Blanco'] },
  { p: 'Shadow', c: 'Personajes', x: ['Sonic', 'Negro', 'Erizo', 'Rojo', 'Rival'] },
  { p: 'Arnold', c: 'Personajes', x: ['Oye Arnold', 'Cabeza', 'Gorra', 'Dibujito', 'Fútbol'] },
  { p: 'Johnny Bravo', c: 'Personajes', x: ['Rubio', 'Músculos', 'Jopo', 'Presumido', 'Dibujito'] },
  { p: 'Coraje', c: 'Personajes', x: ['Perro', 'Cobarde', 'Rosa', 'Miedo', 'Granja'] },
  // ── Videojuegos (nuevas) ──
  { p: 'Splatoon', c: 'Videojuegos', x: ['Tinta', 'Calamares', 'Colores', 'Nintendo', 'Pintar'] },
  { p: 'Animal Crossing', c: 'Videojuegos', x: ['Isla', 'Aldeanos', 'Nintendo', 'Tom Nook', 'Relajante'] },
  { p: 'Kingdom Hearts', c: 'Videojuegos', x: ['Disney', 'Sora', 'Llave', 'Corazones', 'RPG'] },
  { p: 'Devil May Cry', c: 'Videojuegos', x: ['Dante', 'Demonios', 'Espada', 'Estiloso', 'Capcom'] },
  { p: 'Monster Hunter', c: 'Videojuegos', x: ['Cazar', 'Monstruos', 'Armas', 'Capcom', 'Equipo'] },
  { p: 'Ori', c: 'Videojuegos', x: ['Indie', 'Espíritu', 'Bosque', 'Plataformas', 'Blanco'] },
  { p: 'Celeste', c: 'Videojuegos', x: ['Montaña', 'Indie', 'Escalar', 'Pixel', 'Difícil'] },
  { p: 'It Takes Two', c: 'Videojuegos', x: ['Cooperativo', 'Pareja', 'Dos', 'Aventura', 'Muñecos'] },
  { p: 'Baldurs Gate', c: 'Videojuegos', x: ['RPG', 'Dados', 'Aventura', 'Magia', 'Dragones'] },
  { p: 'Forza', c: 'Videojuegos', x: ['Autos', 'Carreras', 'Xbox', 'Simulador', 'Velocidad'] },
  { p: 'Gears of War', c: 'Videojuegos', x: ['Shooter', 'Xbox', 'Motosierra', 'Guerra', 'Cobertura'] },
  { p: 'Uncharted', c: 'Videojuegos', x: ['Nathan Drake', 'Tesoros', 'Aventura', 'PlayStation', 'Escalar'] },
  { p: 'Horizon', c: 'Videojuegos', x: ['Aloy', 'Robots', 'Dinosaurios mecánicos', 'Arco', 'PlayStation'] },
  { p: 'Ghost of Tsushima', c: 'Videojuegos', x: ['Samurái', 'Japón', 'Espada', 'Isla', 'PlayStation'] },
  { p: 'Palworld', c: 'Videojuegos', x: ['Criaturas', 'Atrapar', 'Supervivencia', 'Armas', 'Indie'] },
  { p: 'Vampire Survivors', c: 'Videojuegos', x: ['Indie', 'Oleadas', 'Pixel', 'Automático', 'Sobrevivir'] },
  // ── Deportes (nuevas) ──
  { p: 'Béisbol', c: 'Deportes', x: ['Bate', 'Pelota', 'Home run', 'Guante', 'Estados Unidos'] },
  { p: 'Cricket', c: 'Deportes', x: ['Bate', 'India', 'Wicket', 'Inglés', 'Pelota'] },
  { p: 'Fútbol americano', c: 'Deportes', x: ['Casco', 'Ovalada', 'Touchdown', 'NFL', 'Placar'] },
  { p: 'Sóftbol', c: 'Deportes', x: ['Pelota grande', 'Bate', 'Guante', 'Bases', 'Béisbol'] },
  { p: 'Lucha libre', c: 'Deportes', x: ['Máscaras', 'Ring', 'México', 'Llaves', 'Show'] },
  { p: 'Taekwondo', c: 'Deportes', x: ['Patadas', 'Cinturón', 'Corea', 'Artes marciales', 'Tablas'] },
  { p: 'Squash', c: 'Deportes', x: ['Raqueta', 'Pared', 'Pelotita', 'Cancha cerrada', 'Rebote'] },
  { p: 'Curling', c: 'Deportes', x: ['Hielo', 'Piedra', 'Escoba', 'Barrer', 'Blanco'] },
  { p: 'Triatlón', c: 'Deportes', x: ['Nadar', 'Ciclismo', 'Correr', 'Tres', 'Resistencia'] },
  { p: 'Salto en alto', c: 'Deportes', x: ['Vara', 'Saltar', 'Colchoneta', 'Atletismo', 'Altura'] },
  { p: 'Salto en largo', c: 'Deportes', x: ['Correr', 'Saltar', 'Arena', 'Distancia', 'Atletismo'] },
  { p: 'Lanzamiento de bala', c: 'Deportes', x: ['Pesada', 'Tirar', 'Atletismo', 'Bola', 'Fuerza'] },
  { p: 'Parkour', c: 'Deportes', x: ['Saltar', 'Techos', 'Obstáculos', 'Ciudad', 'Acrobacias'] },
  { p: 'Kitesurf', c: 'Deportes', x: ['Cometa', 'Viento', 'Tabla', 'Mar', 'Volar'] },
  { p: 'Automovilismo', c: 'Deportes', x: ['Autos', 'Circuito', 'Carrera', 'Piloto', 'Velocidad'] },
  { p: 'Dardos', c: 'Deportes', x: ['Diana', 'Puntería', 'Bar', 'Tirar', 'Centro'] },
  // ── Objetos (nuevas) ──
  { p: 'Abanico', c: 'Objetos', x: ['Aire', 'Calor', 'Abrir', 'Mano', 'España'] },
  { p: 'Lupa', c: 'Objetos', x: ['Aumentar', 'Ver', 'Detective', 'Vidrio', 'Sol'] },
  { p: 'Brújula', c: 'Objetos', x: ['Norte', 'Aguja', 'Orientarse', 'Mapa', 'Redonda'] },
  { p: 'Candado', c: 'Objetos', x: ['Llave', 'Cerrar', 'Cadena', 'Seguridad', 'Bici'] },
  { p: 'Enchufe', c: 'Objetos', x: ['Electricidad', 'Pared', 'Cargar', 'Corriente', 'Agujeros'] },
  { p: 'Pila', c: 'Objetos', x: ['Energía', 'Control', 'Doble A', 'Cargar', 'Reloj'] },
  { p: 'Imán', c: 'Objetos', x: ['Pegar', 'Metal', 'Heladera', 'Polos', 'Atraer'] },
  { p: 'Regla', c: 'Objetos', x: ['Medir', 'Centímetros', 'Recta', 'Escuela', 'Plástico'] },
  { p: 'Goma', c: 'Objetos', x: ['Borrar', 'Lápiz', 'Escuela', 'Rosa', 'Migas'] },
  { p: 'Termómetro', c: 'Objetos', x: ['Fiebre', 'Temperatura', 'Grados', 'Mercurio', 'Axila'] },
  { p: 'Balanza', c: 'Objetos', x: ['Peso', 'Kilos', 'Pesarse', 'Baño', 'Aguja'] },
  { p: 'Secador de pelo', c: 'Objetos', x: ['Aire caliente', 'Pelo', 'Enchufe', 'Ruido', 'Baño'] },
  { p: 'Plancha', c: 'Objetos', x: ['Ropa', 'Arrugas', 'Caliente', 'Vapor', 'Planchar'] },
  { p: 'Aspiradora', c: 'Objetos', x: ['Aspirar', 'Polvo', 'Alfombra', 'Ruido', 'Limpiar'] },
  { p: 'Sombrilla', c: 'Objetos', x: ['Playa', 'Sol', 'Sombra', 'Arena', 'Abrir'] },
  { p: 'Cartera', c: 'Objetos', x: ['Bolso', 'Mujer', 'Llaves', 'Hombro', 'Cosas'] },
  // ── Lugares (nuevas) ──
  { p: 'Bar', c: 'Lugares', x: ['Trago', 'Barra', 'Cerveza', 'Amigos', 'Noche'] },
  { p: 'Boliche', c: 'Lugares', x: ['Bailar', 'Noche', 'Música', 'Fiesta', 'Barra'] },
  { p: 'Panadería', c: 'Lugares', x: ['Pan', 'Facturas', 'Horno', 'Medialunas', 'Docena'] },
  { p: 'Farmacia', c: 'Lugares', x: ['Remedios', 'Salud', 'Receta', 'Cruz verde', 'Mostrador'] },
  { p: 'Comisaría', c: 'Lugares', x: ['Policía', 'Presos', 'Denuncia', 'Uniforme', 'Celda'] },
  { p: 'Universidad', c: 'Lugares', x: ['Estudiar', 'Carrera', 'Facultad', 'Profesor', 'Examen'] },
  { p: 'Estacionamiento', c: 'Lugares', x: ['Autos', 'Cochera', 'Ticket', 'Playa', 'Espacios'] },
  { p: 'Verdulería', c: 'Lugares', x: ['Frutas', 'Verduras', 'Cajón', 'Tomate', 'Balanza'] },
  { p: 'Kiosco', c: 'Lugares', x: ['Golosinas', 'Cigarrillos', 'Ventana', 'Barrio', 'Revistas'] },
  { p: 'Terminal de micros', c: 'Lugares', x: ['Colectivos', 'Viaje', 'Boletos', 'Andenes', 'Larga distancia'] },
  { p: 'Parque de diversiones', c: 'Lugares', x: ['Montaña rusa', 'Juegos', 'Algodón de azúcar', 'Vueltas', 'Entradas'] },
  { p: 'Camping', c: 'Lugares', x: ['Carpa', 'Naturaleza', 'Fogón', 'Bolsa de dormir', 'Bosque'] },
  { p: 'Oficina', c: 'Lugares', x: ['Trabajo', 'Escritorio', 'Computadora', 'Jefe', 'Reuniones'] },
  { p: 'Fábrica', c: 'Lugares', x: ['Producción', 'Máquinas', 'Obreros', 'Chimenea', 'Cinta'] },
  { p: 'Puerto', c: 'Lugares', x: ['Barcos', 'Mar', 'Contenedores', 'Muelle', 'Marineros'] },
  { p: 'Granja', c: 'Lugares', x: ['Animales', 'Campo', 'Vaca', 'Gallinas', 'Tractor'] },
  // ── Música y famosos (nuevas) ──
  { p: 'Guns N Roses', c: 'Música y famosos', x: ['Rock', 'Slash', 'Axl', 'Sweet Child', 'Banda'] },
  { p: 'Metallica', c: 'Música y famosos', x: ['Metal', 'Rock pesado', 'Banda', 'Enter Sandman', 'Guitarra'] },
  { p: 'AC/DC', c: 'Música y famosos', x: ['Rock', 'Australia', 'Thunderstruck', 'Cuernos', 'Colegial'] },
  { p: 'Nirvana', c: 'Música y famosos', x: ['Grunge', 'Kurt Cobain', 'Teen Spirit', 'Años 90', 'Banda'] },
  { p: 'Elton John', c: 'Música y famosos', x: ['Piano', 'Lentes', 'Inglés', 'Rocketman', 'Cantante'] },
  { p: 'Adele', c: 'Música y famosos', x: ['Voz', 'Inglesa', 'Baladas', 'Hello', 'Cantante'] },
  { p: 'Billie Eilish', c: 'Música y famosos', x: ['Cantante', 'Verde', 'Susurro', 'Joven', 'Pop'] },
  { p: 'The Weeknd', c: 'Música y famosos', x: ['Cantante', 'Blinding Lights', 'Canadiense', 'Falsete', 'Pop'] },
  { p: 'Daddy Yankee', c: 'Música y famosos', x: ['Reggaetón', 'Gasolina', 'Puerto Rico', 'Despacito', 'Rey'] },
  { p: 'J Balvin', c: 'Música y famosos', x: ['Reggaetón', 'Colombia', 'Colores', 'Mi Gente', 'Pelo'] },
  { p: 'Maluma', c: 'Música y famosos', x: ['Reggaetón', 'Colombia', 'Pretty Boy', 'Cantante', 'Tatuajes'] },
  { p: 'Ozuna', c: 'Música y famosos', x: ['Reggaetón', 'Puerto Rico', 'Voz aguda', 'Trap', 'Cantante'] },
  { p: 'Lady Gaga', c: 'Música y famosos', x: ['Cantante', 'Extravagante', 'Poker Face', 'Pop', 'Rubia'] },
  { p: 'Justin Bieber', c: 'Música y famosos', x: ['Canadiense', 'Baby', 'Cantante', 'Pop', 'Beliebers'] },
  // ── Acciones (nuevas) ──
  { p: 'Patear', c: 'Acciones', x: ['Pie', 'Pelota', 'Golpe', 'Fútbol', 'Puerta'] },
  { p: 'Trotar', c: 'Acciones', x: ['Correr suave', 'Ejercicio', 'Plaza', 'Piernas', 'Zapatillas'] },
  { p: 'Susurrar', c: 'Acciones', x: ['Bajo', 'Oído', 'Secreto', 'Voz', 'Bajito'] },
  { p: 'Tropezar', c: 'Acciones', x: ['Caer', 'Piedra', 'Pie', 'Torpe', 'Escalón'] },
  { p: 'Suspirar', c: 'Acciones', x: ['Aire', 'Amor', 'Cansancio', 'Boca', 'Alivio'] },
  { p: 'Temblar', c: 'Acciones', x: ['Frío', 'Miedo', 'Sacudir', 'Nervios', 'Terremoto'] },
  { p: 'Arrastrarse', c: 'Acciones', x: ['Piso', 'Gatear', 'Lento', 'Serpiente', 'Cuerpo'] },
  { p: 'Escupir', c: 'Acciones', x: ['Saliva', 'Boca', 'Lejos', 'Camello', 'Asco'] },
  { p: 'Parpadear', c: 'Acciones', x: ['Ojos', 'Rápido', 'Cerrar', 'Pestañas', 'Guiño'] },
  { p: 'Rascar', c: 'Acciones', x: ['Picazón', 'Uñas', 'Espalda', 'Mosquito', 'Piel'] },
  { p: 'Tironear', c: 'Acciones', x: ['Fuerza', 'Soga', 'Tirar', 'Manos', 'Cinchada'] },
  { p: 'Cortar', c: 'Acciones', x: ['Tijera', 'Cuchillo', 'Papel', 'Filo', 'Pedazos'] },
  { p: 'Pegar', c: 'Acciones', x: ['Golpear', 'Pelea', 'Mano', 'Cachetada', 'Puño'] },
  { p: 'Firmar', c: 'Acciones', x: ['Papel', 'Lapicera', 'Nombre', 'Contrato', 'Autógrafo'] },
];
