// Mazo de palabras — Decilo sin decirlo
// p: palabra, c: categoría, x: palabras prohibidas (solo para rondas de Taboo)
export interface Palabra {
  p: string;
  c: string;
  x: string[];
}

export const CATEGORIAS = [
  'Animales', 'Comida', 'Cine y series', 'Películas', 'Actores y famosos', 'Personajes',
  'Videojuegos', 'Deportes', 'Objetos', 'Lugares', 'Música y famosos', 'Acciones',
];

export const PALABRAS: Palabra[] = [
  // ── Animales ──
  { p: 'Elefante', c: 'Animales', x: ['Trompa', 'Grande', 'Gris', 'Orejas', 'África'] },
  { p: 'Pingüino', c: 'Animales', x: ['Frío', 'Hielo', 'Ave', 'Antártida', 'Blanco y negro'] },
  { p: 'Tiburón', c: 'Animales', x: ['Mar', 'Dientes', 'Aleta', 'Peligroso', 'Película'] },
  { p: 'Jirafa', c: 'Animales', x: ['Cuello', 'Alta', 'Manchas', 'África', 'Hojas'] },
  { p: 'Perro', c: 'Animales', x: ['Ladrar', 'Mascota', 'Hueso', 'Gato', 'Correa'] },
  { p: 'Gato', c: 'Animales', x: ['Maullar', 'Ratón', 'Mascota', 'Bigotes', 'Siete vidas'] },
  { p: 'Caballo', c: 'Animales', x: ['Montar', 'Galopar', 'Crin', 'Granja', 'Jinete'] },
  { p: 'Abeja', c: 'Animales', x: ['Miel', 'Picar', 'Amarillo', 'Volar', 'Panal'] },
  { p: 'Cocodrilo', c: 'Animales', x: ['Río', 'Dientes', 'Verde', 'Reptil', 'Lagarto'] },
  { p: 'Mono', c: 'Animales', x: ['Banana', 'Selva', 'Trepar', 'Cola', 'Simio'] },
  { p: 'Búho', c: 'Animales', x: ['Noche', 'Sabio', 'Plumas', 'Girar', 'Ave'] },
  { p: 'Tortuga', c: 'Animales', x: ['Caparazón', 'Lenta', 'Ninja', 'Mar', 'Vieja'] },
  { p: 'León', c: 'Animales', x: ['Rey', 'Selva', 'Melena', 'Rugir', 'Felino'] },
  { p: 'Canguro', c: 'Animales', x: ['Australia', 'Saltar', 'Bolsa', 'Cría', 'Boxeo'] },
  { p: 'Murciélago', c: 'Animales', x: ['Noche', 'Cueva', 'Volar', 'Batman', 'Colgado'] },
  { p: 'Pulpo', c: 'Animales', x: ['Ocho', 'Tentáculos', 'Mar', 'Tinta', 'Ventosas'] },
  { p: 'Loro', c: 'Animales', x: ['Repetir', 'Hablar', 'Verde', 'Pirata', 'Ave'] },
  { p: 'Hormiga', c: 'Animales', x: ['Chiquita', 'Trabajadora', 'Hormiguero', 'Fila', 'Picnic'] },
  { p: 'Vaca', c: 'Animales', x: ['Leche', 'Mugir', 'Campo', 'Manchas', 'Toro'] },
  { p: 'Serpiente', c: 'Animales', x: ['Veneno', 'Reptil', 'Arrastrarse', 'Cascabel', 'Lengua'] },
  { p: 'Oso', c: 'Animales', x: ['Miel', 'Hibernar', 'Polar', 'Panda', 'Peluche'] },
  // ── Comida ──
  { p: 'Pizza', c: 'Comida', x: ['Queso', 'Italiana', 'Porción', 'Muzzarella', 'Horno'] },
  { p: 'Asado', c: 'Comida', x: ['Parrilla', 'Carne', 'Fuego', 'Domingo', 'Costillas'] },
  { p: 'Empanada', c: 'Comida', x: ['Relleno', 'Masa', 'Carne', 'Horno', 'Repulgue'] },
  { p: 'Helado', c: 'Comida', x: ['Frío', 'Cucurucho', 'Sabor', 'Verano', 'Postre'] },
  { p: 'Hamburguesa', c: 'Comida', x: ['Pan', 'Carne', 'Queso', 'Comida rápida', 'Papas fritas'] },
  { p: 'Sushi', c: 'Comida', x: ['Japonés', 'Arroz', 'Pescado', 'Palitos', 'Alga'] },
  { p: 'Chocolate', c: 'Comida', x: ['Dulce', 'Cacao', 'Marrón', 'Tableta', 'Bombón'] },
  { p: 'Café', c: 'Comida', x: ['Taza', 'Despertar', 'Negro', 'Cafeína', 'Desayuno'] },
  { p: 'Sopa', c: 'Comida', x: ['Caliente', 'Cuchara', 'Plato', 'Líquido', 'Invierno'] },
  { p: 'Taco', c: 'Comida', x: ['México', 'Tortilla', 'Picante', 'Relleno', 'Carne'] },
  { p: 'Ensalada', c: 'Comida', x: ['Lechuga', 'Verduras', 'Tomate', 'Saludable', 'Aderezo'] },
  { p: 'Milanesa', c: 'Comida', x: ['Empanado', 'Napolitana', 'Carne', 'Frita', 'Puré'] },
  { p: 'Fideos', c: 'Comida', x: ['Pasta', 'Salsa', 'Italia', 'Tuco', 'Hervir'] },
  { p: 'Dulce de leche', c: 'Comida', x: ['Argentina', 'Marrón', 'Untar', 'Postre', 'Leche'] },
  { p: 'Mate', c: 'Comida', x: ['Yerba', 'Bombilla', 'Termo', 'Amargo', 'Argentina'] },
  { p: 'Torta', c: 'Comida', x: ['Cumpleaños', 'Velitas', 'Dulce', 'Porción', 'Bizcochuelo'] },
  { p: 'Pancho', c: 'Comida', x: ['Salchicha', 'Pan', 'Mostaza', 'Rápido', 'Cancha'] },
  { p: 'Huevo', c: 'Comida', x: ['Gallina', 'Frito', 'Yema', 'Cáscara', 'Revuelto'] },
  { p: 'Queso', c: 'Comida', x: ['Rallado', 'Vaca', 'Ratón', 'Agujeros', 'Lácteo'] },
  { p: 'Banana', c: 'Comida', x: ['Amarilla', 'Mono', 'Cáscara', 'Fruta', 'Resbalar'] },
  { p: 'Papas fritas', c: 'Comida', x: ['Aceite', 'Ketchup', 'Crujientes', 'Bastones', 'McDonalds'] },
  // ── Cine y series ──
  { p: 'Superhéroe', c: 'Cine y series', x: ['Capa', 'Poderes', 'Volar', 'Salvar', 'Villano'] },
  { p: 'Zombi', c: 'Cine y series', x: ['Muerto', 'Cerebro', 'Caminar', 'Virus', 'Terror'] },
  { p: 'Titanic', c: 'Cine y series', x: ['Barco', 'Hundirse', 'Iceberg', 'Leonardo', 'Amor'] },
  { p: 'Mago', c: 'Cine y series', x: ['Varita', 'Hechizo', 'Sombrero', 'Conejo', 'Magia'] },
  { p: 'Vampiro', c: 'Cine y series', x: ['Sangre', 'Colmillos', 'Noche', 'Ajo', 'Drácula'] },
  { p: 'Pochoclo', c: 'Cine y series', x: ['Maíz', 'Cine', 'Balde', 'Explotar', 'Película'] },
  { p: 'Director de cine', c: 'Cine y series', x: ['Película', 'Cámara', 'Acción', 'Rodar', 'Corte'] },
  { p: 'Premio Oscar', c: 'Cine y series', x: ['Estatua', 'Hollywood', 'Actor', 'Alfombra roja', 'Ganador'] },
  { p: 'Dinosaurio', c: 'Cine y series', x: ['Extinto', 'Fósil', 'Gigante', 'Prehistórico', 'Reptil'] },
  { p: 'Pirata', c: 'Cine y series', x: ['Barco', 'Parche', 'Tesoro', 'Loro', 'Espada'] },
  { p: 'Bruja', c: 'Cine y series', x: ['Escoba', 'Hechizo', 'Caldero', 'Sombrero', 'Magia'] },
  { p: 'Netflix', c: 'Cine y series', x: ['Series', 'Streaming', 'Maratón', 'Rojo', 'Suscripción'] },
  { p: 'Telenovela', c: 'Cine y series', x: ['Amor', 'Drama', 'Capítulos', 'Llorar', 'Villana'] },
  { p: 'Documental', c: 'Cine y series', x: ['Real', 'Naturaleza', 'Narrador', 'Historia', 'Educativo'] },
  { p: 'Dibujos animados', c: 'Cine y series', x: ['Niños', 'Televisión', 'Colores', 'Personajes', 'Animación'] },
  { p: 'Alfombra roja', c: 'Cine y series', x: ['Famosos', 'Vestidos', 'Fotógrafos', 'Premios', 'Caminar'] },
  { p: 'Extraterrestre', c: 'Cine y series', x: ['OVNI', 'Espacio', 'Verde', 'Platillo', 'Alien'] },
  { p: 'Robot', c: 'Cine y series', x: ['Máquina', 'Metal', 'Futuro', 'Inteligencia artificial', 'Programar'] },
  { p: 'Fantasma', c: 'Cine y series', x: ['Sábana', 'Casa embrujada', 'Boo', 'Aparecer', 'Miedo'] },
  { p: 'Payaso', c: 'Cine y series', x: ['Circo', 'Nariz roja', 'Risa', 'Maquillaje', 'Globos'] },
  { p: 'Cámara oculta', c: 'Cine y series', x: ['Broma', 'Filmar', 'Sorpresa', 'Reír', 'Televisión'] },
  // ── Películas ──
  { p: 'El Rey León', c: 'Películas', x: ['Simba', 'África', 'Hakuna Matata', 'Disney', 'Selva'] },
  { p: 'Toy Story', c: 'Películas', x: ['Juguetes', 'Woody', 'Buzz', 'Pixar', 'Vaquero'] },
  { p: 'Harry Potter', c: 'Películas', x: ['Mago', 'Varita', 'Hogwarts', 'Anteojos', 'Cicatriz'] },
  { p: 'Jurassic Park', c: 'Películas', x: ['Dinosaurios', 'Parque', 'Isla', 'ADN', 'Tiranosaurio'] },
  { p: 'Shrek', c: 'Películas', x: ['Ogro', 'Verde', 'Burro', 'Fiona', 'Pantano'] },
  { p: 'Frozen', c: 'Películas', x: ['Hielo', 'Elsa', 'Princesa', 'Muñeco de nieve', 'Libre soy'] },
  { p: 'Volver al Futuro', c: 'Películas', x: ['DeLorean', 'Viaje en el tiempo', 'Marty', 'Doc', 'Auto'] },
  { p: 'El Padrino', c: 'Películas', x: ['Mafia', 'Italia', 'Don', 'Oferta', 'Corleone'] },
  { p: 'Matrix', c: 'Películas', x: ['Pastilla', 'Neo', 'Realidad virtual', 'Agente', 'Lentes negros'] },
  { p: 'Piratas del Caribe', c: 'Películas', x: ['Jack Sparrow', 'Barco', 'Tesoro', 'Mar', 'Ron'] },
  { p: 'Rápido y Furioso', c: 'Películas', x: ['Autos', 'Carreras', 'Familia', 'Toretto', 'Velocidad'] },
  { p: 'Buscando a Nemo', c: 'Películas', x: ['Pez', 'Payaso', 'Océano', 'Dory', 'Perdido'] },
  { p: 'Los Increíbles', c: 'Películas', x: ['Superhéroes', 'Familia', 'Pixar', 'Traje', 'Poderes'] },
  { p: 'Mi Villano Favorito', c: 'Películas', x: ['Minions', 'Gru', 'Amarillo', 'Villano', 'Nenas'] },
  { p: 'Avatar', c: 'Películas', x: ['Azul', 'Pandora', 'Planeta', 'Alienígenas', 'James Cameron'] },
  { p: 'Avengers', c: 'Películas', x: ['Marvel', 'Superhéroes', 'Thanos', 'Iron Man', 'Equipo'] },
  { p: 'El Señor de los Anillos', c: 'Películas', x: ['Frodo', 'Anillo', 'Gandalf', 'Hobbit', 'Mordor'] },
  { p: 'Star Wars', c: 'Películas', x: ['Espada láser', 'Darth Vader', 'Galaxia', 'Fuerza', 'Yoda'] },
  { p: 'Terminator', c: 'Películas', x: ['Robot', 'Futuro', 'Schwarzenegger', 'Volveré', 'Máquina'] },
  { p: 'Rocky', c: 'Películas', x: ['Boxeo', 'Stallone', 'Escaleras', 'Filadelfia', 'Campeón'] },
  { p: 'E.T.', c: 'Películas', x: ['Extraterrestre', 'Bicicleta', 'Teléfono', 'Casa', 'Dedo'] },
  { p: 'La Era de Hielo', c: 'Películas', x: ['Ardilla', 'Bellota', 'Mamut', 'Perezoso', 'Glaciar'] },
  { p: 'Madagascar', c: 'Películas', x: ['Zoológico', 'León', 'Pingüinos', 'Isla', 'África'] },
  { p: 'Kung Fu Panda', c: 'Películas', x: ['Oso', 'Artes marciales', 'China', 'Po', 'Fideos'] },
  { p: 'Ratatouille', c: 'Películas', x: ['Rata', 'Cocinar', 'París', 'Chef', 'Restaurante'] },
  { p: 'Coco', c: 'Películas', x: ['México', 'Día de los muertos', 'Guitarra', 'Familia', 'Recuérdame'] },
  { p: 'Up', c: 'Películas', x: ['Globos', 'Casa', 'Viejito', 'Volar', 'Aventura'] },
  { p: 'Monsters Inc', c: 'Películas', x: ['Sustos', 'Puertas', 'Sully', 'Mike', 'Gritos'] },
  { p: 'Cars', c: 'Películas', x: ['Autos', 'Carreras', 'Rayo McQueen', 'Pixar', 'Rueda'] },
  { p: 'Grease', c: 'Películas', x: ['Baile', 'Musical', 'John Travolta', 'Secundaria', 'Cuero'] },
  { p: 'Duro de Matar', c: 'Películas', x: ['Bruce Willis', 'Navidad', 'Edificio', 'Policía', 'Explosión'] },
  { p: 'Misión Imposible', c: 'Películas', x: ['Tom Cruise', 'Espía', 'Máscara', 'Colgado', 'Bomba'] },
  { p: 'Mary Poppins', c: 'Películas', x: ['Niñera', 'Paraguas', 'Volar', 'Magia', 'Supercalifragilístico'] },
  { p: 'El Exorcista', c: 'Películas', x: ['Terror', 'Posesión', 'Cura', 'Demonio', 'Cabeza'] },
  { p: 'Karate Kid', c: 'Películas', x: ['Patada', 'Maestro', 'Miyagi', 'Encerar', 'Grulla'] },
  { p: 'Nueve Reinas', c: 'Películas', x: ['Estafa', 'Argentina', 'Darín', 'Estampillas', 'Timo'] },
  { p: 'Relatos Salvajes', c: 'Películas', x: ['Argentina', 'Episodios', 'Venganza', 'Avión', 'Casamiento'] },
  { p: 'Metegol', c: 'Películas', x: ['Argentina', 'Jugadores', 'Fútbol', 'Muñecos', 'Animada'] },
  { p: 'Esperando la Carroza', c: 'Películas', x: ['Mamá Cora', 'Argentina', 'Familia', 'Velorio', 'Tres empanadas'] },
  { p: 'Gladiador', c: 'Películas', x: ['Roma', 'Coliseo', 'Espada', 'Máximo', 'Emperador'] },
  { p: 'Forrest Gump', c: 'Películas', x: ['Correr', 'Chocolates', 'Pluma', 'Tom Hanks', 'Banco'] },
  { p: 'Intensamente', c: 'Películas', x: ['Emociones', 'Alegría', 'Tristeza', 'Cabeza', 'Pixar'] },
  { p: 'Wall-E', c: 'Películas', x: ['Robot', 'Basura', 'Espacio', 'Planta', 'Solo'] },
  { p: 'Náufrago', c: 'Películas', x: ['Isla', 'Wilson', 'Pelota', 'Tom Hanks', 'Solo'] },
  { p: 'Jumanji', c: 'Películas', x: ['Juego', 'Selva', 'Dados', 'Animales', 'Robin Williams'] },
  { p: 'Los Cazafantasmas', c: 'Películas', x: ['Fantasmas', 'Atrapar', 'Mochila láser', 'Nueva York', 'Logo'] },
  { p: 'Mi Pobre Angelito', c: 'Películas', x: ['Navidad', 'Solo en casa', 'Ladrones', 'Trampas', 'Kevin'] },
  { p: 'It', c: 'Películas', x: ['Payaso', 'Globo', 'Terror', 'Alcantarilla', 'Pennywise'] },
  { p: 'Crepúsculo', c: 'Películas', x: ['Vampiros', 'Amor', 'Hombre lobo', 'Bella', 'Brillar'] },
  { p: 'Los Juegos del Hambre', c: 'Películas', x: ['Arco', 'Katniss', 'Distritos', 'Arena', 'Sinsajo'] },
  { p: 'Barbie', c: 'Películas', x: ['Rosa', 'Muñeca', 'Ken', 'Margot Robbie', 'Plástico'] },
  // ── Actores y famosos ──
  { p: 'Leonardo DiCaprio', c: 'Actores y famosos', x: ['Titanic', 'Oscar', 'Lobo de Wall Street', 'Actor', 'Barco'] },
  { p: 'Brad Pitt', c: 'Actores y famosos', x: ['Angelina', 'Rubio', 'Hollywood', 'Actor', 'Club de la Pelea'] },
  { p: 'Jim Carrey', c: 'Actores y famosos', x: ['La Máscara', 'Comedia', 'Ace Ventura', 'Caras', 'Grinch'] },
  { p: 'La Roca', c: 'Actores y famosos', x: ['Músculos', 'Lucha libre', 'Pelado', 'Actor', 'Piedra'] },
  { p: 'Angelina Jolie', c: 'Actores y famosos', x: ['Brad', 'Labios', 'Tomb Raider', 'Actriz', 'Maléfica'] },
  { p: 'Tom Cruise', c: 'Actores y famosos', x: ['Misión Imposible', 'Top Gun', 'Bajo', 'Actor', 'Acción'] },
  { p: 'Will Smith', c: 'Actores y famosos', x: ['Príncipe del rap', 'Cachetada', 'Men in Black', 'Actor', 'Oscar'] },
  { p: 'Keanu Reeves', c: 'Actores y famosos', x: ['Matrix', 'John Wick', 'Neo', 'Actor', 'Motos'] },
  { p: 'Johnny Depp', c: 'Actores y famosos', x: ['Pirata', 'Jack Sparrow', 'Tijeras', 'Actor', 'Sombrero'] },
  { p: 'Ricardo Darín', c: 'Actores y famosos', x: ['Argentino', 'El secreto de sus ojos', 'Nueve reinas', 'Actor', 'Relatos salvajes'] },
  { p: 'Guillermo Francella', c: 'Actores y famosos', x: ['Casados con hijos', 'Bigote', 'Comedia', 'Argentino', 'El Clan'] },
  { p: 'Lionel Messi', c: 'Actores y famosos', x: ['Fútbol', 'Argentina', 'Diez', 'Barcelona', 'Copa del mundo'] },
  { p: 'Diego Maradona', c: 'Actores y famosos', x: ['Diez', 'Mano de Dios', 'Fútbol', 'Barrilete cósmico', 'Nápoles'] },
  { p: 'Cristiano Ronaldo', c: 'Actores y famosos', x: ['Portugal', 'Fútbol', 'Siuuu', 'Real Madrid', 'CR7'] },
  { p: 'Michael Jackson', c: 'Actores y famosos', x: ['Rey del pop', 'Moonwalk', 'Thriller', 'Guante', 'Cantante'] },
  { p: 'Shakira', c: 'Actores y famosos', x: ['Colombia', 'Caderas', 'Cantante', 'Piqué', 'Waka Waka'] },
  { p: 'Madonna', c: 'Actores y famosos', x: ['Reina del pop', 'Cantante', 'Rubia', 'Like a Virgin', 'Evita'] },
  { p: 'Freddie Mercury', c: 'Actores y famosos', x: ['Queen', 'Bigote', 'Bohemian Rhapsody', 'Cantante', 'We Will Rock You'] },
  { p: 'Elvis Presley', c: 'Actores y famosos', x: ['Rey del rock', 'Jopo', 'Cantante', 'Caderas', 'Memphis'] },
  { p: 'Charly García', c: 'Actores y famosos', x: ['Bigote bicolor', 'Rock nacional', 'Piano', 'Cantante', 'Say No More'] },
  { p: 'Bizarrap', c: 'Actores y famosos', x: ['Sesiones', 'Gorra', 'Lentes', 'Productor', 'Música'] },
  { p: 'Susana Giménez', c: 'Actores y famosos', x: ['Diva', 'Teléfono', 'Rubia', 'Televisión', 'Shock'] },
  { p: 'Marcelo Tinelli', c: 'Actores y famosos', x: ['ShowMatch', 'Conductor', 'Bailando', 'Televisión', 'Cámara'] },
  { p: 'Mirtha Legrand', c: 'Actores y famosos', x: ['Almuerzos', 'Televisión', 'Diva', 'Mesa', 'Chiquita'] },
  { p: 'Moria Casán', c: 'Actores y famosos', x: ['Diva', 'Lengua', 'Vedette', 'One', 'Jurado'] },
  { p: 'Lali Espósito', c: 'Actores y famosos', x: ['Cantante', 'Casi Ángeles', 'Pop', 'Actriz', 'Disciplina'] },
  { p: 'El Dibu Martínez', c: 'Actores y famosos', x: ['Arquero', 'Penales', 'Selección', 'Atajada', 'Baile'] },
  { p: 'Usain Bolt', c: 'Actores y famosos', x: ['Correr', 'Jamaica', 'Rayo', 'Velocista', 'Récord'] },
  { p: 'Mike Tyson', c: 'Actores y famosos', x: ['Boxeo', 'Oreja', 'Nocaut', 'Tatuaje', 'Campeón'] },
  { p: 'Michael Jordan', c: 'Actores y famosos', x: ['Básquet', 'Chicago Bulls', 'Veintitrés', 'Zapatillas', 'Volar'] },
  { p: 'Serena Williams', c: 'Actores y famosos', x: ['Tenis', 'Raqueta', 'Hermanas', 'Campeona', 'Estados Unidos'] },
  { p: 'Albert Einstein', c: 'Actores y famosos', x: ['Científico', 'Relatividad', 'Genio', 'Lengua', 'Pelo loco'] },
  { p: 'Morgan Freeman', c: 'Actores y famosos', x: ['Voz', 'Dios', 'Narrador', 'Actor', 'Pecas'] },
  { p: 'Arnold Schwarzenegger', c: 'Actores y famosos', x: ['Terminator', 'Músculos', 'Austria', 'Gobernador', 'Volveré'] },
  { p: 'Sylvester Stallone', c: 'Actores y famosos', x: ['Rocky', 'Rambo', 'Boxeo', 'Actor', 'Músculos'] },
  { p: 'Emma Watson', c: 'Actores y famosos', x: ['Hermione', 'Harry Potter', 'Actriz', 'Inglesa', 'Maga'] },
  { p: 'Julia Roberts', c: 'Actores y famosos', x: ['Mujer bonita', 'Sonrisa', 'Actriz', 'Pelirroja', 'Hollywood'] },
  { p: 'Adam Sandler', c: 'Actores y famosos', x: ['Comedia', 'Actor', 'Netflix', 'Como si fuera la primera vez', 'Gracioso'] },
  { p: 'Danny DeVito', c: 'Actores y famosos', x: ['Bajito', 'Actor', 'Matilda', 'Pelado', 'Comedia'] },
  { p: 'Antonio Banderas', c: 'Actores y famosos', x: ['Español', 'Zorro', 'Gato con botas', 'Actor', 'Acento'] },
  { p: 'Jackie Chan', c: 'Actores y famosos', x: ['Artes marciales', 'China', 'Acrobacias', 'Actor', 'Golpes'] },
  { p: 'Taylor Swift', c: 'Actores y famosos', x: ['Cantante', 'Pop', 'Swifties', 'Eras Tour', 'Rubia'] },
  { p: 'Bad Bunny', c: 'Actores y famosos', x: ['Reggaetón', 'Puerto Rico', 'Conejo', 'Trap', 'Lentes'] },
  { p: 'Duki', c: 'Actores y famosos', x: ['Trap', 'Argentino', 'Freestyle', 'Rapero', 'Modo diablo'] },
  { p: 'María Becerra', c: 'Actores y famosos', x: ['Cantante', 'Argentina', 'Nena de Argentina', 'Pop', 'Quilmes'] },
  { p: 'Tini', c: 'Actores y famosos', x: ['Violetta', 'Cantante', 'Argentina', 'Pop', 'Triple T'] },
  { p: 'Novak Djokovic', c: 'Actores y famosos', x: ['Tenis', 'Serbia', 'Número uno', 'Grand Slam', 'Raqueta'] },
  { p: 'Kylian Mbappé', c: 'Actores y famosos', x: ['Francia', 'Fútbol', 'Velocidad', 'Real Madrid', 'Campeón del mundo'] },
  { p: 'Beyoncé', c: 'Actores y famosos', x: ['Cantante', 'Diva', 'Single Ladies', 'Queen B', 'Estados Unidos'] },
  { p: 'Marley', c: 'Actores y famosos', x: ['Conductor', 'Viajes', 'Por el mundo', 'Mirko', 'Televisión'] },
  { p: 'Guido Kaczka', c: 'Actores y famosos', x: ['Conductor', 'Los 8 escalones', 'Televisión', 'Preguntas', 'Premios'] },
  // ── Personajes ──
  { p: 'Batman', c: 'Personajes', x: ['Murciélago', 'Ciudad Gótica', 'Robin', 'Guasón', 'Capa'] },
  { p: 'Superman', c: 'Personajes', x: ['Capa', 'Volar', 'Kriptonita', 'Clark Kent', 'Acero'] },
  { p: 'Homero Simpson', c: 'Personajes', x: ['Amarillo', 'Donas', 'Springfield', 'Bart', 'Cerveza'] },
  { p: 'Bob Esponja', c: 'Personajes', x: ['Amarillo', 'Mar', 'Patricio', 'Cangreburger', 'Piña'] },
  { p: 'Mickey Mouse', c: 'Personajes', x: ['Ratón', 'Disney', 'Orejas', 'Minnie', 'Guantes'] },
  { p: 'El Hombre Araña', c: 'Personajes', x: ['Telaraña', 'Trepar', 'Rojo', 'Peter Parker', 'Araña'] },
  { p: 'Darth Vader', c: 'Personajes', x: ['Star Wars', 'Casco', 'Padre', 'Lado oscuro', 'Respiración'] },
  { p: 'Papá Noel', c: 'Personajes', x: ['Navidad', 'Regalos', 'Rojo', 'Barba', 'Renos'] },
  { p: 'Pikachu', c: 'Personajes', x: ['Pokémon', 'Amarillo', 'Rayo', 'Ash', 'Ratón'] },
  { p: 'Mario Bros', c: 'Personajes', x: ['Plomero', 'Bigote', 'Hongo', 'Luigi', 'Princesa'] },
  { p: 'El Grinch', c: 'Personajes', x: ['Navidad', 'Verde', 'Robar', 'Odiar', 'Regalos'] },
  { p: 'El Guasón', c: 'Personajes', x: ['Batman', 'Payaso', 'Risa', 'Villano', 'Pelo verde'] },
  { p: 'Mujer Maravilla', c: 'Personajes', x: ['Amazona', 'Lazo', 'Superheroína', 'Tiara', 'Escudo'] },
  { p: 'Hulk', c: 'Personajes', x: ['Verde', 'Enojado', 'Gigante', 'Músculos', 'Aplastar'] },
  { p: 'Iron Man', c: 'Personajes', x: ['Armadura', 'Tony Stark', 'Marvel', 'Volar', 'Millonario'] },
  { p: 'Thor', c: 'Personajes', x: ['Martillo', 'Dios', 'Trueno', 'Rubio', 'Asgard'] },
  { p: 'Capitán América', c: 'Personajes', x: ['Escudo', 'Soldado', 'Estados Unidos', 'Vengador', 'Estrella'] },
  { p: 'Goku', c: 'Personajes', x: ['Dragon Ball', 'Saiyajin', 'Kamehameha', 'Pelo', 'Esferas'] },
  { p: 'Naruto', c: 'Personajes', x: ['Ninja', 'Anime', 'Zorro', 'Naranja', 'Aldea'] },
  { p: 'Pato Donald', c: 'Personajes', x: ['Pato', 'Disney', 'Marinero', 'Enojado', 'Sin pantalones'] },
  { p: 'Winnie Pooh', c: 'Personajes', x: ['Oso', 'Miel', 'Amarillo', 'Puerquito', 'Bosque'] },
  { p: 'Pinocho', c: 'Personajes', x: ['Nariz', 'Mentira', 'Madera', 'Muñeco', 'Grillo'] },
  { p: 'Peter Pan', c: 'Personajes', x: ['Volar', 'Nunca Jamás', 'Campanita', 'Garfio', 'Niño'] },
  { p: 'Cenicienta', c: 'Personajes', x: ['Zapato', 'Princesa', 'Medianoche', 'Carroza', 'Madrastra'] },
  { p: 'Blancanieves', c: 'Personajes', x: ['Manzana', 'Enanos', 'Espejo', 'Princesa', 'Bruja'] },
  { p: 'La Sirenita', c: 'Personajes', x: ['Mar', 'Cola', 'Ariel', 'Cangrejo', 'Voz'] },
  { p: 'Aladdín', c: 'Personajes', x: ['Genio', 'Lámpara', 'Alfombra', 'Deseos', 'Príncipe'] },
  { p: 'Buzz Lightyear', c: 'Personajes', x: ['Toy Story', 'Espacio', 'Al infinito', 'Juguete', 'Alas'] },
  { p: 'Minion', c: 'Personajes', x: ['Amarillo', 'Banana', 'Anteojos', 'Gru', 'Idioma'] },
  { p: 'Gollum', c: 'Personajes', x: ['Anillo', 'Mi precioso', 'Hobbit', 'Cueva', 'Flaco'] },
  { p: 'Frankenstein', c: 'Personajes', x: ['Monstruo', 'Verde', 'Tornillos', 'Científico', 'Rayo'] },
  { p: 'La Momia', c: 'Personajes', x: ['Vendas', 'Egipto', 'Sarcófago', 'Maldición', 'Muerto'] },
  { p: 'Chucky', c: 'Personajes', x: ['Muñeco', 'Terror', 'Cuchillo', 'Pelirrojo', 'Overol'] },
  { p: 'Godzilla', c: 'Personajes', x: ['Monstruo', 'Japón', 'Gigante', 'Ciudad', 'Lagarto'] },
  { p: 'King Kong', c: 'Personajes', x: ['Gorila', 'Gigante', 'Edificio', 'Isla', 'Rubia'] },
  { p: 'Sonic', c: 'Personajes', x: ['Erizo', 'Azul', 'Velocidad', 'Anillos', 'Sega'] },
  { p: 'Pac-Man', c: 'Personajes', x: ['Comer', 'Fantasmas', 'Amarillo', 'Laberinto', 'Arcade'] },
  { p: 'Lara Croft', c: 'Personajes', x: ['Tomb Raider', 'Aventurera', 'Tumbas', 'Videojuego', 'Trenza'] },
  { p: 'Mr. Bean', c: 'Personajes', x: ['Inglés', 'Comedia', 'Oso de peluche', 'Auto verde', 'Gestos'] },
  { p: 'El Chavo', c: 'Personajes', x: ['Barril', 'Vecindad', 'Ocho', 'México', 'Torta de jamón'] },
  { p: 'El Chapulín Colorado', c: 'Personajes', x: ['Antenas', 'Rojo', 'Chipote chillón', 'Héroe', 'México'] },
  { p: 'Wolverine', c: 'Personajes', x: ['Garras', 'X-Men', 'Mutante', 'Regenerar', 'Adamantium'] },
  { p: 'Deadpool', c: 'Personajes', x: ['Rojo', 'Mercenario', 'Cuarta pared', 'Katanas', 'Chistes'] },
  { p: 'Dumbledore', c: 'Personajes', x: ['Director', 'Hogwarts', 'Barba', 'Mago', 'Varita'] },
  { p: 'Voldemort', c: 'Personajes', x: ['Villano', 'Sin nariz', 'Harry Potter', 'Innombrable', 'Varita'] },
  { p: 'Yoda', c: 'Personajes', x: ['Star Wars', 'Verde', 'Maestro', 'Orejas', 'Al revés'] },
  { p: 'Garfield', c: 'Personajes', x: ['Gato', 'Naranja', 'Lasaña', 'Lunes', 'Perezoso'] },
  { p: 'Snoopy', c: 'Personajes', x: ['Perro', 'Blanco', 'Charlie Brown', 'Casita', 'Historieta'] },
  { p: 'Olaf', c: 'Personajes', x: ['Frozen', 'Muñeco de nieve', 'Zanahoria', 'Abrazos', 'Verano'] },
  { p: 'Popeye', c: 'Personajes', x: ['Espinaca', 'Marinero', 'Músculos', 'Pipa', 'Olivia'] },
  { p: 'Tarzán', c: 'Personajes', x: ['Selva', 'Liana', 'Grito', 'Mono', 'Taparrabos'] },
  // ── Videojuegos ──
  { p: 'Minecraft', c: 'Videojuegos', x: ['Bloques', 'Construir', 'Creeper', 'Picar', 'Cubos'] },
  { p: 'Fortnite', c: 'Videojuegos', x: ['Battle Royale', 'Construir', 'Bailes', 'Isla', 'Tormenta'] },
  { p: 'Tetris', c: 'Videojuegos', x: ['Bloques', 'Encajar', 'Líneas', 'Caer', 'Ruso'] },
  { p: 'FIFA', c: 'Videojuegos', x: ['Fútbol', 'EA Sports', 'Ultimate Team', 'Consola', 'Messi'] },
  { p: 'Candy Crush', c: 'Videojuegos', x: ['Caramelos', 'Celular', 'Niveles', 'Combinar', 'Vidas'] },
  { p: 'GTA', c: 'Videojuegos', x: ['Autos', 'Robar', 'San Andreas', 'Policía', 'Misiones'] },
  { p: 'Call of Duty', c: 'Videojuegos', x: ['Guerra', 'Disparos', 'Soldados', 'Online', 'Warzone'] },
  { p: 'Among Us', c: 'Videojuegos', x: ['Impostor', 'Tripulación', 'Nave', 'Sospechoso', 'Tareas'] },
  { p: 'Zelda', c: 'Videojuegos', x: ['Link', 'Espada', 'Princesa', 'Hyrule', 'Trifuerza'] },
  { p: 'Pokémon', c: 'Videojuegos', x: ['Atrapar', 'Pikachu', 'Entrenador', 'Pokebola', 'Evolución'] },
  { p: 'Mario Kart', c: 'Videojuegos', x: ['Carreras', 'Caparazón', 'Banana', 'Karting', 'Nintendo'] },
  { p: 'Counter-Strike', c: 'Videojuegos', x: ['Terroristas', 'Bomba', 'Disparos', 'Policías', 'Computadora'] },
  { p: 'League of Legends', c: 'Videojuegos', x: ['MOBA', 'Campeones', 'Grieta', 'Online', 'Equipos'] },
  { p: 'Angry Birds', c: 'Videojuegos', x: ['Pájaros', 'Gomera', 'Chanchos', 'Celular', 'Huevos'] },
  { p: 'Los Sims', c: 'Videojuegos', x: ['Vida', 'Casa', 'Familia', 'Simular', 'Construir'] },
  { p: 'Crash Bandicoot', c: 'Videojuegos', x: ['Marsupial', 'Cajas', 'Girar', 'Manzanas', 'Naranja'] },
  { p: 'Mortal Kombat', c: 'Videojuegos', x: ['Pelea', 'Fatality', 'Scorpion', 'Sangre', 'Torneo'] },
  { p: 'Street Fighter', c: 'Videojuegos', x: ['Pelea', 'Hadouken', 'Ryu', 'Combos', 'Japón'] },
  { p: 'God of War', c: 'Videojuegos', x: ['Kratos', 'Dioses', 'Hacha', 'Grecia', 'Guerra'] },
  { p: 'Elden Ring', c: 'Videojuegos', x: ['Difícil', 'Jefes', 'Morir', 'Anillo', 'Souls'] },
  { p: 'Roblox', c: 'Videojuegos', x: ['Plataforma', 'Crear', 'Niños', 'Avatares', 'Juegos'] },
  { p: 'Free Fire', c: 'Videojuegos', x: ['Battle Royale', 'Celular', 'Disparos', 'Booyah', 'Isla'] },
  { p: 'Clash Royale', c: 'Videojuegos', x: ['Cartas', 'Torres', 'Coronas', 'Celular', 'Elixir'] },
  { p: 'Doom', c: 'Videojuegos', x: ['Demonios', 'Marte', 'Disparos', 'Infierno', 'Clásico'] },
  { p: 'Space Invaders', c: 'Videojuegos', x: ['Naves', 'Aliens', 'Disparar', 'Arcade', 'Filas'] },
  { p: 'Kirby', c: 'Videojuegos', x: ['Rosa', 'Aspirar', 'Redondo', 'Nintendo', 'Estrella'] },
  { p: 'Donkey Kong', c: 'Videojuegos', x: ['Gorila', 'Corbata', 'Bananas', 'Barriles', 'Nintendo'] },
  { p: 'Luigi', c: 'Videojuegos', x: ['Hermano', 'Verde', 'Mario', 'Bigote', 'Fantasmas'] },
  { p: 'Princesa Peach', c: 'Videojuegos', x: ['Rosa', 'Castillo', 'Rescatar', 'Corona', 'Mario'] },
  { p: 'Bowser', c: 'Videojuegos', x: ['Villano', 'Tortuga', 'Fuego', 'Mario', 'Púas'] },
  { p: 'Charizard', c: 'Videojuegos', x: ['Pokémon', 'Dragón', 'Fuego', 'Naranja', 'Evolución'] },
  { p: 'Master Chief', c: 'Videojuegos', x: ['Halo', 'Casco', 'Soldado', 'Verde', 'Espacial'] },
  { p: 'Plants vs Zombies', c: 'Videojuegos', x: ['Plantas', 'Jardín', 'Girasol', 'Cerebros', 'Defender'] },
  { p: 'Subway Surfers', c: 'Videojuegos', x: ['Correr', 'Tren', 'Vías', 'Monedas', 'Inspector'] },
  { p: 'Consola', c: 'Videojuegos', x: ['PlayStation', 'Jugar', 'Control', 'Televisión', 'Xbox'] },
  { p: 'Joystick', c: 'Videojuegos', x: ['Botones', 'Manos', 'Control', 'Palancas', 'Vibrar'] },
  { p: 'Game Over', c: 'Videojuegos', x: ['Perder', 'Fin', 'Pantalla', 'Vidas', 'Continuar'] },
  { p: 'Nivel', c: 'Videojuegos', x: ['Pasar', 'Subir', 'Dificultad', 'Etapa', 'Completar'] },
  { p: 'Jefe final', c: 'Videojuegos', x: ['Difícil', 'Último', 'Pelea', 'Vida', 'Derrotar'] },
  { p: 'Vida extra', c: 'Videojuegos', x: ['Corazón', 'Morir', 'Hongo', 'Sumar', 'Continuar'] },
  { p: 'Checkpoint', c: 'Videojuegos', x: ['Guardar', 'Punto', 'Volver', 'Progreso', 'Bandera'] },
  { p: 'Multijugador', c: 'Videojuegos', x: ['Online', 'Amigos', 'Equipo', 'Partida', 'Conectados'] },
  { p: 'Lag', c: 'Videojuegos', x: ['Internet', 'Lento', 'Congelado', 'Conexión', 'Online'] },
  { p: 'Gamer', c: 'Videojuegos', x: ['Jugador', 'Silla', 'Auriculares', 'Streaming', 'Vicio'] },
  { p: 'Speedrun', c: 'Videojuegos', x: ['Rápido', 'Récord', 'Terminar', 'Tiempo', 'Trucos'] },
  { p: 'Tutorial', c: 'Videojuegos', x: ['Aprender', 'Principio', 'Instrucciones', 'Guía', 'Primeros pasos'] },
  { p: 'Easter egg', c: 'Videojuegos', x: ['Secreto', 'Escondido', 'Sorpresa', 'Huevo', 'Desarrolladores'] },
  { p: 'Skin', c: 'Videojuegos', x: ['Apariencia', 'Personaje', 'Comprar', 'Ropa', 'Fortnite'] },
  { p: 'Arcade', c: 'Videojuegos', x: ['Fichas', 'Máquinas', 'Salón', 'Retro', 'Palanca'] },
  { p: 'E-sports', c: 'Videojuegos', x: ['Torneos', 'Profesional', 'Equipos', 'Premios', 'Competencia'] },
  // ── Deportes ──
  { p: 'Fútbol', c: 'Deportes', x: ['Pelota', 'Gol', 'Cancha', 'Equipo', 'Arco'] },
  { p: 'Tenis', c: 'Deportes', x: ['Raqueta', 'Pelota', 'Red', 'Saque', 'Cancha'] },
  { p: 'Natación', c: 'Deportes', x: ['Agua', 'Pileta', 'Nadar', 'Brazadas', 'Malla'] },
  { p: 'Básquet', c: 'Deportes', x: ['Aro', 'Pelota', 'Canasta', 'Rebote', 'Picar'] },
  { p: 'Boxeo', c: 'Deportes', x: ['Guantes', 'Ring', 'Golpe', 'Nocaut', 'Pelea'] },
  { p: 'Maratón', c: 'Deportes', x: ['Correr', 'Kilómetros', 'Meta', 'Resistencia', 'Carrera'] },
  { p: 'Ajedrez', c: 'Deportes', x: ['Tablero', 'Rey', 'Jaque', 'Piezas', 'Estrategia'] },
  { p: 'Surf', c: 'Deportes', x: ['Ola', 'Tabla', 'Mar', 'Equilibrio', 'Playa'] },
  { p: 'Esquí', c: 'Deportes', x: ['Nieve', 'Montaña', 'Tablas', 'Bastones', 'Invierno'] },
  { p: 'Yoga', c: 'Deportes', x: ['Estirar', 'Posturas', 'Relajación', 'Colchoneta', 'Respirar'] },
  { p: 'Árbitro', c: 'Deportes', x: ['Silbato', 'Tarjeta', 'Falta', 'Juez', 'Partido'] },
  { p: 'Vóley', c: 'Deportes', x: ['Red', 'Pelota', 'Playa', 'Manos', 'Saque'] },
  { p: 'Rugby', c: 'Deportes', x: ['Ovalada', 'Try', 'Tackle', 'Pumas', 'Scrum'] },
  { p: 'Hockey', c: 'Deportes', x: ['Palo', 'Bocha', 'Leonas', 'Césped', 'Patines'] },
  { p: 'Golf', c: 'Deportes', x: ['Hoyo', 'Palos', 'Pelotita', 'Césped', 'Tiger Woods'] },
  { p: 'Ciclismo', c: 'Deportes', x: ['Bicicleta', 'Pedalear', 'Tour de Francia', 'Casco', 'Ruedas'] },
  { p: 'Skate', c: 'Deportes', x: ['Tabla', 'Ruedas', 'Trucos', 'Rampa', 'Caerse'] },
  { p: 'Fórmula 1', c: 'Deportes', x: ['Autos', 'Carrera', 'Velocidad', 'Boxes', 'Colapinto'] },
  { p: 'Esgrima', c: 'Deportes', x: ['Espada', 'Careta', 'Tocado', 'Duelo', 'Blanco'] },
  { p: 'Gimnasia artística', c: 'Deportes', x: ['Piruetas', 'Barras', 'Medalla', 'Flexibilidad', 'Olimpiadas'] },
  { p: 'Pádel', c: 'Deportes', x: ['Paleta', 'Pared', 'Cancha', 'Parejas', 'Moda'] },
  // ── Objetos ──
  { p: 'Paraguas', c: 'Objetos', x: ['Lluvia', 'Abrir', 'Mojarse', 'Mango', 'Cubrirse'] },
  { p: 'Espejo', c: 'Objetos', x: ['Reflejo', 'Vidrio', 'Mirarse', 'Baño', 'Imagen'] },
  { p: 'Almohada', c: 'Objetos', x: ['Dormir', 'Cama', 'Cabeza', 'Suave', 'Plumas'] },
  { p: 'Tijera', c: 'Objetos', x: ['Cortar', 'Papel', 'Filo', 'Dos', 'Peluquería'] },
  { p: 'Heladera', c: 'Objetos', x: ['Frío', 'Cocina', 'Comida', 'Puerta', 'Congelador'] },
  { p: 'Celular', c: 'Objetos', x: ['Llamar', 'Pantalla', 'Apps', 'Batería', 'Mensaje'] },
  { p: 'Llave', c: 'Objetos', x: ['Puerta', 'Abrir', 'Cerradura', 'Candado', 'Auto'] },
  { p: 'Reloj', c: 'Objetos', x: ['Hora', 'Muñeca', 'Agujas', 'Tiempo', 'Despertador'] },
  { p: 'Escoba', c: 'Objetos', x: ['Barrer', 'Limpiar', 'Palo', 'Piso', 'Bruja'] },
  { p: 'Anteojos', c: 'Objetos', x: ['Ver', 'Ojos', 'Marco', 'Lentes', 'Sol'] },
  { p: 'Cepillo de dientes', c: 'Objetos', x: ['Pasta', 'Boca', 'Lavar', 'Baño', 'Higiene'] },
  { p: 'Lapicera', c: 'Objetos', x: ['Escribir', 'Tinta', 'Birome', 'Papel', 'Tapa'] },
  { p: 'Mochila', c: 'Objetos', x: ['Espalda', 'Escuela', 'Cargar', 'Cierres', 'Viaje'] },
  { p: 'Auriculares', c: 'Objetos', x: ['Música', 'Orejas', 'Escuchar', 'Cable', 'Inalámbricos'] },
  { p: 'Ventilador', c: 'Objetos', x: ['Calor', 'Aspas', 'Girar', 'Verano', 'Aire'] },
  { p: 'Martillo', c: 'Objetos', x: ['Clavo', 'Golpear', 'Herramienta', 'Thor', 'Carpintero'] },
  { p: 'Vela', c: 'Objetos', x: ['Fuego', 'Cera', 'Cumpleaños', 'Soplar', 'Apagón'] },
  { p: 'Linterna', c: 'Objetos', x: ['Luz', 'Oscuridad', 'Pilas', 'Camping', 'Alumbrar'] },
  { p: 'Control remoto', c: 'Objetos', x: ['Televisión', 'Botones', 'Cambiar', 'Pilas', 'Sillón'] },
  { p: 'Valija', c: 'Objetos', x: ['Viaje', 'Ropa', 'Ruedas', 'Aeropuerto', 'Empacar'] },
  { p: 'Silla', c: 'Objetos', x: ['Sentarse', 'Patas', 'Mesa', 'Madera', 'Respaldo'] },
  // ── Lugares ──
  { p: 'Playa', c: 'Lugares', x: ['Arena', 'Mar', 'Sol', 'Sombrilla', 'Verano'] },
  { p: 'Hospital', c: 'Lugares', x: ['Médico', 'Enfermo', 'Camilla', 'Ambulancia', 'Cirugía'] },
  { p: 'Escuela', c: 'Lugares', x: ['Maestra', 'Alumnos', 'Pizarrón', 'Recreo', 'Aula'] },
  { p: 'Aeropuerto', c: 'Lugares', x: ['Avión', 'Valija', 'Vuelo', 'Pasaporte', 'Despegar'] },
  { p: 'Supermercado', c: 'Lugares', x: ['Comprar', 'Carrito', 'Góndola', 'Caja', 'Precios'] },
  { p: 'Cine', c: 'Lugares', x: ['Película', 'Pantalla', 'Butaca', 'Entrada', 'Pochoclo'] },
  { p: 'Museo', c: 'Lugares', x: ['Arte', 'Cuadros', 'Historia', 'Exhibición', 'Antiguo'] },
  { p: 'Selva', c: 'Lugares', x: ['Árboles', 'Animales', 'Húmedo', 'Tarzán', 'Verde'] },
  { p: 'Desierto', c: 'Lugares', x: ['Arena', 'Calor', 'Camello', 'Cactus', 'Seco'] },
  { p: 'Luna', c: 'Lugares', x: ['Espacio', 'Astronauta', 'Noche', 'Cráter', 'Llena'] },
  { p: 'Gimnasio', c: 'Lugares', x: ['Pesas', 'Ejercicio', 'Músculos', 'Entrenar', 'Máquinas'] },
  { p: 'Cancha', c: 'Lugares', x: ['Fútbol', 'Estadio', 'Hinchada', 'Pasto', 'Tribuna'] },
  { p: 'Iglesia', c: 'Lugares', x: ['Cura', 'Misa', 'Rezar', 'Campana', 'Cruz'] },
  { p: 'Biblioteca', c: 'Lugares', x: ['Libros', 'Silencio', 'Estudiar', 'Estantes', 'Prestar'] },
  { p: 'Zoológico', c: 'Lugares', x: ['Animales', 'Jaulas', 'Visitar', 'Leones', 'Paseo'] },
  { p: 'Restaurante', c: 'Lugares', x: ['Comer', 'Mozo', 'Menú', 'Mesa', 'Propina'] },
  { p: 'Plaza', c: 'Lugares', x: ['Juegos', 'Hamacas', 'Árboles', 'Banco', 'Barrio'] },
  { p: 'Cementerio', c: 'Lugares', x: ['Tumbas', 'Muertos', 'Flores', 'Lápida', 'Fantasmas'] },
  { p: 'Estación de servicio', c: 'Lugares', x: ['Nafta', 'Auto', 'Cargar', 'Surtidor', 'Ruta'] },
  { p: 'Peluquería', c: 'Lugares', x: ['Cortar', 'Pelo', 'Tijeras', 'Espejo', 'Peine'] },
  { p: 'Antártida', c: 'Lugares', x: ['Frío', 'Hielo', 'Pingüinos', 'Sur', 'Blanco'] },
  // ── Música y famosos ──
  { p: 'Guitarra', c: 'Música y famosos', x: ['Cuerdas', 'Tocar', 'Rock', 'Acordes', 'Instrumento'] },
  { p: 'Batería', c: 'Música y famosos', x: ['Palillos', 'Ritmo', 'Tambor', 'Platillos', 'Golpear'] },
  { p: 'Micrófono', c: 'Música y famosos', x: ['Cantar', 'Voz', 'Escenario', 'Karaoke', 'Hablar'] },
  { p: 'Karaoke', c: 'Música y famosos', x: ['Cantar', 'Letra', 'Pantalla', 'Micrófono', 'Bar'] },
  { p: 'Ópera', c: 'Música y famosos', x: ['Cantar', 'Teatro', 'Soprano', 'Clásica', 'Italiano'] },
  { p: 'DJ', c: 'Música y famosos', x: ['Música', 'Mezclar', 'Fiesta', 'Bandeja', 'Electrónica'] },
  { p: 'Tango', c: 'Música y famosos', x: ['Baile', 'Buenos Aires', 'Gardel', 'Pareja', 'Bandoneón'] },
  { p: 'Coro', c: 'Música y famosos', x: ['Cantar', 'Grupo', 'Voces', 'Iglesia', 'Director'] },
  { p: 'Violín', c: 'Música y famosos', x: ['Cuerdas', 'Arco', 'Clásica', 'Orquesta', 'Hombro'] },
  { p: 'Rockstar', c: 'Música y famosos', x: ['Escenario', 'Guitarra', 'Fama', 'Gira', 'Fans'] },
  { p: 'Cumbia', c: 'Música y famosos', x: ['Baile', 'Fiesta', 'Ritmo', 'Música', 'Tropical'] },
  { p: 'Piano', c: 'Música y famosos', x: ['Teclas', 'Blanco y negro', 'Cola', 'Concierto', 'Dedos'] },
  { p: 'Trompeta', c: 'Música y famosos', x: ['Soplar', 'Viento', 'Jazz', 'Dorada', 'Labios'] },
  { p: 'Acordeón', c: 'Música y famosos', x: ['Fuelle', 'Apretar', 'Cumbia', 'Teclas', 'Aire'] },
  { p: 'Reggaetón', c: 'Música y famosos', x: ['Perreo', 'Ritmo', 'Puerto Rico', 'Bailar', 'Fiesta'] },
  { p: 'Orquesta', c: 'Música y famosos', x: ['Director', 'Instrumentos', 'Batuta', 'Sinfonía', 'Músicos'] },
  { p: 'Recital', c: 'Música y famosos', x: ['Banda', 'Escenario', 'Entradas', 'Público', 'Vivo'] },
  { p: 'Folclore', c: 'Música y famosos', x: ['Zamba', 'Guitarra', 'Tradición', 'Peña', 'Bombo'] },
  { p: 'Rap', c: 'Música y famosos', x: ['Rimas', 'Freestyle', 'Batalla', 'Micrófono', 'Calle'] },
  { p: 'Flauta', c: 'Música y famosos', x: ['Soplar', 'Agujeros', 'Dulce', 'Escuela', 'Hamelín'] },
  { p: 'Vinilo', c: 'Música y famosos', x: ['Disco', 'Tocadiscos', 'Antiguo', 'Negro', 'Colección'] },
  // ── Acciones ──
  { p: 'Estornudar', c: 'Acciones', x: ['Nariz', 'Achís', 'Resfrío', 'Pañuelo', 'Salud'] },
  { p: 'Bostezar', c: 'Acciones', x: ['Sueño', 'Boca', 'Cansado', 'Aburrido', 'Abrir'] },
  { p: 'Aplaudir', c: 'Acciones', x: ['Manos', 'Bravo', 'Teatro', 'Felicitar', 'Ruido'] },
  { p: 'Cocinar', c: 'Acciones', x: ['Comida', 'Olla', 'Chef', 'Receta', 'Fuego'] },
  { p: 'Bailar', c: 'Acciones', x: ['Música', 'Mover', 'Fiesta', 'Pareja', 'Ritmo'] },
  { p: 'Dormir', c: 'Acciones', x: ['Cama', 'Noche', 'Soñar', 'Roncar', 'Descansar'] },
  { p: 'Manejar', c: 'Acciones', x: ['Auto', 'Volante', 'Ruta', 'Licencia', 'Conducir'] },
  { p: 'Pescar', c: 'Acciones', x: ['Caña', 'Río', 'Anzuelo', 'Pez', 'Paciencia'] },
  { p: 'Pintar', c: 'Acciones', x: ['Pincel', 'Colores', 'Cuadro', 'Pared', 'Artista'] },
  { p: 'Silbar', c: 'Acciones', x: ['Boca', 'Sonido', 'Melodía', 'Labios', 'Aire'] },
  { p: 'Abrazar', c: 'Acciones', x: ['Brazos', 'Cariño', 'Apretar', 'Saludo', 'Amor'] },
  { p: 'Correr', c: 'Acciones', x: ['Rápido', 'Piernas', 'Maratón', 'Transpirar', 'Zapatillas'] },
  { p: 'Saltar', c: 'Acciones', x: ['Alto', 'Soga', 'Piernas', 'Rana', 'Brincar'] },
  { p: 'Llorar', c: 'Acciones', x: ['Lágrimas', 'Triste', 'Pañuelo', 'Cebolla', 'Bebé'] },
  { p: 'Reír', c: 'Acciones', x: ['Chiste', 'Carcajada', 'Gracioso', 'Cosquillas', 'Boca'] },
  { p: 'Cantar', c: 'Acciones', x: ['Voz', 'Música', 'Ducha', 'Micrófono', 'Afinar'] },
  { p: 'Escribir', c: 'Acciones', x: ['Lapicera', 'Papel', 'Letras', 'Carta', 'Mano'] },
  { p: 'Fotografiar', c: 'Acciones', x: ['Cámara', 'Foto', 'Sonreír', 'Flash', 'Retrato'] },
  { p: 'Besar', c: 'Acciones', x: ['Labios', 'Amor', 'Pareja', 'Boca', 'Romántico'] },
  { p: 'Gritar', c: 'Acciones', x: ['Fuerte', 'Voz', 'Enojado', 'Susto', 'Garganta'] },
  { p: 'Maquillarse', c: 'Acciones', x: ['Espejo', 'Labial', 'Cara', 'Pintarse', 'Rubor'] },
];
